### ISSUE TITLE
Set Release Version

### ISSUE THREAD

**Issue by bassrock** [getsentry/sentry-symfony#1]
I do not see a way to easily set the release version using this new bundle. Am I overlooking something?

**Comment by dcramer** [comment]
We might not have a good way exposed. Not a Symfony user here, but what would be the best way from your point of view for us to allow you to set it? We can easily add a setRelease method or alternatively a runtime config.

**Comment by bassrock** [comment]
@dcramer The easiest way would be adding it as a config like the sentry_dsn value.

**Comment by cmmata** [comment]
+1 for setting it in config.yml, like sentry_dsn. It's easy to change and automate, and you have other versions in that file (for example assets). You could use the same release version in all the other bundles / settings.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-php/pull/285 will make this easier, but we'll also add some symfony specific config
