### ISSUE TITLE
Generate release and tag

### ISSUE THREAD

**Issue by nunorafaelrocha** [getsentry/sentry-symfony#10]
The current version (0.2.1) has a **huge** bug on the ExceptionListener - It's importing the HttpExceptionInterface instead of HttpException.

Please generate a new release.

**Comment by dcramer** [comment]
What version of Symfony are you using?

**Comment by dcramer** [comment]
I've also pushed out 0.3.0.

**Comment by nunorafaelrocha** [comment]
@dcramer I'm using Symfony v2.7
