### ISSUE TITLE
Exceptions when spooling emails not logged

### ISSUE THREAD

**Issue by willemstuursma** [getsentry/sentry-symfony#100]
If using a memory spool for Swiftmailer and something goes wrong during the email sending, no exception is logged in Sentry.

It would be really nice if this could be logged. Email debugging is hard enough as it is.

The exception is only logged in `\Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate`.

**Comment by Jean85** [comment]
`onTerminate` does this:
```php
try {
    $spool->flushQueue($this->container->get(sprintf('swiftmailer.mailer.%s.transport.real', $name)));
} catch (\Swift_TransportException $exception) {
    if (null !== $this->logger) {
        $this->logger->error(sprintf('Exception occurred while flushing email queue: %s', $exception->getMessage()));
    }
}
```
So if a `Swift_TransportException` is thrown (due to sending errors) there's no way to report it to Sentry, it's immediately catched. Other kinds of exception should bubble up and be reported normally. Is it not the case?

**Comment by willemstuursma** [comment]
Yes, the other stuff works fine but it would be really great if there would be some trick you guys knew in the Symfony framework or maybe open a PR in Symfony to get this specifically resolved / logged appropriately.  

Hitting an exception here is super difficult to debug and it can happen a lot in the normal flow. I am relying on Sentry to alert me of exceptions, including these. 

Basically it is a design flaw in Symfony.

**Comment by Jean85** [comment]
It's not a design flaw, just a limitation of how this bundle works. Maybe you can inject the Sentry client as a PSR-3 logger in Swiftmailer; you could look at https://github.com/facile-it/sentry-psr-log to see if it may help.

**Comment by willemstuursma** [comment]
Ok thanks. It would be great if these would work out of the box. I'll have a look and if I figure something out I'll let you know.
