### ISSUE TITLE
Unable to report error manually

### ISSUE THREAD

**Issue by sc0rp10** [getsentry/sentry-symfony#101]
Hi!
Nice and clear bundle, thank you for your work!
I have problem/proposition: user should be able to report exception manually:
```php
<?php

try {
    return doSmth();
} catch (Exception $e) {
    $error_reporter->processException($e);

    return 'default';
}
```

I think we should have a service that can report exceptions, sets user data etc. And such service we should use inside event listeners for DRY reasons.
What do you think @Jean85?

**Comment by Jean85** [comment]
This is already possible! The service `sentry.client` is public, and you can already use it like this!

If this wasn't clear enough, you're welcome to open a PR to the readme to add this example ;)

**Comment by sc0rp10** [comment]
But how about UserContext?
As I can see, if we use \Raven_Client directly, context will not been set. Am I right?
About PR with docs: I will do it within 1-2 days.

**Comment by Jean85** [comment]
The user context is set by the listener on the `kernel.request` event, so it's always ready!

https://github.com/getsentry/sentry-symfony/blob/70789f4481798334b4c7a7292b823c5e8038aec0/src/EventListener/ExceptionListener.php#L76-L94
