### ISSUE TITLE
Console Exceptions being logged twice

### ISSUE THREAD

**Issue by artureiji** [getsentry/sentry-symfony#104]
Hello, this month my team received a notice that our logging limit was exceeded, and investigating it we found out some errors were being sent to sentry twice.

After a fast test it seems that the Sentry ExceptionListener is listening to both `ConsoleErrorEvent` and `ConsoleExceptionEvent`, that are dispatched by `Symfony\Component\Console\Application` for a single exception that occurs.

sentry-symfony: 2.0
sentry: 1.8.2
symfony: 3.4.4

**Comment by Jean85** [comment]
Thanks for reporting this. I attached the listener to both events because I wanted to have cross compatibility for Symfony 3 and 4, but this is leading to this bug.

I'll try to find an other solution.

**Comment by Jean85** [comment]
Fix released as [2.0.1](https://github.com/getsentry/sentry-symfony/releases/tag/2.0.1)!

**Comment by xthiago** [comment]
Thank you @Jean85
