### ISSUE TITLE
Errors are duplicated when using trigger_error()

### ISSUE THREAD

**Issue by DarthSaracen** [getsentry/sentry-symfony#106]
Hey there.
I've created my own ExceptionListener as official guide says, but in some cases got duplicated errors in Sentry. After some investigations, found that this only happens with trigger_error() function. Here's a stacktrace of calling Raven_Client->send(), when only one trigger_error() called.

Any suggestions?

`0. Raven_Client->send() called at [.../vendor/sentry/sentry/lib/Raven/Client.php:898]`
`1. Raven_Client->capture() called at [.../vendor/sentry/sentry/lib/Raven/Client.php:650]`
`2. Raven_Client->captureException() called at [.../vendor/sentry/sentry/lib/Raven/ErrorHandler.php:78]`
`3. Raven_ErrorHandler->handleException() called at [.../vendor/sentry/sentry/lib/Raven/ErrorHandler.php:103]`
`4. Raven_ErrorHandler->handleError()`
`5. trigger_error() called at [.../src/Controller/Index.php:31]`
`6. App\Controller\Index->indexAction() called at [.../vendor/symfony/http-kernel/HttpKernel.php:151]`
`7. Symfony\Component\HttpKernel\HttpKernel->handleRaw() called at [.../vendor/symfony/http-kernel/HttpKernel.php:68]`
`8. Symfony\Component\HttpKernel\HttpKernel->handle() called at [.../vendor/symfony/http-kernel/Kernel.php:169]`
`9. Symfony\Component\HttpKernel\Kernel->handle() called at [.../public/index.php:38]`
`string(9) "Hey there"`

`0. Raven_Client->send() called at [.../vendor/sentry/sentry/lib/Raven/Client.php:898]`
`1. Raven_Client->capture() called at [.../vendor/sentry/sentry/lib/Raven/Client.php:650]`
`2. Raven_Client->captureException() called at [.../src/Sentry/ExceptionListener.php:40]`
`3. App\Sentry\ExceptionListener->onKernelException()`
`4. call_user_func() called at [.../vendor/symfony/event-dispatcher/Debug/WrappedListener.php:104]`
`5. Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() called at [.../vendor/symfony/event-dispatcher/EventDispatcher.php:212]`
`6. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() called at [.../vendor/symfony/event-dispatcher/EventDispatcher.php:44]`
`7. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() called at [.../vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139]`
`8. Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() called at [.../vendor/symfony/http-kernel/HttpKernel.php:228]`
`9. Symfony\Component\HttpKernel\HttpKernel->handleException() called at [.../vendor/symfony/http-kernel/HttpKernel.php:79]`
`10. Symfony\Component\HttpKernel\HttpKernel->handle() called at [.../vendor/symfony/http-kernel/Kernel.php:169]`
`11. Symfony\Component\HttpKernel\Kernel->handle() called at [.../public/index.php:38]`
`string(22) "User Notice: Hey there"`

Sry for my english btw

**Comment by Jean85** [comment]
Does this happen with the normal listener or only with your custom one?
If it's the latter, can you post your code?

**Comment by Jean85** [comment]
Closing this as stale.
