### ISSUE TITLE
Reducing build time for the flag "--prefer-lowest"

### ISSUE THREAD

**Issue by agentsib** [getsentry/sentry-symfony#110]
Hello!

At the moment, build time for cases with  "-prefer-lower" flag is extremely slow. In some cases because of the timeout build is unsuccessful.

Just a suggestion. I think the build time can be reduced if you add a file `composer-5.6-lowest.lock`. Before build with '--prefer-lowest' flag you can replace `composer.lock` file and run `composer install`.

Or you can cache file between builds (`composer-5.6-lowest.lock`)

What do you think about it?

PS. Sorry for my english :)

**Comment by Jean85** [comment]
Caching it between builds could be an good idea! But we need a successful build first....
Or maybe we could run a generic `composer install` first and then run it with the `--prefer-lowest`?

**Comment by agentsib** [comment]
> Or maybe we could run a generic composer install first and then run it with the --prefer-lowest?

Without composer.lock file it will not help.

Case 1:

```bash
# time composer install

real	0m5,371s
user	0m2,239s
sys	0m0,514s

# time composer  update --no-interaction --prefer-dist --prefer-stable --prefer-lowest 

real	2m23,637s
user	2m22,082s
sys	0m0,651s

```

Case 2 (https://gist.github.com/agentsib/2e57aacd37a31f2cba8b5273a66d233b):

``` bash
# cp ./build/composer-5.6-lowest.lock ./composer.lock
# composer install 


real	0m1,197s
user	0m0,513s
sys	0m0,383s

# time composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest 

real	0m16,212s
user	0m12,744s
sys	0m0,088s

**Comment by Jean85** [comment]
Mh, thanks for the detailed test! HAve you tried with the lock file and doing the update directly, without the install?

**Comment by agentsib** [comment]
@ Jean85, without `composer install` slowly. Only copying `*.lock` file and `composer install` before updating helps.

```bash
# rm -rf vendor/ composer.lock 
# cp ./build/composer-5.6-lowest.lock composer.lock
# time composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest

real	3m52,679s
user	0m0,024s
sys	0m0,011s
```
```bash
# rm -rf vendor/ composer.lock 
# cp ./build/composer-5.6-lowest.lock composer.lock
# time composer install

real	0m1,498s
user	0m0,481s
sys	0m0,362s
# time composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest

real	0m43,325s
user	0m14,087s
sys	0m0,093s
```

**Comment by agentsib** [comment]
When I have time, I will create PR. We will test on Travis :)

**Comment by Jean85** [comment]
I don't know why, but I'm unable to produce a prefer-lowest locally, the process hangs a lot like in Travis, it seems stuck in a loop!

How were you able to execute it the first time?

**Comment by agentsib** [comment]
I ran locally (`composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest`). Perhaps my computer is more powerful.

**Comment by Jean85** [comment]
I left it open during lunch, so ~1h! It seems to use a single core fully, so it should be stuck in a loop. Maybe you're using an older Composer version? I was working inside a container so Composer was freshly installed...

If this approach could fail, we could try a different approach, and simply require manually Symfony 2.7.*, so we would greatly reduce the number of versions that would be allowed for comparison, hence reducing Composer's workload.

**Comment by agentsib** [comment]
Unfortunately, my decision did not work. But I found another problem. The cases with flag '--prefer-lowest' is not entirely honest. Package `friendsofphp/php-cs-fixer` dependency requires a `symfony-console` 3.0 or higher.

If in `composer.json` remove `friendsofphp/php-cs-fixer` and replace versions from '^2.7|^3.0' to '^2.7', update will be fast.

**Comment by Jean85** [comment]
So maybe that's what is currently stalling composer? So maybe a manual `composer remove` of that tool (when `--prefer-lowest` is used) from the requirements may fix everything?

**Comment by agentsib** [comment]
I thinks it's help! https://travis-ci.org/getsentry/sentry-symfony/builds/346860476 :tada:

**Comment by agentsib** [comment]
I suppose a more elegant solution is remove `friendsofphp/php-cs-fixer` and use phar version :)

**Comment by Jean85** [comment]
Using the PHAR is annoying for contributors, because it would not be present for local development...

**Comment by agentsib** [comment]
Maybe you can add phar to repository... Or make composer task for download it before run.

**Comment by Jean85** [comment]
Solved! https://travis-ci.org/getsentry/sentry-symfony/builds/347166863

Many thanks @agentsib
