### ISSUE TITLE
Why should I use this package and not jus sentry/sentry w/monolog?

### ISSUE THREAD

**Issue by tarjei** [getsentry/sentry-symfony#113]
Hi, one thing I think the README is missing is description of what this package gives you that the monolog integration does not. Would you mind giving some hints and I'll create a PR for the README.

Kind regards,
Tarjei

**Comment by Jean85** [comment]
Hi, thanks for the suggestion!
Well, IMO the main advantages are:
 * easiness of configuration: add the bundle, set the DSN and you're done
 * container registration: you get the `sentry.client` public service available
 * automatic wiring to app: the events have the following things added automatically to the events:
   * user
   * Symfony environment 
   * app path
   * hostname
   * excluded paths (cache and vendor)

**Comment by Jean85** [comment]
Solved by #115

**Comment by scaytrase** [comment]
I think this bundle still misses some benefits monolog intergration has:
* Exception logging inside your application (a.k.a "Recoverable exceptions")
* Configurable log level
* Buffering 

For me the best solution for this bundle is moving to automatic registration of monolog handler, so we can keep easyness of configuration and DI alongside the flexibility of monolog handler usage

WDYT?

**Comment by Jean85** [comment]
Registering this as a Monolog handler would mean relying on the MonologBundle itself, and I think it would be hard and fragile at the same time; also, that is already achievable with other packages.

As for recoverable exceptions, you can already do it, with a `try...catch` where you use the `sentry.client` service to capture the exception, and later recover from it.

**Comment by scaytrase** [comment]
using sentry client makes code dependent on sentry which is less preferrable than general `LoggerInterface`

**Comment by Jean85** [comment]
That's why I was pointing you toward other packages, like https://github.com/facile-it/sentry-psr-log

**Comment by scaytrase** [comment]
No offence, but this one looks like barely supported clone of original raven client with some improvements

https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Client.php#L622-L648
https://github.com/facile-it/sentry-common/blob/master/src/StackTrace/StackTrace.php#L69-L92

Having monolog bridges in official sentry would be more consistent, since exception are already logged according to PSR-3 in `exception` context field in native console and web kernel listeners

**Comment by Jean85** [comment]
Yes, I know that; I'm just saying that doing that job is partly out of scope for this lib, and partly incomplete, since that approach does not cover the case of fatals, or errors under PHP less than 7.

**Comment by scaytrase** [comment]
I see the problem of using 3rd party packages alongside the bundle in that fact that unhandled exceptions will be logged twice - one within this bundle and one with generic PSR-3 logger in built-in handler. But this library works well as raven client bootstrapper, so I think we can just introduce an option to disable handlers for this case here?

**Comment by Jean85** [comment]
That would be a significant amount of work; I'm willing to accept PRs in that direction though...
