### ISSUE TITLE
Sentry 1.x fails to send errors/events to Sentry server when AliceBundle is enabled in the Application.

### ISSUE THREAD

**Issue by d-ph** [getsentry/sentry-symfony#122]
Hi,

Just wanted to let people know that `getsentry/sentry-php@1.*` fails to send errors to the Sentry server when devs use the `hautelook/AliceBundle` or `nelmio/alice` in their application. This is because those Alice packages run `mt_srand(1)` by default, which pwns everything in devs' apps that uses `mt_rand()` ([link](https://github.com/nelmio/alice/issues/124)). This unfortunately includes `getsentry/sentry-php < v2.0`, which uses `mt_rand()` to generate uuid4 for the `event_id` for Sentry Events. Sentry server refuses to accept Events with duplicated `event_id`s, which happens due to constantly `mt_srand(1)`ing to the same value.

This doesn't occur during http requests (unless devs obtain one of the Alice services in their code). This, however, happens _every time_ when a cli command is run, due to the fact that the Alice cli command instantiates other Alice services, which in turn `mt_srand(1)` by default.

In other words, if devs use AliceBundle and Sentry(Bundle) < v2.0, their cli commands silently won't be sending exception reports to their Sentry server. Either that, or an exception will be logged in Sentry but with no events (the `Sorry, the events for this issue could not be found.` error).

The solutions:
1. Upgrade getsentry/sentry-php to v2.0 (once it's released), which uses `ramsey/uuid` to generate the uuid4s. `ramsey/uuid` in turn uses php7's `random_bytes()` (or the polyfil package) instead of `mt_rand()` to construct parts of the uuid4.
2. Add the following event subscriber to your app:
```php
<?php

use Hautelook\AliceBundle\Doctrine\Command\LoadDataFixturesCommand;
use Symfony\Component\Console\ConsoleEvents;
use Symfony\Component\Console\Event\ConsoleCommandEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class ConsoleEventSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            ConsoleEvents::COMMAND => ['onConsoleCommandStart', 0],
        ];
    }

    public function onConsoleCommandStart(ConsoleCommandEvent $event): void
    {
        if (!$event->getCommand() instanceof LoadDataFixturesCommand) {
            mt_srand();
        }
    }
}
```
3. Configure the AliceBundle not to use a constant seed value by setting it to `null`.

To the maintainer of `getsentry/sentry-symfony`: You really want to upgrade this bundle to support `getsentry/sentry-php@^2.0` as soon as it's released to save devs the frustration.

That's all I have to say. Hope it helps someone.

**Comment by Jean85** [comment]
Thanks for reporting this issue. 

I would note that the Alice bundle should be used on dev environment only, and on the contrary the Sentry bundle should be used on staging/prod environment. A good fix would be to avoid registering both bundles at the same time.

**Comment by d-ph** [comment]
I use Alice in my testing environments to have some dummy data during QA testing.

I do, however, agree with what you said, regardless.
