### ISSUE TITLE
Support for symfony 2.3

### ISSUE THREAD

**Issue by diegocastro** [getsentry/sentry-symfony#14]
Support for symfony 2.3 was dropped on version 0.3.0 even though symfony 2.3 is still maintained until may 2017.

**Comment by dcramer** [comment]
Open to ideas how we support both. I believe we bumped version due to compatibility.

**Comment by diegocastro** [comment]
I'll look into the code and run some tests and report back.

**Comment by Jean85** [comment]
This issue is stale.
Also, Symfony 2.3 will fall out of LTS support this month, so I don't think it's valuable to pursue this any further.
