### ISSUE TITLE
respect APP_ENV

### ISSUE THREAD

**Issue by landsman** [getsentry/sentry-symfony#140]
Hi,
I think that in develop environment Sentry should not log errors.
Using: Symfony 4 with .env file configuration.

**Comment by Jean85** [comment]
I don't think it's up to the bundle to decide that on behalf of the user, but that's the suggested behavior in both the readme and the [Flex recipe](https://github.com/symfony/recipes-contrib/tree/master/sentry/sentry-symfony/1.0/config/packages), which registers a DSN only under the prod environment.
