### ISSUE TITLE
Send session data

### ISSUE THREAD

**Issue by zhil** [getsentry/sentry-symfony#143]
It would be nice to see sesson data in sentry issues. I plan to implement it, could such a PR be accepted?

**Comment by Jean85** [comment]
Session data may frequently be sensitive, so I don't think it should be added as a default.

**Comment by zhil** [comment]
@Jean85 ok, what about disabled by default + some easy way to enable it in config?

**Comment by Jean85** [comment]
That would be better...

**Comment by zhil** [comment]
@Jean85 added #144 
let me know if its acceptable

**Comment by Jean85** [comment]
First and foremost, we should differentiate between `$_SESSION` and the session service, it's not the same.
Second, the sentry-php behavior shouldn't be changed, too much stuff relies on that; the bundle should adapt itself to that, not the other way around.
Third, I think we should clarify what stuff should or shouldn't be sent from the session to Sentry; I fear that sending the whole session data is detrimental at the end.

**Comment by zhil** [comment]
@Jean85 well, current sentry-symfony-bundle + sentry-php behavior is kind of strange - for not logged in users it send all session data(including symfony internals session data), for logged in users - do not send any session data.

as for me - most logical way would be mimic sentry-php behavior, with username instead of session_id and _SESSION array in $user['data']

**Comment by zhil** [comment]
ok, in my case I have such a bug with bundle - session data is not send for logged in users.
I have solved it using simple EventSubscriber
```
<?php
namespace App\SomeBundle\EventSubscriber;

use Sentry\SentryBundle\SentrySymfonyEvents;
use Symfony\Component\EventDispatcher\Event;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent;

class MySentryEventSubscriber implements EventSubscriberInterface
{
    /** @var \Raven_Client */
    protected $client;

    /** @var Session */
    protected $session;

    public function __construct(\Raven_Client $client, Session $session)
    {
        $this->client = $client;
        $this->session = $session;
    }

    public static function getSubscribedEvents()
    {
        // return the subscribed events, their methods and priorities
        return array(
            SentrySymfonyEvents::PRE_CAPTURE => 'onPreCapture',
        );
    }


    public function onPreCapture(Event $event)
    {
        if ($event instanceof GetResponseForExceptionEvent) {
            $this->client->user_context($this->session->all(), true);
        }
    }
}
```

@Jean85 issue is closed on my side. Not sure what should we do with bundle - let me know.

**Comment by Jean85** [comment]
I would avoid changing the bundle further for now; there are plenty of extension points, as you did use.

If this will be requested by more users, I would reconsider implementing something new.
