### ISSUE TITLE
PHP memory limits error is not catched

### ISSUE THREAD

**Issue by zhil** [getsentry/sentry-symfony#146]
For some reasons memory limit error is not catched.

Steps to reproduce

* git clone git@github.com:zhil/SentrySymfonyMemoryLimit.git
* cd SentrySymfonyMemoryLimit
* composer install
* put valid sentry DSN in parameters.yml
* ./bin/console server:run --docroot=web --env=prod
* http://127.0.0.1:8000/fatal runtime error catched
* http://127.0.0.1:8000/mem memory limit error is not catched

**Comment by Jean85** [comment]
I'm sorry but I can't reproduce the issue; I get events on both cases. What PHP version are you using? I tested using PHP 7.2.

**Comment by Jean85** [comment]
Closing as stale, please reply or reopen if still valid.

**Comment by zhil** [comment]
@Jean85 issue still exists, used the same steps above

tested on
```
tested on sentry/sentry                        1.9.1
sentry/sentry-symfony                2.0.3
```
and
```
tested on sentry/sentry                        1.9.1
sentry/sentry-symfony                2.1
```

**Comment by Jean85** [comment]
Still cannot reproduce. Your memory limit trigger doesn't work for me, it's doesn't end the request and I even get correctly the "time limit exceeded" error reported to Sentry. 

I even changed the controller to not check `memory_get_usage`, but if I do that the PHP server crashes, so the reproducer is no longer good.

**Comment by Jean85** [comment]
I did it but it wasn't useful. Maybe you should try to create a reproducer using a proper web server (with Docker maybe?)

**Comment by zhil** [comment]
@Jean85 as I remember, it doesnt work in command line mode. I have changed test repo to docker container

```
git clone https://github.com/zhil/SentrySymfonyMemoryLimit.git
PUT VALID DSN IN docker/app/config/parameters.yml.dist
docker-compose build
docker-compose up -d
```
http://127.0.0.1:8000/fatal runtime error catched
http://127.0.0.1:8000/mem memory limit error is not catched

**Comment by Jean85** [comment]
Ok I'm now able to reproduce. I'll try to debug this further.

**Comment by zhil** [comment]
@Jean85 any success with this issue?

**Comment by Jean85** [comment]
No sorry. In the meantime, I started working on v3.0 on master, which uses the completely new 2.0 base SDK.

It's nearly complete, can you test against that version to see if it solved there?

**Comment by Jean85** [comment]
Closing this a stale. Feel free to reopen if v3 still has this issue.
