### ISSUE TITLE
Service to send exception manually ?

### ISSUE THREAD

**Issue by pesseyjulien** [getsentry/sentry-symfony#147]
Hi,

Is there a way to send exception manually using a service ?

Thanks in advance,
Julien

**Comment by pesseyjulien** [comment]
Thanks for your quick feedback !

I have tried this, but it does not seem to be working (see enclosed).

Wrong name ?

![capture d ecran 2018-07-03 a 20 20 15](https://user-images.githubusercontent.com/10850944/42237642-a9d335fe-7efe-11e8-8a32-9731ecd4dcc2.jpg)

**Comment by Jean85** [comment]
Nope, the name is the right one: https://github.com/getsentry/sentry-symfony/blob/f4529a0fb9a109d6be4f03d5712ea2a3d956096d/src/Resources/config/services.yml#L2-L7

Remember that that integration in PHPStorm is powered by the Symfony plugin, which in turn leverages the Symfony cache of your project to decode i.e. service names; in this specific case, if you (correctly) didn't enable the bundle in the dev environment, you will not have the service in your container locally, hence the plugin will not be able to recognize it.

Closing this as resolved, feel free to reply further.

**Comment by pesseyjulien** [comment]
true that, forgot about this :)

Thanks !
