### ISSUE TITLE
Allow to disable the exception listener completely

### ISSUE THREAD

**Issue by Toflar** [getsentry/sentry-symfony#148]
Hi,

I would like to disable the exception listener completely.
I know that I can replace the core one with some NoopListener but I don't really want to add that to my repository everywhere I use it. Something like this would be much more convenient:

```yaml
sentry:
    exception_listener: false
```

The reason why I need this is that in `dev` environment, I don't want exceptions to be reported to Sentry but that doesn't mean I don't want to use this bundle. I need this bundle because I use `captureMessage()` etc. on the client at various places in the code. So disabling the bundle in `dev` is not really an option.
Wdyt?

**Comment by Jean85** [comment]
Setting the DSN to false enables you to reach the same goal; from the README:

> Leaving this value empty will effectively disable Sentry reporting.

**Comment by Toflar** [comment]
I don't want to disable reporting. Setting DSN to `''` is not an option because **I do want to report manually even in dev system for certain things** but I want to disable the general exception listener :)

**Comment by Jean85** [comment]
In #156 I'm thinking about dropping the listener on a new major version. The main problem here is that the `Client::install()` is needed to catch everything, so the listener can go to avoid duplications..

**Comment by DanielSchwiperich** [comment]
@Toflar 
I think you could reach your goad with using the skip_capture option. 
if you put a sentry.yml in the dev packages folder and configure it that way
```
...
    skip_capture: 
      - '\Exception'
```
this should mute all Exceptions since all extend `\Exception` in the end and the ExceptionListener is using `instanceof` for testing if exception capturing should be skipped.

**Comment by Toflar** [comment]
lol, nice idea!

**Comment by Jean85** [comment]
Closing this as stale. Also, this is achievable with the new PHP SDK through the error listeners implemented in https://github.com/getsentry/sentry-php/pull/762 and https://github.com/getsentry/sentry-php/pull/788
