### ISSUE TITLE
Composer install error 

### ISSUE THREAD

**Issue by pesseyjulien** [getsentry/sentry-symfony#149]
Hi,

I sometimes get the following error after some deployment and composer install. 
It's happening when I try to clear the cache :

```
  Type error: Argument 3 passed to Sentry\SentryBundle\EventListener\ExceptionListener::__construct() must be an
  instance of Symfony\Component\HttpFoundation\RequestStack, array given, called in /home/ec2-user/www/front-foot
  ball/releases/16072018-121601/app/cache/prod/ContainerA3y9yv9/appProdProjectContainer.php on line 2436

```

Any idea why ?

Thanks,
Julien

**Comment by Jean85** [comment]
Have you altered the bundle's wiring configuration? Or the configuration for the `request_stack` service? What version of Symfony are you running?

**Comment by pesseyjulien** [comment]
Nop, I did not. Running SF 3.4.12.

**Comment by Jean85** [comment]
It seems to me that you have something strange in your container configuration, I suggest to you to use the `bin/console debug:container` command.

**Comment by pesseyjulien** [comment]
I did, got this :

---------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------ 
  Service ID                                                                                     Class name                                                                                
 ---------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------ 
  Symfony\Bundle\FrameworkBundle\Controller\RedirectController                                   Symfony\Bundle\FrameworkBundle\Controller\RedirectController                              
  Symfony\Bundle\FrameworkBundle\Controller\TemplateController                                   Symfony\Bundle\FrameworkBundle\Controller\TemplateController                              
  addict_web.api                                                                                 Addict\Bundle\WebBundle\Services\ApiService                                               
  cache.app                                                                                      Symfony\Component\Cache\Adapter\TraceableAdapter                                          
  cache.app_clearer                                                                              alias for "cache.default_clearer"                                                         
  cache.global_clearer                                                                           Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer                                
  cache.system                                                                                   Symfony\Component\Cache\Adapter\TraceableAdapter                                          
  cache.system_clearer                                                                           Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer                                
  cache_clearer                                                                                  Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer                               
  cache_warmer                                                                                   Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate                             
  console.command.doctrine_bundle_doctrinecachebundle_command_containscommand                    alias for "doctrine_cache.contains_command"                                               
  console.command.doctrine_bundle_doctrinecachebundle_command_deletecommand                      alias for "doctrine_cache.delete_command"                                                 
  console.command.doctrine_bundle_doctrinecachebundle_command_flushcommand                       alias for "doctrine_cache.flush_command"                                                  
  console.command.doctrine_bundle_doctrinecachebundle_command_statscommand                       alias for "doctrine_cache.stats_command"                                                  
  console.command.doctrine_bundle_mongodbbundle_command_clearmetadatacachedoctrineodmcommand     alias for "Doctrine\Bundle\MongoDBBundle\Command\ClearMetadataCacheDoctrineODMCommand"    
  console.command.doctrine_bundle_mongodbbundle_command_createschemadoctrineodmcommand           alias for "Doctrine\Bundle\MongoDBBundle\Command\CreateSchemaDoctrineODMCommand"          
  console.command.doctrine_bundle_mongodbbundle_command_dropschemadoctrineodmcommand             alias for "Doctrine\Bundle\MongoDBBundle\Command\DropSchemaDoctrineODMCommand"            
  console.command.doctrine_bundle_mongodbbundle_command_generatedocumentsdoctrineodmcommand      alias for "Doctrine\Bundle\MongoDBBundle\Command\GenerateDocumentsDoctrineODMCommand"     
  console.command.doctrine_bundle_mongodbbundle_command_generatehydratorsdoctrineodmcommand      alias for "Doctrine\Bundle\MongoDBBundle\Command\GenerateHydratorsDoctrineODMCommand"     
  console.command.doctrine_bundle_mongodbbundle_command_generateproxiesdoctrineodmcommand        alias for "Doctrine\Bundle\MongoDBBundle\Command\GenerateProxiesDoctrineODMCommand"       
  console.command.doctrine_bundle_mongodbbundle_command_generaterepositoriesdoctrineodmcommand   alias for "Doctrine\Bundle\MongoDBBundle\Command\GenerateRepositoriesDoctrineODMCommand"  
  console.command.doctrine_bundle_mongodbbundle_command_infodoctrineodmcommand                   alias for "Doctrine\Bundle\MongoDBBundle\Command\InfoDoctrineODMCommand"                  
  console.command.doctrine_bundle_mongodbbundle_command_loaddatafixturesdoctrineodmcommand       alias for "Doctrine\Bundle\MongoDBBundle\Command\LoadDataFixturesDoctrineODMCommand"      
  console.command.doctrine_bundle_mongodbbundle_command_querydoctrineodmcommand                  alias for "Doctrine\Bundle\MongoDBBundle\Command\QueryDoctrineODMCommand"                 
  console.command.doctrine_bundle_mongodbbundle_command_sharddoctrineodmcommand                  alias for "Doctrine\Bundle\MongoDBBundle\Command\ShardDoctrineODMCommand"                 
  console.command.doctrine_bundle_mongodbbundle_command_tailcursordoctrineodmcommand             alias for "Doctrine\Bundle\MongoDBBundle\Command\TailCursorDoctrineODMCommand"            
  console.command.doctrine_bundle_mongodbbundle_command_updateschemadoctrineodmcommand           alias for "Doctrine\Bundle\MongoDBBundle\Command\UpdateSchemaDoctrineODMCommand"          
  console.command.lexik_bundle_translationbundle_command_exporttranslationscommand               alias for "Lexik\Bundle\TranslationBundle\Command\ExportTranslationsCommand"              
  console.command.lexik_bundle_translationbundle_command_importtranslationscommand               alias for "Lexik\Bundle\TranslationBundle\Command\ImportTranslationsCommand"              
  console.command.maxmind_bundle_geoipbundle_command_loaddatacommand                             alias for "maxmind_bundle_geoip.command.load_data_command"                                
  console.command_loader                                                                         Symfony\Component\Console\CommandLoader\ContainerCommandLoader                            
  craue_config                                                                                   alias for "craue_config_default"                                                          
  craue_config_cache_adapter                                                                     Craue\ConfigBundle\CacheAdapter\DoctrineCacheBundleAdapter                                
  craue_config_cache_provider                                                                    alias for "doctrine_cache.providers.craue_config_cache"                                   
  craue_config_default                                                                           Craue\ConfigBundle\Util\Config                                                            
  data_collector.dump                                                                            Symfony\Component\HttpKernel\DataCollector\DumpDataCollector                              
  database_connection                                                                            alias for "doctrine.dbal.default_connection"                                              
  doctrine                                                                                       Doctrine\Bundle\DoctrineBundle\Registry                                                   
  doctrine.dbal.default_connection                                                               Doctrine\DBAL\Connection                                                                  
  doctrine.orm.default_entity_manager                                                            Doctrine\ORM\EntityManager                                                                
  doctrine.orm.default_metadata_cache                                                            alias for "doctrine_cache.providers.doctrine.orm.default_metadata_cache"                  
  doctrine.orm.default_query_cache                                                               alias for "doctrine_cache.providers.doctrine.orm.default_query_cache"                     
  doctrine.orm.default_result_cache                                                              alias for "doctrine_cache.providers.doctrine.orm.default_result_cache"                    
  doctrine.orm.entity_manager                                                                    alias for "doctrine.orm.default_entity_manager"                                           
  doctrine_cache.providers.craue_config_cache                                                    Doctrine\Common\Cache\RedisCache                                                          
  doctrine_cache.providers.doctrine.orm.default_metadata_cache                                   Doctrine\Common\Cache\ArrayCache                                                          
  doctrine_cache.providers.doctrine.orm.default_query_cache                                      Doctrine\Common\Cache\ArrayCache                                                          
  doctrine_cache.providers.doctrine.orm.default_result_cache                                     Doctrine\Common\Cache\ArrayCache                                                          
  doctrine_mongodb                                                                               Doctrine\Bundle\MongoDBBundle\ManagerRegistry                                             
  doctrine_mongodb.odm.default_connection                                                        Doctrine\MongoDB\Connection                                                               
  doctrine_mongodb.odm.default_document_manager                                                  Doctrine\ODM\MongoDB\DocumentManager                                                      
  doctrine_mongodb.odm.document_manager                                                          alias for "doctrine_mongodb.odm.default_document_manager"                                 
  eight_points_guzzle.client.addict_api                                                          GuzzleHttp\Client                                                                         
  eight_points_guzzle.formatter                                                                  GuzzleHttp\MessageFormatter                                                               
  eight_points_guzzle.logger                                                                     EightPoints\Bundle\GuzzleBundle\Log\Logger                                                
  eight_points_guzzle.middleware.event_dispatch.addict_api                                       EightPoints\Bundle\GuzzleBundle\Middleware\EventDispatchMiddleware                        
  eight_points_guzzle.middleware.log.addict_api                                                  EightPoints\Bundle\GuzzleBundle\Middleware\LogMiddleware                                  
  eight_points_guzzle.middleware.request_time.addict_api                                         EightPoints\Bundle\GuzzleBundle\Middleware\RequestTimeMiddleware                          
  eight_points_guzzle.middleware.symfony_log                                                     EightPoints\Bundle\GuzzleBundle\Middleware\SymfonyLogMiddleware                           
  eight_points_guzzle.symfony_log_formatter                                                      GuzzleHttp\MessageFormatter                                                               
  event_dispatcher                                                                               alias for "debug.event_dispatcher"                                                        
  filesystem                                                                                     Symfony\Component\Filesystem\Filesystem                                                   
  form.factory                                                                                   Symfony\Component\Form\FormFactory                                                        
  form.type.birthday                                                                             Symfony\Component\Form\Extension\Core\Type\BirthdayType                                   
  form.type.button                                                                               Symfony\Component\Form\Extension\Core\Type\ButtonType                                     
  form.type.checkbox                                                                             Symfony\Component\Form\Extension\Core\Type\CheckboxType                                   
  form.type.collection                                                                           Symfony\Component\Form\Extension\Core\Type\CollectionType                                 
  form.type.country                                                                              Symfony\Component\Form\Extension\Core\Type\CountryType                                    
  form.type.currency                                                                             Symfony\Component\Form\Extension\Core\Type\CurrencyType                                   
  form.type.date                                                                                 Symfony\Component\Form\Extension\Core\Type\DateType                                       
  form.type.datetime                                                                             Symfony\Component\Form\Extension\Core\Type\DateTimeType                                   
  form.type.email                                                                                Symfony\Component\Form\Extension\Core\Type\EmailType                                      
  form.type.file                                                                                 Symfony\Component\Form\Extension\Core\Type\FileType                                       
  form.type.hidden                                                                               Symfony\Component\Form\Extension\Core\Type\HiddenType                                     
  form.type.integer                                                                              Symfony\Component\Form\Extension\Core\Type\IntegerType                                    
  form.type.language                                                                             Symfony\Component\Form\Extension\Core\Type\LanguageType                                   
  form.type.locale                                                                               Symfony\Component\Form\Extension\Core\Type\LocaleType                                     
  form.type.money                                                                                Symfony\Component\Form\Extension\Core\Type\MoneyType                                      
  form.type.number                                                                               Symfony\Component\Form\Extension\Core\Type\NumberType                                     
  form.type.password                                                                             Symfony\Component\Form\Extension\Core\Type\PasswordType                                   
  form.type.percent                                                                              Symfony\Component\Form\Extension\Core\Type\PercentType                                    
  form.type.radio                                                                                Symfony\Component\Form\Extension\Core\Type\RadioType                                      
  form.type.range                                                                                Symfony\Component\Form\Extension\Core\Type\RangeType                                      
  form.type.repeated                                                                             Symfony\Component\Form\Extension\Core\Type\RepeatedType                                   
  form.type.reset                                                                                Symfony\Component\Form\Extension\Core\Type\ResetType                                      
  form.type.search                                                                               Symfony\Component\Form\Extension\Core\Type\SearchType                                     
  form.type.submit                                                                               Symfony\Component\Form\Extension\Core\Type\SubmitType                                     
  form.type.text                                                                                 Symfony\Component\Form\Extension\Core\Type\TextType                                       
  form.type.textarea                                                                             Symfony\Component\Form\Extension\Core\Type\TextareaType                                   
  form.type.time                                                                                 Symfony\Component\Form\Extension\Core\Type\TimeType                                       
  form.type.timezone                                                                             Symfony\Component\Form\Extension\Core\Type\TimezoneType                                   
  form.type.url                                                                                  Symfony\Component\Form\Extension\Core\Type\UrlType                                        
  fos_js_routing.controller                                                                      FOS\JsRoutingBundle\Controller\Controller                                                 
  fos_js_routing.extractor                                                                       FOS\JsRoutingBundle\Extractor\ExposedRoutesExtractor                                      
  fos_js_routing.serializer                                                                      Symfony\Component\Serializer\Serializer                                                   
  http_kernel                                                                                    Symfony\Component\HttpKernel\HttpKernel                                                   
  httplug.client                                                                                 alias for "httplug.client.default"                                                        
  httplug.message_factory                                                                        alias for "httplug.message_factory.default"                                               
  httplug.stream_factory                                                                         alias for "httplug.stream_factory.default"                                                
  httplug.uri_factory                                                                            alias for "httplug.uri_factory.default"                                                   
  hwi_oauth.http.client                                                                          alias for "httplug.client.default"                                                        
  hwi_oauth.http.message_factory                                                                 alias for "httplug.message_factory.default"                                               
  hwi_oauth.http_client                                                                          Http\Client\Common\HttpMethodsClient                                                      
  hwi_oauth.resource_owner.facebook                                                              HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\FacebookResourceOwner                          
  hwi_oauth.resource_owner.google                                                                HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner                            
  hwi_oauth.resource_owner.twitter                                                               HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\TwitterResourceOwner                           
  hwi_oauth.security.oauth_utils                                                                 HWI\Bundle\OAuthBundle\Security\OAuthUtils                                                
  hwi_oauth.user_checker                                                                         alias for "security.user_checker"                                                         
  kernel                                                                                                                                                                                   
  knp_menu.factory                                                                               Knp\Menu\MenuFactory                                                                      
  knp_menu.matcher                                                                               Knp\Menu\Matcher\Matcher                                                                  
  lexik_translation.data_grid.formatter                                                          Lexik\Bundle\TranslationBundle\Util\DataGrid\DataGridFormatter                            
  lexik_translation.data_grid.request_handler                                                    Lexik\Bundle\TranslationBundle\Util\DataGrid\DataGridRequestHandler                       
  lexik_translation.exporter_collector                                                           Lexik\Bundle\TranslationBundle\Translation\Exporter\ExporterCollector                     
  lexik_translation.form.handler.trans_unit                                                      Lexik\Bundle\TranslationBundle\Form\Handler\TransUnitFormHandler                          
  lexik_translation.importer.file                                                                Lexik\Bundle\TranslationBundle\Translation\Importer\FileImporter                          
  lexik_translation.locale.manager                                                               Lexik\Bundle\TranslationBundle\Manager\LocaleManager                                      
  lexik_translation.overview.stats_aggregator                                                    Lexik\Bundle\TranslationBundle\Util\Overview\StatsAggregator                              
  lexik_translation.trans_unit.manager                                                           Lexik\Bundle\TranslationBundle\Manager\TransUnitManager                                   
  lexik_translation.translation_storage                                                          Lexik\Bundle\TranslationBundle\Storage\DoctrineORMStorage                                 
  lexik_translation.translator                                                                   Lexik\Bundle\TranslationBundle\Translation\Translator                                     
  profiler                                                                                       Symfony\Component\HttpKernel\Profiler\Profiler                                            
  request_stack                                                                                  Symfony\Component\HttpFoundation\RequestStack                                             
  router                                                                                         alias for "router.default"                                                                
  routing.loader                                                                                 Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader                                   
  security.authentication_utils                                                                  Symfony\Component\Security\Http\Authentication\AuthenticationUtils                        
  security.authorization_checker                                                                 Symfony\Component\Security\Core\Authorization\AuthorizationChecker                        
  security.csrf.token_manager                                                                    Symfony\Component\Security\Csrf\CsrfTokenManager                                          
  security.password_encoder                                                                      alias for "security.user_password_encoder.generic"                                        
  security.token_storage                                                                         Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage                 
  service_container                                                                              Symfony\Component\DependencyInjection\ContainerInterface                                  
  services_resetter                                                                              Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter                         
  session                                                                                        Symfony\Component\HttpFoundation\Session\Session                                          
  snc_redis.default                                                                              Predis\Client                                                                             
  templating                                                                                     alias for "templating.engine.delegating"                                                  
  templating.loader                                                                              alias for "templating.loader.filesystem"                                                  
  translator                                                                                     alias for "translator.data_collector"                                                     
  twig                                                                                           Twig\Environment                                                                          
  twig.controller.exception                                                                      Symfony\Bundle\TwigBundle\Controller\ExceptionController                                  
  twig.controller.preview_error                                                                  Symfony\Bundle\TwigBundle\Controller\PreviewErrorController                               
  validator                                                                                      alias for "debug.validator"                                                               
  var_dumper.cloner                                                                              Symfony\Component\VarDumper\Cloner\VarCloner                                              
  web_profiler.controller.exception                                                              Symfony\Bundle\WebProfilerBundle\Controller\ExceptionController                           
  web_profiler.controller.profiler                                                               Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController                            
  web_profiler.controller.router                                                                 Symfony\Bundle\WebProfilerBundle\Controller\RouterController

**Comment by imphil** [comment]
I had the same problem, resolved it (for now, at least) by manually removing the cache directory.

**Comment by pesseyjulien** [comment]
Yeah, it does work but the issue is when you have auto-scale with auto deploy, it can fail because of this, which is annoying !

**Comment by Jean85** [comment]
That should mean that you are using the cache in some wrong way...
Closing as resolved because it doesn't seem to be related to the bundle.
