### ISSUE TITLE
Documentation: Add configuration to config_prod.yml

### ISSUE THREAD

**Issue by imphil** [getsentry/sentry-symfony#152]
The [documentation suggests](https://github.com/getsentry/sentry-symfony/blob/master/README.md#step-2-enable-the-bundle) to not include the sentry bundle for test and dev environments. Then the docs go on and suggest to add the configuration to config.yml. This combination of steps does not work for the dev/test environment.

When deploying in dev, I get "There is no extension able to load the configuration for 'sentry' ...", since Symfony validates the configuration and requires the sentry bundle to be present when using the "sentry" config key.

The solution would be to document that config_prod.yml should be used (here: https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk)

**Comment by Jean85** [comment]
Right! Happy to accept a PR here!

**Comment by Jean85** [comment]
This is no longer valid in 3.0, since now we suggest to always include the bundle, and simply set the DSN to `null` to disable sending events.
