### ISSUE TITLE
Listening for kernel.request causes symfony debug error pages not to display

### ISSUE THREAD

**Issue by ethanhann** [getsentry/sentry-symfony#19]
When I enable the Sentry bundle I get the browser's default error page when an exception happens and not the Symfony dev environment error page. 

From what I can tell simply listening for the kernel.request event causes this issue...

https://github.com/getsentry/sentry-symfony/blob/master/src/Sentry/SentryBundle/Resources/config/services.yml#L20

I am using Symfony 2.7, if that is useful to you.

**Comment by dcramer** [comment]
Its very possible this is from our shutdown handler. We try to capture (literally) all the errors, and PHP has a few limitations in how we do that.

Can you try not setting the sentry.dsn value (or SENTRY_DSN ) in dev and see if that works?

**Comment by ethanhann** [comment]
Not setting the dsn did not resolve the issue. I ended up loading the bundle only in the prod environment in AppKernel, and moving the bundle config to my prod config files, to workaround the issue.

**Comment by Addvilz** [comment]
#21 could solve this via configuration (disabling Sentry in dev or test environments)
