### ISSUE TITLE
Suppressed errors will still bubbling up

### ISSUE THREAD

**Issue by f0086** [getsentry/sentry-symfony#20]
I have a lot of "file not found" errors in sentry because of this line in PhpFileCache.php from the Doctrine package:

```
 // note: error suppression is still faster than `file_exists`, `is_file` and `is_readable`
 $value = @include $fileName;
```

The @ will suppress the error, but sentry still log it. Is there a way to ignore these?

**Comment by dcramer** [comment]
@f0086 what version of sentry-php? We made some changes recently, though its possible you're just on an old version[1].

https://docs.sentry.io/hosted/clients/php/usage/#error-control-operators

**Comment by f0086** [comment]
I use the 0.4.0 version of the lib.

**Comment by dcramer** [comment]
It sounds like you're talking about sentry-symfony's version. The component that we care about here is sentry/sentry.

**Comment by f0086** [comment]
Ok, now I am a little confused.
This repo is named ```sentry-symfony```, on the README, it suggests this command: ```composer require sentry/sentry-symfony```. So I put the following line in my composer.json:

```
 "sentry/sentry-symfony": "^0.4.0"
```

So, whats that sentry/sentry component about?

**Comment by Addvilz** [comment]
`sentry/sentry` package is the generic PHP client. `sentry/sentry-symfony` is the bundle wrapper around it to integrate it with Symfony.

**Comment by dcramer** [comment]
Yeah so try bumping the child dependency up. We can require a higher version when we also bump the symfony package.

**Comment by f0086** [comment]
This does not solve my problem :(
I there anything else I can do?

**Comment by dcramer** [comment]
@f0086 you are using the latest sentry-php (1.1.0)? we explicitly have code which checks error_reporting just for this behavior. How do you have the handler configured? I'm going to close this as it should be resolved and we will jsut update the child dep here when a couple of other changes land.

**Comment by dcramer** [comment]
Could this be get sentry/sentry-php#348
