### ISSUE TITLE
Is there an easy way to declare multiple client ? i need more than just sentry.client service

### ISSUE THREAD

**Issue by Rebolon** [getsentry/sentry-symfony#205]
Reading the documentation, i can see that there is only one service 'sentry.client'
If we need to create more than one, is there something available in configuration, or should we declare it using services.yaml ?

thanks

**Comment by Jean85** [comment]
That is valid for 2.x. In the 3.x version, we will support the base SDK v2.0, which follows the [Unified API](https://docs.sentry.io/development/sdk-dev/unified-api/).

In that regard, you can bind different clients to different scopes; you can dig into [the base SDK repo](https://github.com/getsentry/sentry-php) and the relative [2.0 upgrade document](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md) to uncover how to do that, the bundle will just expose the settings to you in an easy manner.

If you want to try it out, there's already a [beta2](https://github.com/getsentry/sentry-symfony/releases/tag/3.0.0-beta2) release available.

**Comment by Jean85** [comment]
Closing this as stale.
