### ISSUE TITLE
Upgrading to 3 is missing info about options

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-symfony#207]
I'm trying to upgrade to latest beta version.
So, I changed re requirement in my composer from `^2.3` to `^3.0@beta` and ran `composer update`. Then I read the [doc](url).
Now I'm getting an error, since the key `skip_capture` under `options` is not supported anymore.
It looks like mentioned doc is missing that part.

**Comment by Jean85** [comment]
`skip_capture` has been abandoned, since the same feature has been implemented in the base SDK, with the native `excluded_exceptions` option. I'll update the upgrade doc accordingly, thanks for reporting it.

**Comment by mkopinsky** [comment]
A vanilla install of "sentry/sentry-symfony": "^3.0-beta2" by default put 
```
sentry:
    options:
        curl_method: async
```
in config/packages/sentry.yaml, which doesn't work with v2 of the PHP SDK.

**Comment by Jean85** [comment]
That's due to the flex recipe that is outdated. I have a pending PR there: https://github.com/symfony/recipes-contrib/pull/621

**Comment by mkopinsky** [comment]
OK great. I'm fairly new to symfony, so flex is still this foreign magical power in my mind.
