### ISSUE TITLE
<unlabeled event>

### ISSUE THREAD

**Issue by hjanuschka** [getsentry/sentry-symfony#219]
since we upgraded to sentry-symfony 3.0 series, we have like a gazillion of `<unlabeled events>` not sure how to debug this one.

pers. feeling, is that the "excluded_exceptions" somehow count as unlabeled?!

**Comment by hjanuschka** [comment]
https://github.com/getsentry/sentry-php/pull/822

**Comment by Jean85** [comment]
Duplicated of #216

**Comment by PapyDanone** [comment]
Just an FYI, `<unlabeled event>` is also what you get in Sentry when calling the `captureEvent` method of the Sentry client directly, with an empty `message` key in the payload.
