### ISSUE TITLE
Is this package deprecated?

### ISSUE THREAD

**Issue by raffomania** [getsentry/sentry-symfony#221]
The [sentry docs](https://docs.sentry.io/clients/php/integrations) say that this package is deprecated. This is mentioned nowhere in the README or this repository. I would like to add sentry to my symfony app without writing lots of symfony-specific integrations with the new sdk, but also don't want to use a deprecated package.

Will there be a new sentry-symfony package based on the new unified php sdk?

**Comment by Jean85** [comment]
No, this package is not deprecated. If you take a look to our readme, the new 3.0 version supports the new SDK with the Unified API.

Unfortunately my PR to the docs is still not merged: https://github.com/getsentry/sentry-docs/pull/810

**Comment by raffomania** [comment]
alright, thanks for the heads up.
