### ISSUE TITLE
Support for symfony 2.8

### ISSUE THREAD

**Issue by nocive** [getsentry/sentry-symfony#222]
Hi guys,

This is more of a question than an issue, so apologies if perhaps this is not the most appropriate place to raise it.

I managed to backport the 3.x version of the bundle for Symfony 2.8 without too much effort and was wondering if you would be interested in receiving a PR for that, so that possibly others could benefit from it as well?

You can check out the PR here: https://github.com/nocive/sentry-symfony/pull/1

**Comment by Jean85** [comment]
That version is not supported anymore, sorry. There's the 1.x version of the bundle if you need to work under Symfony 2.8, and there aren't so many differences between 1.x and 2.x to do it.

3.x is another story, but backporting support for 2.8 there is nearly impossible, since we are supporting Symfony 4 there; too many conflicting deprecations.

**Comment by nocive** [comment]
@Jean85 I know, we're using the new version in apps that we managed to upgrade, but I can imagine that there are a lot of people out there that are simply unable to upgrade their legacy applications for all sorts of different reasons. That's also our case.

I'm not proposing that you support 2.8, was just asking and proposing that maybe having a backported branch for others in the same situation wouldn't hurt.

We also don't wanna stick to the 1.x branch because we found out some nasty memory leaks and we want to use the new integration and SDK across all applications consistently.

**Comment by Jean85** [comment]
Oh, I misread your PR, sorry! I thought you were targeting the 2.x of this bundle, instead you're targeting 3.x, hence the new SDK.

That is surely some value. I'll look further into the PR.

**Comment by nocive** [comment]
You didn't misread it, I wrote 2.0.x version of the bundle but I meant the SDK :)
It was based from master, so yes, it's the 3.x version of the bundle, 2.x of the SDK.

**Comment by nocive** [comment]
https://github.com/getsentry/sentry-symfony/pull/223

**Comment by Jean85** [comment]
Solved with #223
