### ISSUE TITLE
Some tests?

### ISSUE THREAD

**Issue by Addvilz** [getsentry/sentry-symfony#23]
Should we have some tests in this bundle, to verify the functionality? :)

- PHPUnit
- PHPSpec

Could write some. Would certainly make me sleep better.

**Comment by dcramer** [comment]
I'd like to but not being symfony user it was unclear the best way to have any kind of reasonably accurate tests. 

We use phpunit in the core lib.

**Comment by Addvilz** [comment]
Okay, I could write some and send a PR, if you don't mind.

**Comment by dcramer** [comment]
Absolutely. It'd be extremely helpful!

**Comment by Addvilz** [comment]
@dcramer just one question, do you prefer to use PHPUnit, or you wouldn't mind PHPSpec either?
