### ISSUE TITLE
Client IP not properly logged before authentication is done when using a reverse-proxy

### ISSUE THREAD

**Issue by chdeliens** [getsentry/sentry-symfony#231]
Hi,

We are running into issues logging the correct user IP here.

We properly configured the "trusted proxies" of Symfony, so that when calling `$request->getClientIp()` at any time, we get the user IP (that is in our case contained in the `X-Forwarded-For` header since we are hosted behind a GCP Load Balancer) and not the forwarding-server's IP.

Sentry does log the correct user IP address only if an error occurs *after* the authentication has occurred.

I did some quick debugging to try and spot the issue, all I can say at this stage is that the correct IP is logged only when the request is a `MASTER_REQUEST`. 

For some reason, before the authentication occurs (we are using a provider to validate oauth2 bearer tokens), the request is a `SUB_REQUEST` and Sentry's `RequestListener` never processes it (I believe it's that specific listener that correctly pulls the IP address from the `$request`).

Expected behaviour: Sentry must always call `$request->getClientIp()` instead of relying on sometimes relying on `$_SERVER['REMOTE_ADDR']`.

Hopefully, it's not a silly configuration option on our end 😉 
Happy to discuss/debug this further with you guys!

**Comment by Jean85** [comment]
The piece of code that retrieves the IP address with `$request->getClientIp()` is here: https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/RequestListener.php#L77

If you look at the top of the function, that is a listener to the `kernel.request` event, and it's not executed on subrequest. The only case where that wouldn't work would be if you set the trustet proxies setting AFTER that that listener is executed.

Since the right place to set that is in your front controller, can you check that in your project?

**Comment by chdeliens** [comment]
The only case where that wouldn't work would be if you set the trustet proxies setting AFTER that that listener is executed.
> 
> Since the right place to set that is in your front controller, can you check that in your project?

We do set the trusted proxies in `public/index.php`, *before* the Kernel is booted, which is supposed to be the right place.

Some Sentry-logged issues *do* have the proper user IP address information, but they are very few.
Most of them carry the wrong information as the user IP address.

So far I can't seem to find a pattern to explain this behaviour.

**Comment by Jean85** [comment]
I would advise you to check all the `if`s above the linked line of code, one of those is maybe throwing off your listener. The other possibility is that you have something else that is overriding those values.

**Comment by B-Galati** [comment]
Could it be the `RequestIntegration` that overrides it?

**Comment by Jean85** [comment]
`RequestIntegration` doesn't override, it sets the IP only if it's empty: https://github.com/getsentry/sentry-php/blob/646f6ada8b89a08063e31f54ed6d260bd6879239/src/Integration/RequestIntegration.php#L129-L131

**Comment by Jean85** [comment]
Closing as not reproducible and stale. Feel free to reply if new informations arise.

**Comment by chdeliens** [comment]
It's now no longer happening. I can only see public IPs being logged in Sentry, no more internal LB IPs. I guess that some dependencies update fixed the issue!

Case closed indeed! Thanks!
