### ISSUE TITLE
Allow to disable ErrorListener completely 

### ISSUE THREAD

**Issue by B-Galati** [getsentry/sentry-symfony#232]
Hello,

In the setup there is an optional step with monolog setup. But having both Monolog and the `ErrorListener` would produce duplicates in Sentry server no?

So IMHO it would be great to add option to disable the `ErrorListener` and rely entirely on Monolog to report errors to Sentry if one is willing to do so.

WDYT?

**Comment by Jean85** [comment]
Wouldn't make more sense to not use this bundle entirely in that case, and just require the base Sentry SDK to work with Monolog?

**Comment by B-Galati** [comment]
> Wouldn't make more sense to not use this bundle entirely in that case, and just require the base Sentry SDK to work with Monolog?

Sure it's possible but it's simpler to use this bundle that configures everything for us with the extra data provided by the listeners.

Also, Monolog config is documented in the README (as optional) so it looks to be a valid use case for the bundle.

**Comment by Jean85** [comment]
The config would live in a completely different instance of the Hub/Client, wouldn't it? IHMO it doesn't interoperate well..

**Comment by B-Galati** [comment]
@Jean85 Yeap the goal is to use the service `Sentry\State\HubInterface` created by the bundle in monolog config + take advantage of the setup of the bundle (pre-configured paths, data, tags etc.).

**Comment by Jean85** [comment]
I'm gradually changing my mind. #247 seems to tackle well this issue, and I would like to add a breadcrumb Monolog handler in the future.

**Comment by B-Galati** [comment]
Let me know if you need anything!
