### ISSUE TITLE
Deprecation warnings in Symfony 4.4

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-symfony#235]
>Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" will return "\Symfony\Component\Config\Definition\Builder\TreeBuilder" as of its next major version. Doing the same in child class "Sentry\SentryBundle\DependencyInjection\Configuration" will be required when upgrading.

Since this repo is already requiring php>7.1, it should be easy to avoid such warning (adding a return type should be enough).
I can provide a PR

**Comment by Jean85** [comment]
Fix seems to be fine, PR is appreciated.
