### ISSUE TITLE
Help with class_serializers

### ISSUE THREAD

**Issue by perlamutr** [getsentry/sentry-symfony#236]
Hello, brothers and sisters!

How can I use my custom ClassSerializers? Using option class_serializers gives an error `Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "class_serializers" under "sentry.options" in /home/ifunny/api/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 307

`
What should I do to inject my serializers?

Thank you!

**Comment by Jean85** [comment]
`class_serializers` is a new option added in the base SDK in version 2.1.

We should add that option, but it would require bumping `sentry/sentry` to `^2.1`! A PR is welcome!
