### ISSUE TITLE
Incorrect wiring of services resulting in no events being captured

### ISSUE THREAD

**Issue by teohhanhui** [getsentry/sentry-symfony#242]
I have noticed that no events are being captured, so I augmented the Sentry code with some `var_dump` calls, and here is the result:

```
string(63) "Sentry\State\Hub::__construct ==> array (
  'client' => NULL,
)"
string(101) "Sentry\State\Hub::getCurrent ==> array (
  'hub' => 'Sentry\\State\\Hub (314)',
  'client' => NULL,
)"
string(107) "Sentry\State\Hub::captureException ==> array (
  'hub' => 'Sentry\\State\\Hub (314)',
  'client' => NULL,
)"
string(81) "Sentry\State\Hub::__construct ==> array (
  'client' => 'Sentry\\Client (610)',
)"
string(119) "Sentry\State\Hub::setCurrent ==> array (
  'hub' => 'Sentry\\State\\Hub (579)',
  'client' => 'Sentry\\Client (610)',
)"
string(119) "Sentry\State\Hub::getCurrent ==> array (
  'hub' => 'Sentry\\State\\Hub (579)',
  'client' => 'Sentry\\Client (610)',
)"
string(119) "Sentry\State\Hub::getCurrent ==> array (
  'hub' => 'Sentry\\State\\Hub (579)',
  'client' => 'Sentry\\Client (610)',
)"
```

As you can see, when `Hub::captureException` is called, the client is still `null`. :disappointed:

I suspect this is because the service with id `Sentry\State\HubInterface` has a method call `setCurrent` which injects a self-reference.

**Comment by teohhanhui** [comment]
Probably related to https://github.com/getsentry/sentry-php/pull/847

**Comment by teohhanhui** [comment]
I think the problem is that `ErrorListener` calls `\Sentry\captureException`, which uses the static `Hub::getCurrent`. This means the `Sentry\State\HubInterface` might not have been instantiated yet.

**Comment by Jean85** [comment]
The Hub is injected in the `RequestListener`, so your case was that you were getting an error even before that `kernel.request` was dispatched?

Wouldn't declare that service as public solve that issue alltogether? Can you test it out?

**Comment by teohhanhui** [comment]
Sorry, I don't follow. Injecting the Hub into `ErrorListener` fixes the issue. It's the same thing that's already being done for `RequestListener`, and there's no other change necessary.

**Comment by teohhanhui** [comment]
Please see the `var_dump` output I've included above to understand the order of events / what's going on.

**Comment by Jean85** [comment]
That's exactly my reasoning: it seems that the `ErrorListener` is instantiated and used even before the instantiation of the `RequestListener`. I was thinking that making the `Hub` service public would've triggered the instantiation immediately; BTW it isn't a straightforward approach,so yours is probably preferable.
