### ISSUE TITLE
How to configure ClientBuilder etc with custom serializer?

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry-symfony#251]
Hello, i have been struggling about how to set custom serializer and pass it to `ClientBuilderInterface::setSerializer()`.

This is final solution i was able to get working, but i am unsure if it is correct and there is no easier way?

Either i think in config i should use `Sentry\ClientBuilderInterface` instead of `Sentry\ClientBuilder` but since it is private service (defined in services.xml) and when i tried to exchange that i received `Error: Cannot instantiate interface Sentry\ClientBuilderInterface`

```yaml
services:
    Entrydo\Sentry\GenericSentrySerializer: ~
    Entrydo\Sentry\SentryClientBuilderSerializerConfigurator: ~
    Sentry\ClientBuilder:
        configurator: ['@Entrydo\Sentry\SentryClientBuilderSerializerConfigurator', 'configureSerializer']
```
```php
final class SentryClientBuilderSerializerConfigurator
{
    /**
     * @var GenericSentrySerializer
     */
    private $genericSentrySerializer;

    public function __construct(GenericSentrySerializer $genericSentrySerializer)
    {
        $this->genericSentrySerializer = $genericSentrySerializer;
    }


    public function configureSerializer(ClientBuilderInterface $clientBuilder): void
    {
        $clientBuilder->setSerializer(
            $this->genericSentrySerializer
        );

        ClientBuilderConfigurator::configure($clientBuilder);
    }
}
```
```php
final class GenericSentrySerializer implements SerializerInterface
{
    /**
     * @var Serializer
     */
    private $originalSerializer;

    public function __construct(Options $options)
    {
        $this->originalSerializer = new Serializer($options);
    }


    /**
     * Serialize an object (recursively) into something safe to be sent in an Event.
     *
     * @param mixed $value
     *
     * @return string|bool|float|int|object|array|null
     */
    public function serialize($value)
    {
        // and other logic

        if ($value instanceof UuidInterface) {
                return [
                    'uuid' => $value->toString(),
                ];
            }

        return $this->originalSerializer->serialize($value);
    }
}
```

**Comment by JanMikes** [comment]
If this is the right way of extending ClientBuilder, can we document it? I have spent some time figuring out that the only way (IS IT or am i wrong?) of doing that is using a symfony service configurator + decorating with calling the original configurator which i found in `SentryExtension`

**Comment by Jean85** [comment]
That's one way to do it, but you could've just added a `setSerializer` call to the builder service, Symfony would've done that for you without the need for an additional class.

**Comment by JanMikes** [comment]
@Jean85 thank you for your reply, though i did not figure out how to do that directly on existing service with id `Sentry\ClientBuilderInterface`.

**Comment by Jean85** [comment]
https://symfony.com/doc/current/service_container/calls.html

**Comment by JanMikes** [comment]
> https://symfony.com/doc/current/service_container/calls.html

Meh, i knew u must have missed something stupid and easy :-). Thank you! 

Can we please keep this open for few days? I would prepare PR with updating docs mentioning this as i think it might save some time for other devs looking for same thing.

**Comment by JanMikes** [comment]
I have tried suggested approach with calls and it still fails (i think it is because service is ClientInterface private) with message `Error: Cannot instantiate interface Sentry\ClientBuilderInterface`

My services.yaml looks like this:
```yaml
Entrydo\Sentry\GenericSentrySerializer: ~
    Sentry\ClientBuilderInterface:
        calls:
            - method: setSerializer
              arguments:
                  - '@Entrydo\Sentry\GenericSentrySerializer'
```

**Comment by Jean85** [comment]
Nope, the issue here is that with YAML you're completely overriding the bundle configuration, so the `class` key missing, and the service doesn't know how to instantiate the class. So you either add the call with PHP (like with a compiler pass) or you have to copy what' you're overriding.

**Comment by JanMikes** [comment]
Ah, damn, i see 😄 

What do you think about extending sentry/symfony extension to make this easier, something like this (i would prepare PR):

Sentry yaml:
```yaml
sentry:
    dsn: '%env(SENTRY_DSN)%'
    client:
        serializer: '@MyService' # new option
    options:
        environment: '%kernel.environment%'
```

`SentryExtension::load()`:
```diff
- $container->getDefinition(ClientBuilderInterface::class)
-    ->setConfigurator([ClientBuilderConfigurator::class, 'configure']);

+ $clientBuilder = $container->getDefinition(ClientBuilderInterface::class);
+ $clientBuilder->setConfigurator([ClientBuilderConfigurator::class, 'configure']);
        
+ if ($processedConfiguration['client']['serializer']) {
+    $clientBuilder->addMethodCall('setSerializer', /** .. */);
+ }
```

**Comment by Jean85** [comment]
I would have to maintain a lot of different stuff for that, since that is not the only option that could be configured in that way, and not the only way.
