### ISSUE TITLE
syntax error, unexpected '}', expecting ';' is not send to sentry in dev mode

### ISSUE THREAD

**Issue by alihasana** [getsentry/sentry-symfony#258]
Hi team,

i am not getting alert for syntax error, unexpected '}', expecting ';' in dev mode.
Even i try with all error_ types

Could you please advice on this.

Thanks

**Comment by Jean85** [comment]
By default, the DSN may not be set in dev environment, you should check on that.

Apart from this, it's possible that the framework is crashing hard before starting, so you are unable to have reports from that event.

**Comment by alihasana** [comment]
I got other error, DSN are there.

Le jeu. 10 oct. 2019 à 17:54, Alessandro Lai <notifications@github.com> a
écrit :
