### ISSUE TITLE
Sentry does not send events to server in messenger context

### ISSUE THREAD

**Issue by bjalt** [getsentry/sentry-symfony#259]
The sentry/sentry/src/Transport/HttpTransport.php:81 will not send events while running in a worker process. Switching the statement to ``$promise = $this->httpClient->sendRequest($request);`` will work. 
One can also observer how the ``$this->pendingRequests[]`` is holding all the pending request. But non is getting send to the sentry server for display in the sentry frontend.

Can You please advice how to continue?

**Comment by bjalt** [comment]
Found there is already an issue open about this: https://github.com/getsentry/sentry-php/issues/811

**Comment by dpinheiro** [comment]
Although the referenced issue has been closed still I can't get the messenger errors to show up on sentry. Any update to this?

**Comment by Jean85** [comment]
https://github.com/getsentry/sentry-php/pull/813 was released with the 2.1.2 client. You could try to call `flush()` when the messenger dispatches some event that marks the end of a single message?

If that fixes it, I could accept a PR implementing the same, like an additional listener.


Also: do you receive any message if the worker shuts down? Like, if you set it up to shut down every N messages?

**Comment by dpinheiro** [comment]
Sorry for the late reply. Not sure about you mean about the `flush()`, at least I'm not aware (except the doctrine one)

I just tried to set messenger to shutdown after X seconds but no messages sent, I will try to debug the problem

**Comment by Jean85** [comment]
Ok. If no message is being sent at all, it may be that you have something else broken. I would suggest you to use the `sentry:test` command to see if sending a simple event from CLI works at all.

Feel free to open a different issue if you need it.

**Comment by emarref** [comment]
I have found that subscribing to the `WorkerMessageFailedEvent` event is a good way to do it. E.g. https://gist.github.com/emarref/d8f7c2e071e334b39a5042b06927f881

Is it worth creating a pull request adding this subscriber if the application is using Messenger?

**Comment by Jean85** [comment]
Yes it is!
