### ISSUE TITLE
Improve docs about send_default_pii

### ISSUE THREAD

**Issue by Pheetbag** [getsentry/sentry-symfony#262]
When i first install the bundle and tried to send my users with the events. I wasted at least half a day trying to figure out why the bundle didnt send those. 

I know the information about send_default_pii is in the SDK docs on the sentry website, but it is hidden in bunch of other configs and is not even bring up in the docs for this bundle (even when that config only affect this kind of libraries on top of the SDK), so i think its appropriate to add a little side note in the README.md talking about how this config will make the bundle change its behavior. 

I want your feedback about this addition and i'll make a PR adding it if you agree.

**Comment by Jean85** [comment]
This is already documented in #220; since it's not an option specific to the bundle, I would say that having that documented would be a duplication...

**Comment by Pheetbag** [comment]
i see, well having it in the UPGRADE.md file i'm sure is extremely useful for the migrations usecase, but not so much for newcomers that land directly in the 3.0 branch, but i also get the duplication issue... Maybe there is something that can be improved  in somewhere to make the DX better? i would be glad to help do something about.

i first put this here because i thought this setting did'nt have an impact in the core php sdk, but instead was intended for this kind of wrappers around it, now i see i got it wrong. No i believe this is not a problem for the SDK usecase because users expect to do their own implementation and not the library doing it for them (at least i dont see it being stated anywhere, but in the send_default_apii option doc itself, so no problem about it, you know what it does and know that you have to enable it), i faced this problem here just because i read the information about the listeners (to create my own ones) and give them a quick read, of course i noticed what you where doing to the Scope (adding user information and ip address) i find myself debugging my application trying to figure out why that default behavior was not triggering. Maybe a comment in the `RequestListener.php` in the right place would help mitigate this problem? what you think?

**Comment by Jean85** [comment]
Maybe the best course of action would be linking directly to the documentation in the readme?

**Comment by Pheetbag** [comment]
I think that is already done, there is a reference to the unified API. Maybe just expecting the user to find out about this by reading the detailed docs is just enough?
