### ISSUE TITLE
HHVM tests failing when mocking exception class

### ISSUE THREAD

**Issue by Addvilz** [getsentry/sentry-symfony#27]
https://travis-ci.org/getsentry/sentry-symfony/jobs/157938242 fails in HHVM when getting mock of the internal exception. 

I'll see to this as soon as I get a minute or two.

**Comment by dcramer** [comment]
:+1: I fixed the other issues with older PHP

**Comment by Addvilz** [comment]
According to sebastianbergmann/phpunit-mock-objects#207 this can be fixed by either upgrading PHPUnit, or upgrading HHVM - none of which is probably a good option. Latest HHVM on Xenial seems to not have this issue anymore.

Instead of that I opted to use `\Exception` directly as there should not be any side-effects from that.
