### ISSUE TITLE
Add support for Symfony 5

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-symfony#272]
Symfony 5 is currently in beta and will be stable [in two weeks](https://symfony.com/releases).

**Comment by Jean85** [comment]
This is blocked by https://github.com/getsentry/sentry-php/issues/922

**Comment by pyatnitsev** [comment]
Symfony 5 has been released.

**Comment by Jean85** [comment]
This is going to be resolved by #266. We're currently blocked upstream though: https://github.com/getsentry/sentry-php/pull/925#pullrequestreview-321716954

**Comment by Vincz** [comment]
Hey guys! Sentry PHP 2.2.5 is released with the Symfony 5.0 compatibility :)

**Comment by Jean85** [comment]
Also blocked by #277 :disappointed: it's complete, it only needs a review.

**Comment by tacman** [comment]
This is such a useful bundle, any chance it could be reviewed and released/tagged for Symfony5?  Thanks!

**Comment by Vincz** [comment]
@Jean85 looks like it has been merged ! :)

**Comment by Jean85** [comment]
One last blocker, I promise :sweat_smile: we need #284, because right now the CI on #266 is blocking Composer from installing Symfony 5

**Comment by garak** [comment]
@Jean85 #284 is merged

**Comment by Vincz** [comment]
Hey @Jean85 ! Any idea when this will be merged? Thanks !

**Comment by Jean85** [comment]
Sorry, I had a couple of rough days. I'll check it now, I need to rework the CI matrix due to https://github.com/getsentry/sentry-symfony/pull/266#issuecomment-561098139

**Comment by Yozhef** [comment]
Hellow @Jean85 need add support all Symfony components to the new versions. 

I'm starting use Symfony 5 and have a problem:
```
 Problem 1
    - Installation request for sentry/sentry-symfony ^3.2 -> satisfiable by sentry/sentry-symfony[3.2.0].
    - sentry/sentry-symfony 3.2.0 requires symfony/config ^2.8||^3.0||^4.0 -> no matching package found.
```

I have `symfony/console` - but a version 5.0.1.

**Comment by Jean85** [comment]
@Yozhef #266 is now merged, you can try it out requiring `dev-master`. In the meantime, we have a few things to iron out (like #288) but I hope that it will not impact the final 3.3 release.

**Comment by Jean85** [comment]
All PR are merged. I hope to have a release ASAP.

**Comment by alsotop** [comment]
Do the composer.json requires for symfony components below not need to be updated?

```
"symfony/config": "^2.8||^3.0||^4.0",
"symfony/console": "^2.8||^3.0||^4.0",
"symfony/dependency-injection": "^2.8||^3.0||^4.0",
"symfony/event-dispatcher": "^2.8||^3.0||^4.0",
"symfony/http-kernel": "^2.8||^3.0||^4.0",
"symfony/security-core": "^2.8||^3.0||^4.0"
```

**Comment by kavalanche** [comment]
I think it should be updated. I have the same problem.

```
Problem 1
    - sentry/sentry-symfony 3.2.1 requires symfony/config ^2.8||^3.0||^4.0 -> no matching package found.
    - sentry/sentry-symfony 3.2.0 requires symfony/config ^2.8||^3.0||^4.0 -> no matching package found.
```

**Comment by pyatnitsev** [comment]
It's merged to master, but not released yet.

**Comment by sirian** [comment]
+1
When will be released?

**Comment by garak** [comment]
Notice that releases pages lists version `3.2.0` as including this feature, while it is not.
![Schermata da 2019-12-23 11-34-22](https://user-images.githubusercontent.com/179866/71353113-6b9d5e00-2578-11ea-9705-06e4a561c8f2.png)

**Comment by Jean85** [comment]
@garak that entry is related to #235, which is effectively released in that version.

**Comment by garak** [comment]
I guess that wording is a bit misleading, maybe "Remove deprecation" would have been better
