### ISSUE TITLE
Breadcrumbs not added

### ISSUE THREAD

**Issue by matthiashamacher** [getsentry/sentry-symfony#274]
Hello,

if added some Breadcrumbs to my application but they aren't shown inside the issues.
I've added them as it is described in the PHP example here: https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=php#recording-crumbs
I just debugged the whole process and saw, that the $this->breadcrumbs array in State/Scope.php is empty each time I add a breadcrumb. Currently I add the breadcrumbs on different pages witch where called after each other, so there is a page call between them. Is that the problem? Is it only possible to add breadcrumbs on one page?

Kind regards,
Matthias

**Comment by Jean85** [comment]
Yes, breadcrumbs persist only inside the same request, Sentry does not store information anywhere, so each new page restarts everything. As always, PHP is share-nothing.

**Comment by matthiashamacher** [comment]
Hey @Jean85 ,
thanks for the information.
Then I need to find an other way how I can achieve that. :D
