### ISSUE TITLE
Add user feedback

### ISSUE THREAD

**Issue by Arioch171** [getsentry/sentry-symfony#287]
This bundle could automatically inject the required scripts in error responses to show an error reporting form (see [User Feedback](https://docs.sentry.io/enriching-error-data/user-feedback/?platform=php)). Instead of overriding templates, an event subscriber could inject the Sentry widget in response data (eg. [WebDebugToolbarListener](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php)).

Would you be interested in this feature?

**Comment by Jean85** [comment]
It seems interesting on the surface, but I have some doubts:
 - this has to be opt-in
 - how would you link the necessary JS?
 - should we avoid Twig? it would create a soft-dependency that's harder to solve in CI
 - how can we test this feature?

**Comment by Arioch171** [comment]
@Jean85 
>     * this has to be opt-in
I agree, I would add an opt-in parameter.

>     * how would you link the necessary JS?
I was thinking of putting the necessary JS in a twig template. We need to generate two `<script>` tags: the base library + another for `Sentry.showReportDialog`. It would be easily overridden if necessary. We could also add a parameter to provide the JS library link (e.g. https://browser.sentry-cdn.com/5.7.0/bundle.min.js), and maybe another array parameter to pass to `showReportDialog`... 

>     * should we avoid Twig? it would create a soft-dependency that's harder to solve in CI
You're right, it would add a new dependency. Without a templating engine, I guess we would have to generate it in php...

>     * how can we test this feature?
The unit test would pass a Response object and expect it to contain the added script. We could also add an end-to-end WebTestCase: trigger a 404 error and expect the response to contain the script.

**Comment by Jean85** [comment]
Providing the JS like this is not in line with what Symfony suggests, which is using Webpack encore. I fear that this feature is too much borderline, with too much burden on us and not so much benefit for the end user, compared to what could be done. In reality, this should be simply added to the errors page, which are normally a separate Twig template already; at that point, the bundle shouldn't pop that script everywhere, it would be wrong, so the usefulness of doing this feature in this bundle is even thinner.

**Comment by erichard** [comment]
We are talking about including a JS in an exception template used for 5xx status code. 

I think this is acceptable to provide such a template with js files loaded via the sentry CDN. No need to use webpack encore for that.

It's a question of providing an out of the box but complete sentry integration. You are still free not to  use the template or use your own.

@Jean85 For the opt-in, do you mean opt-in for the visitor or for the developer ? I think it could be both by testing the DNT header presence for exemple.

**Comment by Jean85** [comment]
- Which CDN would you use? Would you ask the dev to input it?
 - How would you intercept the right responses in which inject it?

**Comment by Arioch171** [comment]
By default, I would use Sentry CDN like this one https://browser.sentry-cdn.com/5.7.0/bundle.min.js. The dev could change it with a parameter. If he wanted to use a local version, he could give a local url.

If the goal is injecting the script when a server error occurs (http code 5xx), intercepting the responses would be as simple as calling `isServerError()` on the response object. There would be other checks: content would have to be html... That's what Symfony does in https://github.com/symfony/symfony/blob/5.0/src/Symfony/Bundle/WebProfilerBundle/EventListener/WebDebugToolbarListener.php#L105

**Comment by Jean85** [comment]
I still see more issues that advantages. Let me explain:

> By default, I would use Sentry CDN like this one https://browser.sentry-cdn.com/5.7.0/bundle.min.js. The dev could change it with a parameter. If he wanted to use a local version, he could give a local url.

This would mean hardcoding the URL in the bundle, which is bad, since the URL may change over time. As you can see, it even embeds the version right now.

A local URL is not feasible from a YAML / XML config, because if you use Encore, you would need the Encore bundle to step in and generate the right URL dynamically. And doing with PHP would mean soft-requiring said bundle (and Twig) and wiring it through.
