### ISSUE TITLE
POST data not recorded

### ISSUE THREAD

**Issue by rdohms** [getsentry/sentry-symfony#29]
In our tests we have noticed that the POST data is not sent along for reproducing bugs.

Is there a way to gather more data and send it along by default, or is it a matter of extending the bundle classes and rolling out your own?

**Comment by dcramer** [comment]
@rdohms we should be capturing POST data automatically:

https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Client.php#L553

Granted if its not form data we probably aren't catching it.
