### ISSUE TITLE
Tag 3.3.0 was moved from 620b90d to 6e448db, resulting in broken downstream installs

### ISSUE THREAD

**Issue by Ocramius** [getsentry/sentry-symfony#297]
Release 3.3.0 (620b90d) was moved to commit 6e448db (re-tag).

Please don't do that, as it breaks downstream consumers. In my case, my `composer.lock` points at 620b90dc35c12ef96c6460df74e30441e359ce6d, and won't update to 6e448db anymore (local version takes precedence).

In addition to that, packagist still points to 620b90d, and a forced version delete+update would be needed there.

In practice, what should be done:

 * revert `3.3.0` to point to 620b90d
 * tag `3.4.0` pointing to 6e448db
 * never ever delete stable tags

**Comment by Jean85** [comment]
Sorry for the confusion, @HazAT proceeded as fast as possible to clean this up; something broke in the automation that are in place for releases, so we had to proceed by hand.

The tag is fixed on Packagist too, so the only way to have a broken setup is to have the previous tag installed. For anyone needing to fix that case:
 * delete the `vendor/sentry/sentry-symfony` folder
 * call `composer update sentry/sentry-symfony` again to fetch the correct commit.

**Comment by Ocramius** [comment]
Alright, forced a local update, just please don't re-tag again: it's better to release a new one instead :|

**Comment by HazAT** [comment]
Sorry about that, `3.3.1` has been released, this should fix the issue.
