### ISSUE TITLE
Class 'Sentry' not found

### ISSUE THREAD

**Issue by sylouuu** [getsentry/sentry-symfony#3]
Hello,

Just followed the readme with `composer require sentry/sentry` before.

The bundle line is underlined in PhpStorm because it doesn't know where to find `new Sentry/SentryBundle/SentryBundle()`.

Is there something missing? Autoloader?

Bests

**Comment by ruudk** [comment]
It shouldn't be / but \

**Comment by ruudk** [comment]
Fixed in https://github.com/getsentry/sentry-symfony/pull/4

**Comment by sylouuu** [comment]
Indeed thx.
