### ISSUE TITLE
After Update: Uncaught Error: Call to undefined method 

### ISSUE THREAD

**Issue by OnDreBug** [getsentry/sentry-symfony#300]
After Update from 3.2.1 => 3.3.1

PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\HttpKernel\Event\ExceptionEvent::getThrowable() in ...vendor/sentry/sentry-symfony/src/EventListener/ErrorListener.php:26

**Comment by adrienfr** [comment]
Same here, `getException` is deprecated since SF 4.4 and removed in 5.0 but still exists in 4.3 and lower. `getThrowable` only exists on SF 4.4+

**Comment by adrienfr** [comment]
I thinks this comes from [here](https://github.com/getsentry/sentry-symfony/pull/277/files#diff-3557e77ca9efe3cb02d8ba3030de4711R27), where `getThrowable()` should be `getException()` for versions with SF < 4.4

**Comment by Jean85** [comment]
This seems correct. I need to adjust when to switch from one listener to the other.

**Comment by adrienfr** [comment]
Thank you @Jean85 !
