### ISSUE TITLE
how to get the release number from database

### ISSUE THREAD

**Issue by asuri0n** [getsentry/sentry-symfony#305]
Hello,
The Release number of my app is stored in the database, is there a way to pass this value to the sentry conf ?

thanks

**Comment by Jean85** [comment]
The fact that the release is in the DB sound pretty strange to me: it should be the version of the code that is active on the server in that moment, so it's normally the tag or the commit hash of the source code. In the last release (3.4.0) the release field is even automatically populated like that thanks to #294. 

In any case, the release is a property of the `Options` class, so you just need to reach the Options in the container (the service is called with the class name): https://github.com/getsentry/sentry-symfony/blob/1d120b268725bd22f04bac230a3b216844bc0131/src/Resources/config/services.xml#L8

...and call `Options::setRelease` upon it.
