### ISSUE TITLE
RequestListener::onKernelRequest() type error

### ISSUE THREAD

**Issue by Nadrshin** [getsentry/sentry-symfony#306]
php 7.4.1
symfony 3.4.31

After upgrading `sentry/sentry-symfony` from 3.2.1 to 3.4.0  following error appeared:

```
Type error: Argument 1 passed to Sentry\SentryBundle\EventListener\RequestListener::onKernelRequest() must be an instance of Symfony\Component\HttpKernel\Event\RequestEvent, instance of Symfony\Component\HttpKernel\Event\GetResponseEvent given, called in /home/crash/projects/dict/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php on line 115
```

But error appeares only one time after auto container recompilation in dev environment. If I refresh page in browser after error appears, there will be no more error.

**Comment by Jean85** [comment]
It's possible that you had stale Symfony cache. Does the error return if you trigger an error that Sentry captures?

**Comment by Nadrshin** [comment]
> It's possible that you had stale Symfony cache.

Yes, cache is stale. And it should be updated automatically in dev environment. (After updating the parameter value, for example.)

>  Does the error return if you trigger an error that Sentry captures?

No, all is well.

And there is no error if I clear cache with `bin/console cache:clear` command.

**Comment by Jean85** [comment]
I don't understand what's the issue here then.
