### ISSUE TITLE
Store the User Context only when a exception is thrown

### ISSUE THREAD

**Issue by franmomu** [getsentry/sentry-symfony#317]
I was checking in my project which services were accessing the session (it changes the response to private) and I found out that the [RequestListener](https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/RequestListener.php) is accessing it [using tokenStorage](https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/RequestListener.php#L68). What about only storing the user data when the exception is thrown?

**Comment by Jean85** [comment]
1) What do you mean with
> it changes the response to private

2) It would make the process a lot more complex and unreliable, since it would have to do that when handling an error, possibly a fatal error, situation where it could possibly fail again and create a worst scenario...

**Comment by franmomu** [comment]
Sorry I should have explained better. [In Symfony](https://symfony.com/doc/4.4/http_cache.html#http-caching-and-user-sessions):

> Whenever the session is started during a request, Symfony turns the response into a private non- cacheable response. This is the best default behavior to not cache private user information (e.g. a shopping cart, a user profile details, etc.) and expose it to other visitors.

So when the listener is executing `$token = $this->tokenStorage->getToken();` starts the session and makes the response non-cacheable.

> 2. It would make the process a lot more complex and unreliable, since it would have to do that when handling an error, possibly a fatal error, situation where it could possibly fail again and create a worst scenario...

I meant maybe instead of listen to `onKernelRequest`, listen to `onException` and have more priority than the ErrorListener. I still have to fix some code of my own in the project, when I finish I could give it a try at this if it's ok.

**Comment by Jean85** [comment]
I understand your request now, thank you.

> I meant maybe instead of listen to `onKernelRequest`, listen to `onException` and have more priority than the ErrorListener. I still have to fix some code of my own in the project, when I finish I could give it a try at this if it's ok.

That is something that you could do on your own by changing the default behavior of the bundle, but I cannot implement it as a default because I fear it would not work in case of a fatal error.

**Comment by franmomu** [comment]
> I understand your request now, thank you.
> 
> > I meant maybe instead of listen to `onKernelRequest`, listen to `onException` and have more priority than the ErrorListener. I still have to fix some code of my own in the project, when I finish I could give it a try at this if it's ok.
> 
> That is something that you could do on your own by changing the default behavior of the bundle, but I cannot implement it as a default because I fear it would not work in case of a fatal error.
> 
> [EDIT] Also, it would change the behavior, because it would also not have the user information if you can `captureMessage` on your own, for example.

Ok! Makes sense, thank you, I'll try to change it in the project.

**Comment by franmomu** [comment]
Just in case someone might find it useful, I ended up decorating the listener:

```yaml
App\Sentry\RequestListener:
    decorates: Sentry\SentryBundle\EventListener\RequestListener
    arguments: ['@App\Sentry\RequestListener.inner']
```

```php
<?php

declare(strict_types=1);

namespace App\Sentry;

use Sentry\SentryBundle\EventListener\RequestListener as InnerRequestListener;
use Symfony\Component\HttpKernel\Event\ControllerEvent;
use Symfony\Component\HttpKernel\Event\RequestEvent;

final class RequestListener
{
    private $requestListener;

    public function __construct(InnerRequestListener $requestListener) 
    {
        $this->requestListener = $requestListener;
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        if (! $event->isMasterRequest()) {
            return;
        }

        if (! $event->getRequest()->hasPreviousSession()){
            return;
        }

        $this->requestListener->onKernelRequest($event);
    }

    public function onKernelController(ControllerEvent $event): void
    {
        $this->requestListener->onKernelController($event);
    }

}
```
