### ISSUE TITLE
Filtering out cookies from context sent to Sentry

### ISSUE THREAD

**Issue by tarjei** [getsentry/sentry-symfony#341]
Hi, how do I filter out cookies I do not want to be stored to sentry when using this bundle?

**Comment by Jean85** [comment]
This bundle does not add anything on top of the [base PHP SDK](https://github.com/getsentry/sentry-php), so you can refer to the [general docs](https://docs.sentry.io/platforms/php/).

In general, cookies are bound to the `send_default_pii` option, so if that's turned off (and it is by default), no cookie is attached to the event. If you prefer to have cookies but omit part of them, you probably will have to work in the `before_send` callback, or add a global event processor.
