### ISSUE TITLE
Composer require with Symfony Flex fails.

### ISSUE THREAD

**Issue by jvanschie** [getsentry/sentry-symfony#342]
Hi,

I am using Symfony 5 and I am unable to install this package using Symfony Flex.
Do you have an idea why I am getting below error message?

composer require sentry/sentry-symfony

Restricting packages listed in "symfony/symfony" to "5.0.*"
Using version ^3.5 for sentry/sentry-symfony
./composer.json has been updated
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.0.*"
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony/polyfill-uuid could not be found in any version, there may be a typo in the package name.
  Problem 2
    - sentry/sentry 2.3.2 requires symfony/polyfill-uuid ^1.13.1 -> no matching package found.
    - sentry/sentry 2.3.0 requires symfony/polyfill-uuid ^1.13.1 -> no matching package found.
    - sentry/sentry 2.3.1 requires symfony/polyfill-uuid ^1.13.1 -> no matching package found.
    - sentry/sentry-symfony 3.5.0 requires sentry/sdk ^2.1 -> satisfiable by sentry/sdk[2.1.0].
    - sentry/sdk 2.1.0 requires sentry/sentry ^2.3 -> satisfiable by sentry/sentry[2.3.1, 2.3.0, 2.3.2].
    - Installation request for sentry/sentry-symfony ^3.5 -> satisfiable by sentry/sentry-symfony[3.5.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by Jean85** [comment]
`symfony/polyfill-uuid` 1.13.1 does actually exist: https://packagist.org/packages/symfony/polyfill-uuid#v1.13.1

It seems a local problem in your environment. Try updating Composer if you're not using the latest patch (1.10.6 as of now).

**Comment by jvanschie** [comment]
I've already tried to update composer.
Still having the same issue.

composer -V
Composer version 1.10.6 2020-05-06 10:28:10

**Comment by Jean85** [comment]
Try `composer clear-cache` or `composer why-not symfony/polyfill-uuid:^1.13.1`

**Comment by jvanschie** [comment]
clear-cache didn't make a difference.

why-not:

```
composer why-not symfony/polyfill-uuid:^1.13.
                                                                  
  [InvalidArgumentException]                                      
  Could not find package "symfony/polyfill-uuid" in your project  
                                                                  
prohibits [-r|--recursive] [-t|--tree] [--] <package> [<constraint>]
```

**Comment by Jean85** [comment]
You should report this to Composer, with your `composer.json` too.

**Comment by jvanschie** [comment]
@Jean85 yes I did, thanks for your help. I will close this ticket.
