### ISSUE TITLE
Timestamp not getting processed

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-symfony#35]
Right now I'm getting this strange behavior in our Sentry setup:

> There was 1 error encountered while processing this event
> Discarded invalid value for parameter 'timestamp'
> ```
> {
>   "name": "timestamp",
>   "value": "2016-11-24T09:15:35Z"
> }
> ```

**Comment by dcramer** [comment]
@Jean85 is it possible your local timestamps are way off?

**Comment by Jean85** [comment]
Yeah it seems to be the case. So it's getting blocked by Sentry?

**Comment by dcramer** [comment]
@Jean85 we throw it away in certain cases, such as if its in the future
