### ISSUE TITLE
Capture command arguments

### ISSUE THREAD

**Issue by ostrolucky** [getsentry/sentry-symfony#351]
CLI Commands are usually run with certain arguments. Error is also most of the time being triggered with certain CLI arguments only, this is why it's important to have it. Would you welcome contribution to log not only command name, but command arguments in your ConsoleListener?

**Comment by stayallive** [comment]
I'd be +1 for this since it's useful context, for example in Laravel we add the full input as context (looks like [this](https://d.bouma.dev/OTd7FXTAUB6r)) and also the exit code.

Code context (`artisan` being the name of Laravel CLI tool):

> https://github.com/getsentry/sentry-laravel/blob/2dfcf9e0bd83856ee7abba25bb3ade8960081430/src/Sentry/Laravel/EventHandler.php#L472-L480
> https://github.com/getsentry/sentry-laravel/blob/2dfcf9e0bd83856ee7abba25bb3ade8960081430/src/Sentry/Laravel/EventHandler.php#L492-L502

**Comment by Jean85** [comment]
This was requested in the past, see https://github.com/getsentry/sentry-symfony/issues/60#issuecomment-305269876.

It must not be the default behavior, to avoid exposing sensitive information.

**Comment by ostrolucky** [comment]
Isn't this a problem already in stack traces in general? Sentry should have a generic way how to combat exposing sensitive information.

**Comment by stayallive** [comment]
Yes, this value should already be sanitised. I believe both client and server side.

In Laravel we made a configuration option to disable these kind of "auto-breadcrumbs" (per type) and that could maybe be an option, but we do have it enabled by default there.

**Comment by Jean85** [comment]
I would consider enabling it by default only in a major version bump, which is coming by the way thanks to #337.

Maybe we can add the feature off by default in 3.x and switch it to on by default in 4?

**Comment by ostrolucky** [comment]
I would rather not add more toggles. So if adding it in major version is your only concern, let's just merge it to 4.

**Comment by michondr** [comment]
some time has passed, and I'm curious if this is available at the moment? I'd like to know how to reprocess these failed messages

![image](https://user-images.githubusercontent.com/29277166/108561778-15a08380-72ff-11eb-8249-62856cec5d1b.png)

**Comment by ostrolucky** [comment]
There is https://github.com/getsentry/sentry-symfony/pull/352, but for some unknown reason, this wasn't merged for 4.0.

**Comment by Jean85** [comment]
Sorry, we missed the PR while refactoring toward 4.0. I'm happy to re-review it once it's rebased and the comments are addressed.

**Comment by ostrolucky** [comment]
Rebased and comments addressed

**Comment by michondr** [comment]
> Rebased and comments addressed

any info where to find snippets of how to tweak it? or how to use it? how it works?

**Comment by Jean85** [comment]
@michondr it's all in the linked PR: #352

**Comment by Jean85** [comment]
Closing as #352 got merged.
