### ISSUE TITLE
Doc improvement: How to use the client as service with Dependency Injection and autowiring. 

### ISSUE THREAD

**Issue by versedi** [getsentry/sentry-symfony#362]
The previous major version allowed to get a service from container aliased as: `@sentry.client` 

This alias doesn't exist anymore in version `3.5.2`

```
 bin/console debug:container sentry.client
                                                 
No services found that match "sentry.client".  

```

1. Please provide an example in the documentation available at: https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-3.0.md how to properly inject Sentry Client with Dependency Injection and autowiring on/off.
2. Please provide an information that the alias isn't available anymore and all references to it has to be changed in X way. 

Best Regards,
v.

**Comment by Jean85** [comment]
Since this is documentation, this is the best way to start participating in Open Source.

Feel free to open a PR with the desired changes; your perspective as a user who bumped on those issues is probably the best fit to write that down.

**Comment by Jean85** [comment]
BTW, the doc already reports this:
> All services uses the full qualified name of their interfaces to name them

> * `Sentry\State\HubInterface`: this is the central root of the SDK; it's the Hub that the bundle will instantiate at startup, and the current one too if you do not change it
> * `Sentry\ClientInterface`: this is the proper client; compared to the 1.x SDK version it's a lot more slimmed down, since a lot of the stuff has been split in separated components, so you probably will not interact with it as much as in the past. You also have to remind you that the client is bound to the Hub, and has to be changed there if you want to use a different one automatically in error reporting

**Comment by versedi** [comment]
If you map Sentry\ClientInterface to Sentry\Client you will get into a dependency chain.

You will need to map TransportInterface to whatever you want but then you will get stuck at mapping EventFactoryInterface to EventFactory which requires following parameters in constructor:

```
/**
     * EventFactory constructor.
     *
     * @param SerializerInterface               $serializer               The serializer
     * @param RepresentationSerializerInterface $representationSerializer The serializer for function arguments
     * @param Options                           $options                  The SDK configuration options
     * @param string                            $sdkIdentifier            The Sentry SDK identifier
     * @param string                            $sdkVersion               The Sentry SDK version
     */
```

First three are autowired - no hassle.

What are we supposed to pass as `sdkIdentifier` and `sdkVersion` and from where?

**Comment by Jean85** [comment]
The client in `sentry/sentry` 2.0 (which is used in 3.0 of this bundle) is no longer the "god class", but only the HTTP sender of events.

The end user should interact with the Hub (`HubInterface`) to start with.

**Comment by ste93cry** [comment]
I'm going to close this issue because as said by @Jean85 the entry point to use the new PHP SDK (be it `2.x` or `3.x`) is to either use the global functions or use the hub. Using the client like in `1.x` is still possible, but you will lose some features that needs the scope to work (e.g. the event processors) and whose instance is hold by the hub and so it's highly discouraged unless you know what you are doing. The recommended way to use this bundle and the dependency injection pattern is to inject the `Sentry\State\HubInterface` service (which should be autowired) and use the methods on it
