### ISSUE TITLE
Add a way to ignore exception thrown by Symfony Messenger if there is a retry.

### ISSUE THREAD

**Issue by VincentLanglet** [getsentry/sentry-symfony#363]
Let's say I use Symfony Messenger with the following config:
```
framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 5000
            failed: 'doctrine://default?queue_name=failed'
```

The following scenarios can occur: 
1. First try: success
2. First try: failure ; Second try: success
3. First try: failure ; Second try: failure ; Third try: success
4. First try: failure ; Second try: failure ; Third try: failure

Currently, case 2, 3 and 4 are sending error messages on Sentry.
Is there a way to only get error message on Sentry for case 4 ?

**Comment by Jean85** [comment]
This was already implemented in the original PR, with the `capture_soft_fails: false` configuration option of this bundle, see https://github.com/getsentry/sentry-symfony#configuration-of-the-sdk

**Comment by VincentLanglet** [comment]
> This was already implemented in the original PR, with the `capture_soft_fails: false` configuration option of this bundle, see https://github.com/getsentry/sentry-symfony#configuration-of-the-sdk

Hi @Jean85 ! Thanks for your quick answer.

I just made a try with:
```
messenger:
   enabled: true
   capture_soft_fails: false
```
And the retry strategy:
```
retry_strategy:
  max_retries: 3
  delay: 5000
```

I'm also use the monolog handler for sentry
```
    monolog:
        error_handler:
            enabled: true
            level: error
```

With a MessageHandler like
```
public function __invoke(Message $message)
    {
        $id = $message->getId();

        throw new \Exception("EEREYUE $id");
    }
```

I get the following exceptions on Sentry
![image](https://user-images.githubusercontent.com/9052536/91860911-8332f780-ec6c-11ea-9037-41eb5ca139aa.png)

If I use 
```
messenger:
   enabled: true
   capture_soft_fails: true
```
I get each exceptions 4 times.

Shouldn't the `Symfony\Component\Messenger\Exception\HandlerFailedException` by send to Sentry only once if I use `capture_soft_fails: false` ?

**Comment by Jean85** [comment]
The issue is in the fact that you're using both the integration and the Monolog handler. The option regards the native integration only, see https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/MessengerListener.php#L36

**Comment by VincentLanglet** [comment]
> The issue is in the fact that you're using both the integration and the Monolog handler. 

Yes, but it could be great to support this :) 

> The option regards the native integration only, see https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/MessengerListener.php#L36

What are my options ?
- Should I exclude the `Symfony\Component\Messenger\Exception\HandlerFailedException` since it's handled by your messenger support ? (Then I/we could add a word about this on the doc)
- Does a PR is required on this repo ?

**Comment by Jean85** [comment]
Using both is not something I expect from this bundle, it leads to a lot of mess. We're considering switching to Monolog only in #337

**Comment by VincentLanglet** [comment]
> Using both is not something I expect from this bundle, it leads to a lot of mess. 

Using only monolog wouldn't allow to ignore soft fail exceptions. Which is a pretty useful feature.

**Comment by Jean85** [comment]
Ouch, you're right!

But how do you handle having both enabled? Don't you receive duplicated events anyway?

**Comment by VincentLanglet** [comment]
> But how do you handle having both enabled? Don't you receive duplicated events anyway?

I made multiple try with the following example
```
public function __invoke(Message $message)
{
     $id = $message->getId();

     throw new \Exception("EEREYUE $id");
}
```

With
```
messenger:
   enabled: true
   capture_soft_fails: true
```
I received 4 Exceptions and 4 HandlerFailedExceptions, so they indeed does the same things.

With
```
messenger:
   enabled: true
   capture_soft_fails: false
```
I received only 1 Exception but still 4 HandlerFailedExceptions. So I understood that the messenger integration send the Exception to Sentry, and the logger was sending the HandlerFailedExceptions.

With
```
    messenger:
        enabled: true
        capture_soft_fails: false
    options:
        excluded_exceptions:
            - Symfony\Component\Messenger\Exception\HandlerFailedException # Handled by messenger integration
```
I have no duplicate now.

If you want to switch to Monolog only, it would just need a special treatment for HandlerFailedException. But I'm not sure how/if you can know that there will be a `retry`...

**Comment by B-Galati** [comment]
See my message here: https://github.com/getsentry/sentry-symfony/issues/337#issuecomment-687293670
