### ISSUE TITLE
Errors not arriving in Sentry

### ISSUE THREAD

**Issue by yourithielen** [getsentry/sentry-symfony#369]
Hi,

On my production server running `./bin/console sentry:test` works as expected: a message ID is shown and the message arrives in Sentry. But when I throw an uncaught exception in my controller it doesn't arrive in Sentry.

When I use `\Sentry\captureException()` and ID is returned in production but no message arrives in Sentry.

When I try the above on my development machine it works as expected, for both `prod` and `dev` environments (set in `.env`). 

Any idea what to look for?

I'm using version 3.5.2, Symfony Flex and FOSrestbundle 2.8.2

**Comment by Jean85** [comment]
You should check what you're doing to Sentry in prod, if you're doing something different. Maybe the payload is too big? Maybe the serialization of the data fails for some reason? Have you checked the logs?

**Comment by yourithielen** [comment]
The logs don't show anything unusual. Also, when an error occurs, a request is being send to Sentry: `Sep 18 09:52:57 XXX kernel: [719714.779891] Outgoing Web request: IN= OUT=ens32 SRC=XXX DST=35.188.42.15 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=42459 DF PROTO=TCP SPT=39424 DPT=443 WINDOW=29200 RES=0x00 SYN URGP=0 UID=33 GID=33` (syslog).

If the payload is to big I would expect an error `HTTP Error 413 Payload Too Large`.

**Comment by yourithielen** [comment]
I debugged `Sentry\Transport\HttpTransport` in production and found out that `cleanupPendingRequests` receives an error reponse from Sentry: `< HTTP/1.1 413 Request Entity Too Large`.

Is this caused by `sentry-symfony`?

**Comment by yourithielen** [comment]
Found out that the request I was making had a POST attachment attached. Somehow this POST data was also sent to Sentry as context.
