### ISSUE TITLE
How to setup logging for sentry/sentry?

### ISSUE THREAD

**Issue by yourithielen** [getsentry/sentry-symfony#370]
How do I setup sentry/sentry logging? I've had some issues sending messages to Sentry (HTTP Error 413 Payload Too Large) but could not find this anywhere in my logs.

I found out that `Sentry\Transport\HttpTransport` uses a `Psr\Log\NullLogger`. I'm not using autowiring.

What value should I pass to `sentry.options.logger`? I've tried a few but none of them work.

**Comment by yourithielen** [comment]
Had a look at the inner workings and it seems the current version is not compatible with https://github.com/getsentry/sentry-php/pull/989. Thoughts?

**Comment by yourithielen** [comment]
For now I fixed it like this:
`    Sentry\ClientBuilderInterface:
      class: Sentry\ClientBuilder
      public: false
      arguments:
        - '@Sentry\Options'
      calls:
        - setLogger: ['@logger']`

**Comment by Jean85** [comment]
That's the correct way to do it. getsentry/sentry-php#989 is for the 3.0 release, so that's way you can't use it yet.

**Comment by soullivaneuh** [comment]
In that case, what is the goal of `sentry.options.logger`?

It's quite hacky to override a vendor service.

**Comment by soullivaneuh** [comment]
@yourithielen Here is a less intrusive way using the kernel with `CompilerPassInterface`:

```php
namespace App;

use Symfony\Component\HttpKernel\Kernel as BaseKernel;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

final class Kernel extends BaseKernel implements CompilerPassInterface
{
    use MicroKernelTrait;

    public function process(ContainerBuilder $container): void
    {
        $container->getDefinition(\Sentry\ClientBuilderInterface::class)->addMethodCall(
            'setLogger',
            [new Reference('logger')]
        );
    }
}
```

**Comment by ste93cry** [comment]
>In that case, what is the goal of `sentry.options.logger`?

That option sets the [`logger` option](https://develop.sentry.dev/sdk/event-payloads/#optional-attributes) of the SDK (and fills the field with the same name in the event), it's not for setting the PSR-3 logger 😉

**Comment by soullivaneuh** [comment]
@Jean85   Since the v4 of this bundle, the `ClientBuilderInterface`service does not exist anymore.

What is the correct way to set a logger on the sentry client now? Do we have a documentation about this?

**Comment by Jean85** [comment]
There's a full upgrade doc here: https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md

Keep in mind that some stuff may belong to the underlying SDK, which has its upgrade document here: https://github.com/getsentry/sentry-php/blob/master/UPGRADE-3.0.md

**Comment by soullivaneuh** [comment]
@Jean85 Yes, I did read this documentation first, it says:

> Removed the Sentry\ClientBuilderInterface and Sentry\Options services.

But there is not indication about the migration to do, especially for this not documented case.
Currently, I have not clue about how to keep our custom logger on the Sentry client.

Am I missing something?

**Comment by ste93cry** [comment]
Looking at the code I think there is no easy way, since as you said the builder is not anymore registered as a service mainly because it was not stateless (a mistake) and therefore an instance is not really re-usable to create different clients. What we can definitely do however, and maybe also the best thing, is to expose an option `sentry.logger` which points to a service and is set on the builder service when building the container. WDYT?

**Comment by soullivaneuh** [comment]
@ste93cry You may. However, thanks to the Symfony's auto-wiring system to automatically bind the `LoggerInterface` if available.

Both of them allow two advantages:

1. Ready to use sentry client with configured logging, that will cover 99% of the needs.
2. The possibility to change the logger we want to plug on the sentry client.

My two cents. :+1:

**Comment by ste93cry** [comment]
Using the main logger is not something recommended, because it may create a loop if you use Monolog to report errors to Sentry rather than relying on the custom error handler, which is something we absolutely want to throw away in the next major because it goes into conflict with the built-in one of Symfony.
