### ISSUE TITLE
Commande sentry:test does not check return code

### ISSUE THREAD

**Issue by odoucet** [getsentry/sentry-symfony#372]
I'm investigating an issue with Sentry server configuration.
I tried to use `php bin/console sentry:test` to send a fake event to Sentry server.
Message printed is : 

`Message sent successfully with ID 0f26408bbc4d4f06970aabaecb89193b`

But the server actually answered with a 403 error. This should be tested and printed to help check the full chain.

**Comment by Jean85** [comment]
This seems to be the not first time this is raised as an issue, see #369.
We could probably leverage the logger like in #370.

**Comment by tamert** [comment]
I living  a smilar issue. 
```
DSN correctly configured in the current client
Sending test message...
Message sent successfully with ID 0bc9ef1332d545fdb1277f3dfc00bb12
```
but havent a issue from issue box

**Comment by odoucet** [comment]
bump
