### ISSUE TITLE
Support sentry-php 3.0

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-symfony#374]
https://github.com/getsentry/sentry-php/releases/tag/3.0.0

**Comment by webmozart** [comment]
Is that integration supposed to read and use the `Sentry-Trace` header passed along by the frontend?

**Comment by Jean85** [comment]
@webmozart I don't know, that's the base SDK that this bundle integrates: so if you need that feature, it's something to be done there first, then we can try to support it here too.

**Comment by qstiegler** [comment]
It would be really great if you could update the package son so the performance tracing feature can be used. Thanks in advance!
