### ISSUE TITLE
before_send does not accept instance methods

### ISSUE THREAD

**Issue by Bilge** [getsentry/sentry-symfony#378]
Since `before_send` expects a callback, the only valid callback target is a static method or an object implementing `__invoke`. We can specify a service with `before_send: '@myService'` which will work if `myService` implements `__invoke`. However, in the case that we want to use a specific instance method of `myService`, there is no way to specify this because Symfony will not substitute the service in an array. That is,  `before_send: ['@myService', myMethod]` is passed as an array of two strings instead of an array of an object and a string.

**Comment by Jean85** [comment]
That's not the only way: you could create a factory which returns the closure directly, or the callback in any other desired format.

**Comment by Bilge** [comment]
Create a factory... and do *what* with it? There isn't a *before_send_factory* option, `before_send` requires a callback, not a factory creating a callback.

**Comment by Jean85** [comment]
The factory can be used as a way to create a service, see https://symfony.com/doc/current/service_container/factories.html

So you could do something like:
```yaml
services:
  my_custom_before_send_callback:
    factory: ['@App\BeforeSendCallback', 'create']
```
```php
class BeforeSendCallback
{
    public function create(): callable
    {
        return function () // ...
    }
}
```

**Comment by Bilge** [comment]
That doesn't indicate how the factory is used in the `before_send` configuration of this bundle.

**Comment by Jean85** [comment]
In the example, `my_custom_before_send_callback` is a callable as a service; at that point, you can use `before_send: @my_custom_before_send_callback`.

**Comment by Bilge** [comment]
All you have done is tell me what I already stated in the premise of this ticket. We _can_ specify a callable class but we _cannot_ specify a callback to a named method of that class. This isn't the solution I am looking for.

**Comment by Jean85** [comment]
Then, I'm happy to accept a PR that fixes this behavior and accepts that new form of specifying the callable.

**Comment by Jean85** [comment]
4.0 changed and reduced the way to define this, now only a service is the accepted way to input it.

**Comment by Bilge** [comment]
@Jean85 Thanks for the heads up on the change. Sounds good 👍
