### ISSUE TITLE
on MASTER (dev-master a28795f with SDK 3.0.4): "excluded_exceptions" no longer supported under sentry.options

### ISSUE THREAD

**Issue by tobikars** [getsentry/sentry-symfony#390]
on MASTER (dev-master a28795f with SDK 3.0.4): "excluded_exceptions" no longer supported under sentry.options: 

[critical] Uncaught Exception: Unrecognized option "excluded_exceptions" under "sentry.options". Available options are "attach_stacktrace", "before_breadcrumb", "before_send", "capture_silenced_errors", "class_serializers", "context_lines", "default_integrations", "enable_compression", "environment", "error_types", "http_proxy", "in_app_exclude", "in_app_include", "integrations", "logger", "max_breadcrumbs", "max_request_body_size", "max_value_length", "prefixes", "release", "sample_rate", "send_attempts", "send_default_pii", "server_name", "tags", "traces_sample_rate", "traces_sampler".

**Comment by Jean85** [comment]
This is absolutely expected due to #385; master is currently receiving PRs to work toward a 4.0 release, which will support `sentry/sentry` 3.0.

**Comment by Jean85** [comment]
Please keep a look on https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md (and further updates) with notes about the incoming breaking changes for the 4.0 release.

**Comment by TomasVotruba** [comment]
@Jean85 Thank you for the upgrade.md link. I've just came across same issue and the link helps a lot :+1:
