### ISSUE TITLE
Options config value accepts only scalar values

### ISSUE THREAD

**Issue by ste93cry** [getsentry/sentry-symfony#41]
I was trying to set the `options` config key in the Symfony configuration but it accepts only scalar values while it should accept an array of key/values. Changing the `prototype` of the node from `scalar` to `variable` in the config tree builder works, although I think it would be better to have a full definition that checks all options available so that a user cannot add whatever he wants. Let me know what you think about this, I could submit a PR that fixes the issue

**Comment by Jean85** [comment]
You are right! It should accept a full array, but maybe we should limit the amount possible stuff that can be passed in there?

PR is more than welcome!

**Comment by ste93cry** [comment]
>but maybe we should limit the amount possible stuff that can be passed in there?

Indeed, but does it makes sense to invest time in doing it now when 2.0 version of the base library is being developed?

>It should accept a full array

Indeed, at the moment noone can use the options because of this

**Comment by michaelzangerle** [comment]
I discovered the same issue when setting tags via options and took a look at the configuration tree of the bundle. There seems to be same issue multiple times (options, skip_capture, prefixes, excluded_app_paths, ...). The `prototype` is defined as `scalar` although the default is an `array`.

I thought about creating a PR to define the options that are also used by the Raven-Client but then again some values are set via setter injection and some via the configuration. I can think of three possible solutions:

- A. Add all the options the client accepts to the options property of the configuration tree and get rid of those that would be duplicate like `environment` (BC break).
- B. Create all the configuration options the client accepts at the same level as `environment` and pass the whole configuration on to the client (not that clean). `options` could then be removed.
- C. Leave the existing configuration properties as they are and add the not existing ones to the `options` property (not very clean but would not cause a BC break).

What do you think? I would prefer solution A as it is the cleanest one but some feedback before starting on the PR would be appreciated.

**Comment by Jean85** [comment]
Since `options` is not working in the current form, I wouldn't consider it a BC changing the way it works; I also like option A, but I would prefer to deprecate first and drop later (in next major) the duplicates; we can accept both and throw an exception when **both are defined but with different values**.

In fact this is a mixed A-C approach, but just as a deprecation path towards a full-A case. I think that would be better, since in next major we will probably rewrite the option part anyway, due to the v2 ov the Sentry client.

**Comment by michaelzangerle** [comment]
@Jean85 Do you know when the next major will be released? I am just wondering if it's even worth to change it or just move on to the next version...

**Comment by Jean85** [comment]
The v2 of the Sentry client is currently being worked on, but it's still a long way to go, it will not be ready for months.

**Comment by Jean85** [comment]
Issue solved! I will tag it next week.
