### ISSUE TITLE
Adding support for performance monitoring

### ISSUE THREAD

**Issue by rjd22** [getsentry/sentry-symfony#418]
At this moment this bundle doesn't yet have proper support for performance monitoring. I'm thinking about helping out and implementing it. But am unsure what would be the preferred way to implement it.

I could make a Tracing event listener that listens to the `kernel.request` and `kernel.terminate` events? What do you guys think?

Example of Laravel's implementation:
https://github.com/getsentry/sentry-laravel/blob/master/src/Sentry/Laravel/Tracing/Middleware.php

**Comment by Jean85** [comment]
We want to add that feature as the next step. That wasn't included in 4.0 only because we didn't want to delay the release further. You're welcome to start working on it if you want, happy to help and review through it; using the Laravel integration as reference is a good start.

Surely a listener that starts and stops it on request is ok, but you would have to:
 * make the feature opt-in
 * take sub-requests into account, as we do with the `SubRequestListener`
 * take into account other listeners and their priorities, that we slightly changed in 4.0 exactly to have room to fit this feature in

**Comment by rjd22** [comment]
@Jean85 Do you have reasoning that the feature needs to be opt-

**Comment by rjd22** [comment]
@Jean85 maybe it would be best to require the users to tag the listeners and decide priority themselfes? This allows us to make more separate tracing listeners for also things like Doctrine and allows users more flexibility on where they want them in their system and which ones they want.

**Comment by Jean85** [comment]
That doesn't seem sensible to me. The default listeners that we already have have influence on the new ones; also, it should be easy for us to disable the behaviour since we can read the tracing configuration.

**Comment by rjd22** [comment]
@Jean85 The reasoning I'm asking is because Symfony has quite a lot of examples in their code on how to do the tracing. This also includes Twig rendering and Doctrine queries.

Since these bundles are optional wouldn't it be wise to allow the developer some flexibility? Another way would be of course somehow check if these bundles are installed and add the listeners automaticly.

Example of a Symfony WebProfiler trace:

![Screenshot from 2021-01-21 09-41-58](https://user-images.githubusercontent.com/160743/105325927-6cfee700-5bcd-11eb-908c-c303474b5f13.png)

**Comment by Jean85** [comment]
Checking for bundle existence is pretty straightforward, since checking for the class presence (DataCollectors?) is more than enough. Tracing for Twig and Doctrine is more than enough for starters. Next step could be the HTTP client or the cache.

**Comment by rjd22** [comment]
@Jean85 I've been working on the implementation and here is the initial implementation. I would like some feedback on the inner workings:

https://github.com/getsentry/sentry-symfony/pull/423

**Comment by rjd22** [comment]
https://github.com/getsentry/sentry-symfony/pull/423 got merged! :partying_face: :tada:
