### ISSUE TITLE
Symfony reports deprecations since 4.0

### ISSUE THREAD

**Issue by ruudk** [getsentry/sentry-symfony#419]
After upgrading to 4.0 I see this in my logs:
```
2021-01-21T12:24:32+00:00 [info] User Deprecated: The "Sentry\State\HubAdapter::startTransaction()" method will require a new "array<string, mixed> $customSamplingContext" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.

2021-01-21T12:24:32+00:00 [info] User Deprecated: The "Sentry\State\Hub::startTransaction()" method will require a new "array<string, mixed> $customSamplingContext" argument in the next major version of its interface "Sentry\State\HubInterface", not defining it is deprecated.
```

Related to https://github.com/getsentry/sentry-php/pull/1134.

As this is reported by Symfony I report it here in the SymfonyBundle repository. 

How can this be solved?

**Comment by Jean85** [comment]
The tracing feature should be enabled by default, can you confirm that?
How did you enable that? Can you share a stacktrace of this issue?

**Comment by ruudk** [comment]
It happens because there is a new `@param` defined in phpdoc of `HubInterface` but not in the function argument, see https://github.com/getsentry/sentry-php/blob/d727bd1a35523b96dfe450ec4e8406338cec816c/src/State/HubInterface.php#L143-L145

The issue is reported by Symfony's DebugClassLoader. 

See https://github.com/symfony/error-handler/blob/7d9e5470d7bfb692f1db4c4dfe79bd5ff3312ca1/DebugClassLoader.php#L675

**Comment by Jean85** [comment]
Oooh now I get it! Well, we're the same maintainers, and that feature has still to be implemented, so it should be a non-issue...

**Comment by ruudk** [comment]
I understand. But it will now warn until this is implemented for every Symfony user that upgrades to 4.0.

**Comment by Jean85** [comment]
I understand but I don't know how to silence this. It seems to be triggered even if the code is used in a FC way, right?

**Comment by ruudk** [comment]
It can be silenced by removing the phpdoc from the interface.

**Comment by Jean85** [comment]
@ste93cry what do you think? Should we remove or alter it to avoid those deprecations?

**Comment by ste93cry** [comment]
>It can be silenced by removing the phpdoc from the interface

It won't be necessary, you made me find out some weeks ago that the signature of a method in a class implementing an interface can be different if the new arguments have a default value. so we can add the argument to the `HubAdapter` and `Hub` classes to solve the issue

**Comment by Jean85** [comment]
Fixed in https://github.com/getsentry/sentry-php/pull/1176

**Comment by ruudk** [comment]
✅  Confirmed that https://github.com/getsentry/sentry-php/commit/540fd64e20381feeb269e151eb7227fa3aecdb75 works and the deprecation notice is now gone!
