### ISSUE TITLE
How to ignore local environment?

### ISSUE THREAD

**Issue by viion** [getsentry/sentry-symfony#432]
Not a Feature request as such, unless this doesn't exist.

I have everything setup and running fine however when developing locally it is common to get a lot of errors, either typos, random expectation of errors, testing, etc. the problem is these all get sent to Sentry, is there an option in the yaml to set it to ignore/not send exceptions thrown whilst in the local environment?

Regards

**Comment by ste93cry** [comment]
By just not setting the DSN option or setting it to an empty string, Sentry will still run but no events will be really sent to the server

>The DSN tells the SDK where to send the events. If this value is not provided, the SDK will try to read it from the SENTRY_DSN environment variable. If that variable also does not exist, the SDK will just not send any events.

https://docs.sentry.io/platforms/php/guides/symfony/configuration/options/#dsn

**Comment by viion** [comment]
thanks @ste93cry i think that also made me realise i can move the `yml` to an environment specific folder, eg `config/packages/prod` for instance then handle the config per env!

I think that solves my question!
