### ISSUE TITLE
Configuration property to activate sending extra data in 4.0

### ISSUE THREAD

**Issue by simonberger** [getsentry/sentry-symfony#439]
Sentry 3 changed to not send tags/extra data anymore automatically

```
The Monolog handler does not set anymore the tags and extras on the event by extracting automatically the data from the record payload. You can decorate the class and set such data on the scope as shown below:
```
https://github.com/getsentry/sentry-php/blob/master/UPGRADE-3.0.md

I missed upgrade entry in 4.0 of this bundle or better an easy solution to configure this.

Can you add a configuration property for this and add it to Sentry\Monolog\Handler?

To activate it in our project again I copied your handler and added a `setExtras` call. This follows the upgrade guide of the sentry-php package. If this could be wrapped by a configuration property of the bundle for extra data and tags which is disabled by default, this would be a great addition

```
public function handle(array $record): bool
    {
        $result = false;

        withScope(function (Scope $scope) use ($record, &$result): void {
            //$scope->setTags();
            if (isset($record['context']['extra'])) {
                $scope->setExtras($record['context']['extra']);
            }

            $result = parent::handle($record);
        });

        return $result;
    }
```

**Comment by ste93cry** [comment]
This is a frequently requested question which can find its answer in getsentry/sentry-php#848. There are no plans to revert this change, but the `UPGRADE` file you found provides a solution using the decorator pattern which should work well with most use-cases

**Comment by simonberger** [comment]
@ste93cry This feature request does not ask to revert this change. It asks for an easy way to activate it in this symfony bundle wrapper of the sentry package.
Are there any reasons against?

**Comment by ste93cry** [comment]
>It asks for an easy way to activate it in this symfony bundle wrapper of the sentry package

It doesn't matter if behind a configuration option or not, asking for a way to enable a behaviour that has been dropped in the core SDK is like asking for the feature to be reimplemented, don't you agree?

**Comment by simonberger** [comment]
> > It asks for an easy way to activate it in this symfony bundle wrapper of the sentry package
> 
> It doesn't matter if behind a configuration option or not, asking for a way to enable a behaviour that has been dropped in the core SDK is like asking for the feature to be reimplemented, don't you agree?

Yes I agree but that wasn't the discussion here.
I asked to re-add an old functionality instead of reverting this change.

I now read the linked issue in detail and see it was an unwanted feature. Still I don't see the reason to not now allow it behind an option. Especially if it is improved via serialization.

**Comment by ste93cry** [comment]
I'm closing this because an answer has been given: we don't plan to reintroduce this feature soon, nor to revert the decision we took in the past regarding this particular topic. As mentioned in the UPGRADE file, you can use the decorator pattern to log the data, with the added bonus that you are able to discern what to log and what not
