### ISSUE TITLE
Outdated documentation about sentry.monolog setting

### ISSUE THREAD

**Issue by denisvmedia** [getsentry/sentry-symfony#441]
[This PR](https://github.com/getsentry/sentry-symfony/pull/406) removes `sentry.monolog` setting, but it's not reflected in the documentation. In addition, I think, it could be nice to have an explanation on how to work without this setting.

**Comment by douglasjam** [comment]
https://github.com/getsentry/sentry-symfony/issues/438

**Comment by denisvmedia** [comment]
I see. Closing this ticket.
