### ISSUE TITLE
Explicit `null` dsn no longer disables Sentry

### ISSUE THREAD

**Issue by bobvandevijver** [getsentry/sentry-symfony#453]
### Environment

sentry-symfony 4.0.1 / sentry-php 3.1.5

### Steps to Reproduce

Set the following configuration:
```
sentry:
  dsn: ~ # Or ''
```

### Expected Result

Sentry client should not push any event to the Sentry instance.

### Actual Result

But it does. Due to this particular change, a falsy dsn value will be unset from the configuration: https://github.com/getsentry/sentry-symfony/commit/c95a2bd49525db1cf4da5d36c45f19d9e8cc3912#diff-ebe00144d6cecb5ca8a2860883e01147f42bbed2b12a3a7f44915908a4829faaR30

As it is unset, it is not forwarded to the Sentry Client options and that causes sentry-php to fallback to the `SENTRY_DSN` defined in the environment, as that is the default: https://github.com/getsentry/sentry-php/blob/master/src/Options.php#L693

Either the documentation here should be updated (and it should be added to the 4.0 upgrade notes) that you need to disable it using some other method (I do not know which one), or the value should not be unset in the configuration.

**Comment by ste93cry** [comment]
>Either the documentation here should be updated (and it should be added to the 4.0 upgrade notes) that you need to disable it using some other method (I do not know which one), or the value should not be unset in the configuration.

This is indeed a bug, setting `null`, `false` or an empty string should disable Sentry as written in the documentation and as it always worked in the past. I opened a PR to fix the issue, thank you for reporting the problem 😉

**Comment by Jean85** [comment]
Reported as not fully fixed in https://github.com/getsentry/sentry-symfony/pull/457
