### ISSUE TITLE
Not connecting issues (errors) with traces

### ISSUE THREAD

**Issue by askold123** [getsentry/sentry-symfony#456]
As seen from this video https://youtu.be/sA1rED-zb6w?t=375 exceptions can be connected with transaction, but this library does not provide such function.

I'm starting transaction as it described in your doc:
```
$transactionContext = new \Sentry\Tracing\TransactionContext();
$transactionContext->setName('External Call');
$transactionContext->setOp('http.caller');
$transaction = \Sentry\startTransaction($transactionContext);

$spanContext = new \Sentry\Tracing\SpanContext();
$spanContext->setOp('functionX');
$span1 = $transaction->startChild($spanContext);

// Calling functionX
$this->functionX();
$span1->finish();

$transaction->finish();
```
 and if exception occures, it is sent separately and is not connected to transaction in Sentry UI.

**Comment by Jean85** [comment]
I'm not sure if this is an issue for the bundle or for the base SDK... @ste93cry?

**Comment by ste93cry** [comment]
>this is an issue for the bundle

There is no indication that it involves Symfony, so I would say no. At the same time however, I know very little of the distributed tracing feature of Sentry so I cannot determine if this is either a bug or something that is working as expected, regardless of the video, and maybe there is something else missing that must be done manually to link together a transaction and an error. @stayallive @HazAT can you please help us?

**Comment by askold123** [comment]
Yes, it relates to base SDK.
I will copy this issue there

**Comment by Jean85** [comment]
FTR reopened as https://github.com/getsentry/sentry-php/issues/1192.
