### ISSUE TITLE
Installation currently broken due to new symfony/psr-http-message-bridge recipe

### ISSUE THREAD

**Issue by weaverryan** [getsentry/sentry-symfony#463]
Hi!

This is more of an FYI that the installation is currently broken, but the problem is with a new recipe. Here is an issue that describes the situation: https://github.com/symfony/recipes/issues/909

At this time, I don't think this library will need to do anything - I thought I would share to let you know, and help others. The current work around (which is explained in the docs, but is currently ALWAYS needed, regardless of your version of SensioFrameworkExtraBundle) is to either `composer remove nyholm/psr7` or delete the `config/packages/psr_http_message_bridge.yaml` file that comes with the recipe. 

### Environment

Using Symfony and v4 of sentry-symfony.

### Steps to Reproduce

`composer require sentry/sentry/symfony` into a Flex enabled project. You will get the same error as described in #446

Cheers!

**Comment by Jean85** [comment]
Hi @weaverryan! We are currently already aware of the problem, and as you said, we already merged #445 to warn our users of the issue. Let us know if you think the wording is fine, or if we should improve it!

**Comment by nicolas-grekas** [comment]
Can be closed I think.

**Comment by Jean85** [comment]
Thank you Nicolas.

FTR this is fixed thanks to the new psr7-pack from https://github.com/symfony/recipes/pull/911
