### ISSUE TITLE
Enabling tracing slows down render to screen

### ISSUE THREAD

**Issue by rjd22** [getsentry/sentry-symfony#464]
I've been testing the implementation of the tracing and I noticed the render to screen was delayed by a lot when tracing is enabled. Do notice that with "render to screen" I mean the time it takes for the HTML content to be presented on the client.

I might have been wrong but as far as I knew this was not present in my implementation so I reviewed the current implementation and my eye fell on the following lines:

https://github.com/getsentry/sentry-symfony/blob/develop/src/EventListener/TracingRequestListener.php#L51-L64

If I understand this right when calling `$transaction->finish();` the results are collected and send to sentry. But this is still at the moment rendering is happening in Symfony. If we move this part to `TerminateEvent` the sending to sentry will happen after render. Making the application feel more responsive for the user even when tracing is present with the added advantage that if something goes wrong with tracing the user won't even notice it.

@ste93cry @Jean85 I'm not sure if everything I'm saying is right because I don't know how Sentry handles the `finish` internally but could you confirm if I might be right?

Edit:
I've now tested this. The response time dropped from 600ms to 100ms on my personal application.

Before change:
![Screenshot from 2021-03-13 13-21-59](https://user-images.githubusercontent.com/160743/111029857-460ba700-83ff-11eb-9d07-901520a2f7b8.png)

After change:
![Screenshot from 2021-03-13 13-22-37](https://user-images.githubusercontent.com/160743/111029865-4f950f00-83ff-11eb-8a5f-4dc9d30ef551.png)

**Comment by ste93cry** [comment]
>If I understand this right when calling `$transaction->finish();` the results are collected and send to sentry. But this is still at the moment rendering is happening in Symfony

Correct

>If we move this part to `TerminateEvent` the sending to sentry will happen after render. 

Also correct. The reason I changed from that event to the `FinishRequestEvent` event is that as far as I understood the latter is dispatched right after the response is returned by the controller but before it is sent to the client while the first is dispatched when the application exits, therefore we would possibly measure time for things not strictly related to the request handling.

>The response time dropped from 600ms to 100ms on my personal application

I definitely expected such result after your change. I'm not sure if it's more right to end the transaction when the application terminates or if we should find the way to delay the sending of the transaction until that moment instead of immediatly

**Comment by rjd22** [comment]
@ste93cry I would say that the transaction should end as late as possible to not infer with other processes that also happen in KernelTerminate (priority 1000?). Tracing should also tell you that something is becoming slow in KernelTerminate like writing the session cookie or logs for example.

But I would recommend adding to spans so someone can see the difference between the two parts of the process. For example a `kernel.request` and a `kernel.terminate` span.

I do feel strongly that not interfering with application performance is more important than having correct tracing timings. So I would still merge my PR before releasing even without the extra spans.

**Comment by stayallive** [comment]
In Laravel we also do it on the termination of the request, so I'd say this is a good change.

Of course next to this change Relay would still be recommended (this is documented already). 

Slightly related: this improvement only really works when using php-fpm. I have not seen this "trick" of delaying execution to after the response was sent on Apache PHP for example. But either way a good change, just something to note.

**Comment by ste93cry** [comment]
>I do feel strongly that not interfering with application performance is more important than having correct tracing timings. So I would still merge my PR before releasing even without the extra spans.

Absolutely agree that we have to solve performance issues if they are serious 😉 

>But I would recommend adding to spans so someone can see the difference between the two parts of the process. For example a `kernel.request` and a `kernel.terminate` span.

I agree. I had a look at how the profiler works in Symfony and it looks like they collect the data on `kernel.response` and then they collect additional data and save the profile on `kernel.terminate`. I think we should do something similar, by rethinking the stack of the transaction as you suggest: the transaction should wrap the entire application lifecycle, starting with the handling of the master request and ending with the termination of the app. A first span should be added to the start of the master request and should terminate when its response has been sent. WDYT?

**Comment by rjd22** [comment]
@ste93cry sounds like a plan 👍

**Comment by rjd22** [comment]
Since the fix was merged I'm closing this ticket. 👍
