### ISSUE TITLE
Support custom SDK fingerprinting

### ISSUE THREAD

**Issue by annuh** [getsentry/sentry-symfony#474]
I would like to use override Sentry's default grouping by providing a custom fingerprint for specific exceptions.

There is some documentation about this in the official Sentry PHP documentation: 
 https://docs.sentry.io/platforms/php/data-management/event-grouping/sdk-fingerprinting/. 

```php
try {
  // Run code that for example throws a MyRpcException
} catch (MyRpcException $e) {
  \Sentry\withScope(function (\Sentry\State\Scope $scope) use ($e) {
    $scope->setFingerprint([
      '{{ default }}',
      $e->getFunctionName(),
      $e->getStatusCode(),
    ]);
    \Sentry\captureException($e);
  });
}
```
But I can't figure how this can be used in this integration.

Is it possible to support this function in this Symfony integration for Sentry? 🙂

**Comment by Jean85** [comment]
This would absolutely work out of the box, this bundle integrates the base SDK as it is.

The `\Sentry\*()` functions are just global static shortcuts for doing the same stuff with the `HubInterface`, so you could either use that snippet verbatim or inject `HubInterface` in your services and call the methods on it in the same way.

**Comment by ste93cry** [comment]
I'm closing this because issue is quite old and the question has been answered. Feel free to reopen should you still have doubts
