### ISSUE TITLE
Develop branch breaks on non-existent parameter "sentry.tracing.enabled"

### ISSUE THREAD

**Issue by nicwortel** [getsentry/sentry-symfony#476]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
sentry/sdk 3.1.0
sentry/sentry 3.2.0
sentry/sentry-symfony dev-develop 8e2fbda

PHP 8.0.3, Symfony 5.2.4

### Steps to Reproduce

1. `composer require sentry/sentry-symfony dev-develop`

### Expected Result

The latest development version of this package is installed so I can test the performance monitoring features (which appear to not work in the latest release, 4.0.3).

### Actual Result

The `cache:clear` script which is run after `composer require` fails with:

> You have requested a non-existent parameter "sentry.tracing.enabled". Did you mean this: "sentry.tracing.dbal.enabled"?

Then the `composer.json` and `composer.lock` files are reverted to their original content.

If I run `composer require` with `--no-scripts` the Composer command is executed succesfully but then I get the same error with every request and every Symfony command I call.

The stack trace leads to `vendor/sentry/sentry-symfony/src/DependencyInjection/Compiler/DbalTracingPass.php:36`: 

https://github.com/getsentry/sentry-symfony/blob/8e2fbdafd86b1e888e5073cd9a3844b6c137b415/src/DependencyInjection/Compiler/DbalTracingPass.php#L36

**Comment by ste93cry** [comment]
Thank you for the report, fix has been merged
