### ISSUE TITLE
Ignore ErrorException thrown by Symfony

### ISSUE THREAD

**Issue by duxet** [getsentry/sentry-symfony#48]
After catching errors (like `TypeError`) Symfony is also throwing `ErrorException` and that results in two exceptions being reported to Sentry instead of reporting only the first one.

The simplest solution would be adding `ErrorException` to list of ignored exceptions, but i am not sure if that's a good idea.

**Comment by delamart** [comment]
I was wondering the same and it looks like ignoring ErrorException is not an option.
I had an ErrorException triggered by an undefined array index which I believe is an E_NOTICE so I got a sentry issue for that which I would not have had at all if I ignored ErrorException.

This is all default configuration for symfony and sentry by the way.

**Comment by Jean85** [comment]
This is starting to seem an unrelated issue or something linked to the base PHP SDK. I'm removing this issue from the stable milestone (see #86).

**Comment by stayallive** [comment]
With sentry-php version 1.8.1 just released, this should be fixed (run composer update). If it still persists for anyone, please open an new issue on getsentry/sentry-php with some info on the error that is duplicated.

**Comment by Jean85** [comment]
Closing as this is fixed with `sentry/sentry` 1.8.1.
