### ISSUE TITLE
Injecting own Spool into SpoolTransport 

### ISSUE THREAD

**Issue by graferowy** [getsentry/sentry-symfony#497]
Hi!

How can I make sentry to use SpoolTransport (taken from one of repository's branches- https://github.com/getsentry/sentry-php/blob/e7fb87f840ab026e9ee9444831b6c7c571f06ed0/src/Transport/SpoolTransport.php). I copied this Transport into my project files (and adjusted it to the current TransportInterface) and how can I now set it as a default transport with spools defined by me?

Using
sentry-symfony 4.1
symfony 5.1

**Comment by graferowy** [comment]
Thank you for your answer. What I end up doing was to get the factory of `sentry.client` definition in my compiler pass. Then I added `setTransportFactory` method call with my spool transport factory. Everything seems to be working fine so I hope it's a valid solution.

`
$transportFactory = $container->getDefinition(SpoolTransportFactory::class);
$sentryClient = $container->findDefinition('sentry.client');
$factory = $sentryClient->getFactory();

if (isset($factory[0]) && $factory[0] instanceof Definition) {
     $factory[0]->addMethodCall('setTransportFactory', [$transportFactory]);
}
`

**Comment by ste93cry** [comment]
Yes, that's another solution indeed. Anyway, maybe in the future we could make some things like setting the transport factory configurable so that you don't have to write hacky compiler passes

**Comment by ste93cry** [comment]
I'm closing this because I think it's solved. Btw, in the upcoming `4.2` version it will be possible to configure the factory in the bundle's config
