### ISSUE TITLE
Consider that pugx/sentry-sdk is abandoned

### ISSUE THREAD

**Issue by kevin-lot** [getsentry/sentry-symfony#499]
What actually happened. Maybe a screenshot/recording? Maybe some logs?

pugx/sentry-sdk is abandonned https://packagist.org/packages/pugx/sentry-sdk.
Repository is archived https://github.com/PUGX/sentry-sdk.
README is not updated https://github.com/getsentry/sentry-symfony/blob/master/README.md#optional-use-custom-http-factorytransport

What is the package that I have to use ?

Tks.

**Comment by ste93cry** [comment]
I'm closing this because I think the question has been given an answer.
