### ISSUE TITLE
Problem with consume memory

### ISSUE THREAD

**Issue by josecantera** [getsentry/sentry-symfony#502]
I have a problem with a long process. 
Every Time call to capture method in a long process consume a bit of memory.
For example a loop comand:

Every call to captureException eat a bit of memory,  Is a problem for me when use in a long process worker
I dont know how clean the memory after capture, is posible ?

```
<?php

namespace App\Command;

use Exception;
use Sentry\ClientInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class TestCommand extends Command
{
    public const COMMAND_NAME = 'app:test';
    private ClientInterface $client;

    public function __construct(
        ClientInterface $client,
        string $name = null
    ) {
        parent::__construct($name);
        $this->client = $client;
    }

    /**
     * @inheritdoc
     */
    protected function configure()
    {
        $this
            ->setName(self::COMMAND_NAME)
            ->setDescription('Test')
            ->setHelp('Tests');
    }

    /**
     * @inheritdoc
     */
    protected function execute(InputInterface $input, OutputInterface $output) : int
    {

        $output->writeln('START '.memory_get_usage());
        for ($i = 1; $i <= 10; $i++) {
            $this->client->captureException(new Exception());
            $output->writeln(memory_get_usage());
        }
        $output->writeln('END '.memory_get_usage());

        return Command::SUCCESS;
    }
}
```

**Comment by Jean85** [comment]
It's possible that we have a memory leak somewhere, but to track it down we would need to profile it somehow, and I do not personally know where to start in a situation like a long running process..

**Comment by josecantera** [comment]
Thks @Jean85  I understand not is normal use.
i am changing to the legacy/deprecated version : https://github.com/getsentry/raven-php , this version dont have problem with memory in long process and is working in tests.

**Comment by Jean85** [comment]
It may still be a normal use here, like with the Symfony Messenger consumer. But I do not have experience with the needed tools to identify the leak.

**Comment by rjd22** [comment]
@Jean85 I might be able to help out on this one. I will check in the coming weeks why this might be happening.

**Comment by Jean85** [comment]
Thank you @rjd22!
