### ISSUE TITLE
Compatibility with AliceBundle

### ISSUE THREAD

**Issue by colinodell** [getsentry/sentry-symfony#503]
### Environment

PHP 7.4
Symfony 5.2
Doctrine DBAL 2.12.1
Doctrine ORM 2.8.4
hautelook/alice-bundle 2.9.0
sentry/sentry 3.2.2
sentry/sentry-symfony 4.1.1

### Steps to Reproduce

- Use the dependencies above
- Have automated functional tests that use Alice's `PurgerLoader` to purge the database before tests run
- Upgrade `sentry/sentry-symfony` from 4.0.3 to 4.1.1
- Run the tests

### Expected Result

- Alice detects that MySQL is being used and disables foreign key checks
- Alice runs a series of TRUNCATE queries
- All queries are successful
- Functional tests begin running

### Actual Result

- Alice fails to detect that MySQL is being used; foreign key checks are not disabled
- Alice runs a series of TRUNCATE queries
- Queries fail due to FK constraints
- Function tests fail to start

Alice uses the following code to determine if MySQL is being used:

```php
public function purge()
{
    // Because MySQL rocks, you got to disable foreign key checks when doing a TRUNCATE/DELETE unlike in for example
    // PostgreSQL. This ideally should be done in the Purger of doctrine/data-fixtures but meanwhile we are doing
    // it here.
    // See the progress in https://github.com/doctrine/data-fixtures/pull/272
    $disableFkChecks = (
        $this->purger instanceof DoctrineOrmPurger
        && in_array($this->purgeMode->getValue(), [PurgeMode::createDeleteMode()->getValue(), PurgeMode::createTruncateMode()->getValue()])
        && $this->purger->getObjectManager()->getConnection()->getDriver() instanceof AbstractMySQLDriver
    );

    if ($disableFkChecks) {
        $connection = $this->purger->getObjectManager()->getConnection();

        $connection->exec('SET FOREIGN_KEY_CHECKS = 0;');
    }

    $this->purger->purge();

    if ($disableFkChecks && isset($connection)) {
        $connection->exec('SET FOREIGN_KEY_CHECKS = 1;');
    }
}
```

The `AbstractMySQLDriver` check fails because this bundle decorates the connection with `Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverConnection` which is not an instance of `AbstractMySQLDriver`.  As a result, Alice can no longer identify the underlying driver in order to disable FK checks.

I believe this breaking change was introduced in #426 and is also causing #485 and #488.  I suspect that code in other projects that relies on driver detection may also experience broken functionality as a result of the driver being decorated in this way.

[Disabling the new DBAL tracing feature](https://github.com/getsentry/sentry-symfony/issues/488#issuecomment-826865279) does seem to prevent the issue from occurring.

**Comment by ste93cry** [comment]
>I suspect that code in other projects that relies on driver detection may also experience broken functionality as a result of the driver being decorated in this way.

You're right. However, decoration is a common programming pattern and in this case I think it's perfectly valid for the use-case of our library. As for the Doctrine migrations issue, I suggest you to report this issue in the Alice repository. The fix should be as simple as checking the database platform instead of using `instanceof AbstractMySQLDriver`

**Comment by colinodell** [comment]
Thanks for the feedback! I'll open a ticket in the other repository.

(And it seems I was mistaken - it wasn't AliceBundle itself, but rather https://github.com/theofidry/AliceDataFixtures)
