### ISSUE TITLE
Problem during composer update - `sentry/sdk/composer.json` not found

### ISSUE THREAD

**Issue by Mariyo** [getsentry/sentry-symfony#507]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
PHP 3.5.4

### Steps to Reproduce

`composer update`

### Expected Result

Update `composer.lock`

### Actual Result

![image](https://user-images.githubusercontent.com/1678254/118642737-fb7e2080-b7db-11eb-9590-9e30a620702a.png)

However, `sentry/sentry/composer.json` exists:

![image](https://user-images.githubusercontent.com/1678254/118642903-29fbfb80-b7dc-11eb-94fc-b85cf781c0f3.png)

**Comment by Jean85** [comment]
This doesn't seem an issue with our code, but something related to your vendor folder. Can you try to `rm -rf vendor && composer install && composer update`?

**Comment by Mariyo** [comment]
Thx for advice, 
I have already tried to delete, but only `vendor/sentry` folder. When I delete whole `vendor`, it seems to work.
