### ISSUE TITLE
I configured sentry-symfony according to the docs, but nothing is logged

### ISSUE THREAD

**Issue by lmeyer1** [getsentry/sentry-symfony#523]
### Environment

I'm using Sentry SaaS (sentry.io).

Which SDK and version? In composer:

    "sentry/sentry-symfony": "^3.5"
    "symfony/symfony": "^3.4.37",

Currently installed:
- symfony/monolog-bundle: 3.5.0
- sentry-symfony: 3.5.4
- symfony: 3.4.37

The application is Prestashop 1.7.7.4 https://github.com/PrestaShop/PrestaShop

### Steps to Reproduce

According to the docs, I modified config.yml

    monolog:
        handlers:
            main:
                type:   stream
                path:   '%env(PS_LOG_OUTPUT)%'
                level:  debug
                channels: ["!event"]
            sentry:
                type: service
                id: Sentry\Monolog\Handler
            console:
                type:   console
                bubble: false
                verbosity_levels:
                    VERBOSITY_VERBOSE: INFO
                    VERBOSITY_VERY_VERBOSE: DEBUG
                channels: ["!doctrine"]
            console_very_verbose:
                type:   console
                bubble: false
                verbosity_levels:
                    VERBOSITY_VERBOSE: NOTICE
                    VERBOSITY_VERY_VERBOSE: NOTICE
                    VERBOSITY_DEBUG: DEBUG
                channels: ["doctrine"]

    sentry:
        dsn: "https://f3***9c@o4***8.ingest.sentry.io/5***0"
    
    services:
        Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $level: !php/const Monolog\Logger::ERROR

There is no file like `bundles.php` as mentionned in the docs. Instead I added 

    $bundles[] = new Sentry\SentryBundle\SentryBundle();

to `app/AppKernel.php`.

### Expected Result

I expect an exception to be sent to sentry.io

    throw new Exception('Test Sentry');

### Actual Result

Nothing is sent to sentry.io. The configuration of the application looks OK:
    
    $ php bin/console debug:config sentry
    
    Current configuration for extension with alias "sentry"
    =======================================================
    
    sentry:
        dsn: 'https://f3***9c@o4***8.ingest.sentry.io/5***0'
        register_error_listener: true
        (...)
        monolog:
            error_handler:
                enabled: false
                level: DEBUG
                bubble: true
        messenger:
            enabled: false
            capture_soft_fails: true

    $ php bin/console debug:config monolog
    
    Current configuration for extension with alias "monolog"
    ========================================================

    monolog:
        handlers:
            main:
                type: stream
                path: '%env(PS_LOG_OUTPUT)%'
                level: debug
                channels:
                    type: exclusive
                    elements:
                        - event
                priority: 0
                bubble: true
    (...)
            sentry:
                type: service
                id: Sentry\Monolog\Handler
                priority: 0
                level: DEBUG
                bubble: true
    (...)

**Comment by stayallive** [comment]
Have you also tried running `php bin/console sentry:test`, this might provide some more information.

**Comment by lmeyer1** [comment]
Thanks @stayallive , I didn't know about this command. It works now !
Both using `sentry:test` and with a real exception.

**Comment by stayallive** [comment]
Curious that it started working after that... but I'm glad you got it up and running 💪

**Comment by lmeyer1** [comment]
@stayallive
It started working while I was writing the issue. I made a small adjustment during the tests 😄

This might help others to use sentry and prestashop together
