### ISSUE TITLE
Lost in app traceback after sentry php sdk update

### ISSUE THREAD

**Issue by vladyslavstartsev** [getsentry/sentry-symfony#526]
### Environment

How do you use Sentry?
On-premise
Which SDK and version?
sentry/sentry-symfony 4.0.1
### Steps to Reproduce

I’ve updated PHP packages

sentry/sentry-symfony from 3.5.3 to 4.0.1
and also updated
sentry/sentry from 2.5.2 to 3.1.5
my sentry server is on premise - version 10.1.0

and I lost in app traceback - the feature where I can see lines of my app where the error failed and also see parameters that where passed to the method/function.

How can I enable it back? What I can do, is downgrade it to the previous version, back this way my app will not stay up to date

### Expected Result

I see full trace of the exception of my application

### Actual Result

I see collapsed trace of the exception of my application

**Comment by Jean85** [comment]
The trace is automatically collected when capturing exceptions. If you're using `captureMessage()` instead, the trace is collected automatically only if the `attach_stacktrace` options is set to true.

Also: `sentry/sentry` just released 3.3.1, you're a bit behind...

**Comment by vladyslavstartsev** [comment]
@Jean85 it's our fault. We configured it wrong way
