### ISSUE TITLE
Tracing sends web profiler timings

### ISSUE THREAD

**Issue by pounard** [getsentry/sentry-symfony#528]
Hello,

First of all, thanks a lot for this great bundle, this is my first issue here.

It seems that the tracing sends timings for the web profiler requests, is there any way to avoid this ? I know that I probably should not use it on a devel environment (moreover Symfony's web profiler is disabled on all other environments) and this is not a bug, but is there a way to easily exclude some paths/routes from being watched by the sentry plugin ?

**Comment by ste93cry** [comment]
There is no built-in option to exclude certain routes from being considered for collecting tracing data, however you can set the `sentry.traces_sampler` option to a service defined as an invokable class that can filter out the request based on some conditions, e.g. the URL or the route path/name.

```yaml
services:
    App\CustomTracesSampler: ~

sentry:
    options:
        traces_sampler: App\CustomTracesSampler
```

```php
namespace App;

class CustomTracesSampler
{
    public function __invoke(\Sentry\Tracing\SamplingContext $sampleContext): float
    {
        // do something here to decide whether or not the tracing sample should be collected and return a float between 0 and 1 (inclusive)
    }
}
```
