### ISSUE TITLE
Is it possible to ignore some exceptions ?

### ISSUE THREAD

**Issue by pounard** [getsentry/sentry-symfony#529]
Sentry reports all Symfony exceptions, including 404 errors, is it possible to ignore some errors ?

**Comment by ste93cry** [comment]
You can configure the `IgnoreErrorsIntegration` exception by setting it under the `sentry.options.integrations` config

**Comment by Jean85** [comment]
You can find an example in https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md

**Comment by pounard** [comment]
Nice, thank you very much.
