### ISSUE TITLE
captureException/CaptureMessage method not working

### ISSUE THREAD

**Issue by ziat1988** [getsentry/sentry-symfony#531]
### Environment
 Symfony 3.4
 sentry/sentry-symfony : "^1.0"

### Steps to Reproduce.
My sentry works well with normal error exception.
But when I want to send the log message to sentry with try - catch manually then nothing sent to sentry. I use the code like:
  
use Sentry\SentryBundle\SentrySymfonyClient;
...
   try{
     ...
  // must throw error
     }catch(Exception $e){
     $sentryClient = new SentrySymfonyClient();
     $sentryClient->captureException($e);
   }

It is possible to do this with the libary?

**Comment by ste93cry** [comment]
I don't know if it's just for example purposes, but I don't get why you are instantiating the client inside the `catch` block. That means that every time a new exception is catched, you create a new client before capturing the error... To answer your question though, it should work, but the version of the bundle you're using is so old that it become unsupported, therefore my suggestion is to update it (we're at version `4.x`, which is still compatible with Symfony `3.4`)

**Comment by ziat1988** [comment]
Thanks for your answer. The reason I do this is there are one place in my application I don't want throw Error, I want instead continue the application even error happen and at same time send to sentry a notification of that error. So, I need a try catch and inside the catch, i need a piece of code to send to sentry. Please correct me if there are better way but the purpose for this is just that.

**Comment by ste93cry** [comment]
>Please correct me if there are better way but the purpose for this is just that.

That's the way, what I was saying is that it looks quite strange that you're creating a new instance of the client inside the `catch` block, even more if you also want to log other errors in some other places when they happen. Moreover, since you're using Symfony, you should use inject the `sentry.client` service where you need it and use it

**Comment by ziat1988** [comment]
I have inject the sentry.client instead  and it works perfect  even with my old version sentry/sentry-symfony 1.0.
Thanks a lot for your support.
