### ISSUE TITLE
Deprecation warning v4.1.4

### ISSUE THREAD

**Issue by Jamie-Vandenbalck** [getsentry/sentry-symfony#532]
### Environment

Sentry-symfony: v4.1.4
Symfony: v4.4
Doctrine DBAL: v2.13

### Deprecation warning

`The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.`

**Comment by ste93cry** [comment]
Duplicate of #483
