### ISSUE TITLE
Sentry rarely captures exceptions that cause CLI commands to fail and terminate

### ISSUE THREAD

**Issue by Bilge** [getsentry/sentry-symfony#533]
### Environment

PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:43) ( NTS )

How do you use Sentry?
Sentry SaaS 

Which SDK and version?
```
sentry/sdk                            3.1.0
sentry/sentry                         3.3.1
sentry/sentry-symfony                 4.1.4 
```

### Steps to Reproduce

1. Create CLI command.
2. Have CLI throw an uncaught exception.

### Expected Result

Exception is captured by framework and submitted to Sentry.

### Actual Result

Nothing. No issue created or updated because no event captured. Program just dies without ever informing anyone there was a problem.

Note that in older versions, this seemed to work quite consistently. I'm sorry I could not say which version broke this exactly, but I could swear, at one point, this behaviour was working as expected. More recent versions have all but broken this functionality.

**Comment by Jean85** [comment]
Have you tried creating a simple command that only throws? Or one that manually captures a message without throwing? Did you try the `sentry:test` command?

**Comment by Bilge** [comment]
Hmmm...

```
$ bin/console sentry:test
DSN correctly configured in the current client
Sending test message...
Message not sent!
<warning>Check your DSN or your before_send callback if used</warning>
```

**Comment by Jean85** [comment]
If you have differences between CLI and web, you may need to check your `php.ini`, which may be different. 
A common mistake is an outdated CA bundle.

**Comment by Bilge** [comment]
The ini files are mostly the same, therefore I would expect the CA bundles to be the same on CLI and web. I'm more concerned that dev is different from prod than web is different from CLI, though both are a concern I suppose. 

My most pressing concern is that the test tool does not expose the cause of the failure: if nothing else comes of this ticket, at the very least, I think this is something that needs to be fixed. The real reason for the failure must be present in the response from the server, but is lost through many layers of abstraction currently.

**Comment by Bilge** [comment]
I'm really trying my best here but it's not easy. Someone decided it was a good idea to just [swallow all exceptions with no notification whatsoever](https://github.com/getsentry/sentry-php/blob/7b938ca3f21e4bb437883af3f7552db6415112e6/src/Client.php#L168-L169). If we modify the source to dump the exception, all I get is the following

>GuzzleHttp\Promise\RejectionException: The promise was rejected in vendor/guzzlehttp/promises/src/Create.php on line 62

This is completely meaningless to me. "The promise was rejected" is not an HTTP error and I don't know what could cause this.

**Comment by Jean85** [comment]
The reason for swallowing exceptions there is to avoid a loop in which a failure triggers firing another event.

We discussed before to add the possibility to use a logger there, and IIRC there's already a small possibility to inject one somewhere.

**Comment by Bilge** [comment]
Just wanted to give you a quick update since I'm working with the enlightened @kelunik to figure out what's really going on here. There's a crazy stack of dependencies, as you may or may not be aware, where you rely on Guzzle, which relies on Symfony/HttpClient which relies on _either_ curl or Amp, **depending on the version of curl installed**. Thus we can explain the divergence in behaviour between dev and prod, because my dev is using curl 7.77.0 and prod is using curl 7.58.0. [When curl is less than 7.61 it uses Amp instead](https://github.com/symfony/http-client/blob/3db8fd57e0bb92b17e8c62c9f7beac87b47e303c/HttpClient.php#L46-L49), but Amp has bugs which we're currently looking to resolve. I suppose you could close this since it seems to be an Amp bug right now.

**Comment by kelunik** [comment]
Reproduction using `amphp/http-client` with `symfony/http-client` if `ext-curl` is not available or too old.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

Sentry\init(['dsn' => 'https://...@o918361.ingest.sentry.io/5861458' ]);

$hub = Sentry\SentrySdk::getCurrentHub();
$client = $hub->getClient();

print $hub->captureMessage('Test message');
```

```
➜ AMP_DEBUG_HTTP2_FRAMES=1 php -dzend.assertions=1 test.php
send SETTINGS <flags = 00, stream = 0, length = 24>
recv SETTINGS <flags = 00, stream = 0, length = 18>
send SETTINGS <flags = 01, stream = 0, length = 0>
send HEADERS <flags = 04, stream = 1, length = 200>
send DATA <flags = 01, stream = 1, length = 307>
recv WINDOW_UPDATE <flags = 00, stream = 0, length = 4>
recv SETTINGS <flags = 01, stream = 0, length = 0>
recv HEADERS <flags = 04, stream = 1, length = 73>
send WINDOW_UPDATE <flags = 00, stream = 0, length = 4>
send WINDOW_UPDATE <flags = 00, stream = 1, length = 4>
recv RST_STREAM <flags = 00, stream = 1, length = 4>
send RST_STREAM <flags = 00, stream = 1, length = 4>
```

The server sends a `RST_STREAM` indicating a protocol error, not sure which condition triggers this, yet.

**Comment by kelunik** [comment]
Something in the stack sets the `te` header field, which isn't supported for HTTP/2 unless it's set to `trailers`.

```
  [10]=>
  array(2) {
    [0]=>
    string(2) "te"
    [1]=>
    string(4) "gzip"
  }
  [11]=>
  array(2) {
    [0]=>
    string(2) "te"
    [1]=>
    string(7) "deflate"
  }
  [12]=>
  array(2) {
    [0]=>
    string(2) "te"
    [1]=>
    string(7) "chunked"
  }
```

**Comment by kelunik** [comment]
Fixed in https://github.com/amphp/http-client/releases/tag/v4.6.1. The cause is https://github.com/php-http/client-common/blob/4751c8ffc38ea18e3c77c1b9215f719fda6bd01d/src/Plugin/DecoderPlugin.php#L62 setting the `te` request header field, which is invalid for HTTP/2 requests.

**Comment by Bilge** [comment]
> 
> 
> Fixed in https://github.com/amphp/http-client/releases/tag/v4.6.1. The cause is https://github.com/php-http/client-common/blob/4751c8ffc38ea18e3c77c1b9215f719fda6bd01d/src/Plugin/DecoderPlugin.php#L62 setting the `te` request header field, which is invalid for HTTP/2 requests.

Confirmed this fixes it for me.

**Comment by Jean85** [comment]
Thank you for reporting it back! Can you report it to HTTPlug too?

**Comment by kelunik** [comment]
@Jean85 There's not too much they can do, because they don't know whether the request will be transferred using HTTP/1.x or HTTP/2.

https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.2 suggests they should be stripped by an intermediary, so that's what `amphp/http-client` does now.
