### ISSUE TITLE
Add support for symfony 5.1, 5.2, 5.3

### ISSUE THREAD

**Issue by whyte624** [getsentry/sentry-symfony#535]
Please, add composer constraints for new symfony versions.

**Comment by ste93cry** [comment]
Constraints are already fine, as you can see [here](https://semver.mwl.be/?package=symfony%2Fmessenger&constraint=%5E4.4.20%7C%7C%5E5.0.11&stability=stable). Which issue are you having?

**Comment by ste93cry** [comment]
I’m closing this because I don’t think there is anything we have to do. Feel free to reopen if you still think it’s not like I said
