### ISSUE TITLE
Return value of RequestListener::getUsername() must be of the type string or null,

### ISSUE THREAD

**Issue by xepozz** [getsentry/sentry-symfony#539]
I've tried to update sentry to last version with symfony 5.3.4 and I have the problem:
Stacktrace
```
Error: Uncaught TypeError: Return value of Sentry\SentryBundle\EventListener\RequestListener::getUsername() must be of the type string or null, int returned in /opt/app/vendor/sentry/sentry-symfony/src/EventListener/RequestListener.php:112
Stack trace:
#0 /opt/app/vendor/sentry/sentry-symfony/src/EventListener/RequestListener.php(70):
```
As I see the [UserInterface](https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Security/Core/User/UserInterface.php#L87) doesn't have a return type.
Can you please solve it?

**Comment by ste93cry** [comment]
The method [**has**](https://github.com/symfony/symfony/blob/a5fa6e5c2aed5fa928493bbe0c8c2df614e9d71d/src/Symfony/Component/Security/Core/User/UserInterface.php#L83) a return type, it's just that it could not be added without breaking BC and at the time this interface was created return type declarations were a dream. It's likely that in Symfony 6 it will be added, therefore if you're returning something different than a `string` (and according to the error it seems you are doing it) then it's something that you have to fix in your code, there is nothing to do from our side
