### ISSUE TITLE
Where can I see Spans?

### ISSUE THREAD

**Issue by simPod** [getsentry/sentry-symfony#540]
### Environment

How do you use Sentry?
self-hosted/on-premise (20.11)

Which SDK and version?
PHP latest

Symfony 5.3 based application

### Steps to Reproduce

1. I have enabled Tracing
```yaml
tracing:
    enabled: true
```

### Expected Result

I expected to see some info about my dbal queries in Sentry but all I can see are measurements of the whole SF requests

Where can I see any info about Spans, or what is the difference between having `tracing.dbal.enabled` set to `true` or `false`?

**Comment by simPod** [comment]
> This is weird. Actually, once you have tracing.enabled: true, and if you didn't explicitly disabled the DBAL hook it should just work out of the box, logging as child span of the main transaction each query that it happens 🤔 I have not enough context/information to understand why it doesn't happen, so a reproducer would be extremely helful

do you have any example what and where I should see? Maybe I just don't know where to look or my sentry version doesn't support it.

**Comment by Jean85** [comment]
I personally don't remember in which Sentry server version that was implemented, it's possible that you have to upgrade that to use it.

**Comment by simPod** [comment]
Might you share an example what does Tracing with dbal support looks like in UI? It's still kind of blurry for me.

**Comment by ste93cry** [comment]
I've taken this image from the official documentation of Sentry, so even though it doesn't represent what the PHP SDK produces, it is still representative of what the Performance Monitor feature is capable of. In the case of Symfony, the main transaction should be the HTTP request while the spans should be DBAL queries, calls to the cache, etc

![immagine](https://user-images.githubusercontent.com/1770485/129232759-44cc8aaf-014a-454f-9d13-bc652939c890.png)

**Comment by simPod** [comment]
I see, thank you!
