### ISSUE TITLE
Prepared queries when using Doctrine DBAL are not instrumented

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#544]
I'm using bundle 4.2.0 and using tracing for sentry.

When some SQL is used for selecting some data in sentry I see only a trace for sql.conn.prepare. But this does not show the time spent for selecting data itself.

Maybe there is a way to include such information in trace too? I want to see in trace how much time was spent for getting data from db

Thank you.

**Comment by ste93cry** [comment]
>Maybe there is a way to include such information in trace too?

It is already included, the same way it is for `sql.conn.prepare`. There is not enough context or information here to help you further, so some code to reproduce the issue would be helpful

**Comment by jokaorgua** [comment]
@ste93cry 

Initial data:
symfony 5.3.6
Doctrine-orm 2.9.4
sentry bundle 4.2.0

I've created a test command with the following code
```
$filter = new RequestFilterSearchAll();
$userIds = $this->userFetcher->all($filter);
dump($userIds);
```

UserFetcher.php::all
```
$query = $this->connection->createQueryBuilder()
            ->select(
                'some data'
            )
            ->from('users', 'u');

....filter processing.....

$result = $this->connection->fetchAllAssociative(
            $query->getSQL(),
            $query->getParameters(),
            $query->getParameterTypes()
        );
```

Executed command with bin/console test

The transaction was sent to sentry and I see the following

![image](https://user-images.githubusercontent.com/5228422/130194142-77dfa62b-e5bd-48cd-94ff-123a069d97bb.png)

So as you can see there is only sql.conn.prepare time. I want to know how to add there time for select itself, not only the prepare

**Comment by jokaorgua** [comment]
And here I have a screenshot with transaction made by following code
```
dump($this->entityManager->getRepository(User::class)->findAll());
```

![image](https://user-images.githubusercontent.com/5228422/130196514-a8a8d1fe-c92f-4d28-9895-0a2cd063036d.png)

Still no select timings

**Comment by jokaorgua** [comment]
if I'm right the issue is in https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/Connection.php#L1283
When params are not empty the prepare method is called and logged into sentry's transaction

But after that the $stmt->execute is called and it is not covered by tracing driver

Please correct me if I'm wrong

**Comment by ste93cry** [comment]
That is indeed the culprit of the issue, nice catch! I will open a PR soon to fix it
