### ISSUE TITLE
Handler Shutdown Error in Console Command

### ISSUE THREAD

**Issue by Vandersteen** [getsentry/sentry-symfony#55]
I have a long running Symfony Console command that starts a Process (Also from Symfony) on a regular interval.

Now in case there is an unexpected error I had a Shutdown Function registered before using sentry.

After some testing, it seems that sentry did not send those errors with just registering the bundle and config.

So i've added these in the execute method:

    $errorHandler = new \Raven_ErrorHandler($this->getContainer()->get('sentry.client'));
    $errorHandler->registerErrorHandler();
    $errorHandler->registerShutdownFunction();

And now it works.

Weirdly, some time after the errors did seem to come in. (like 30 min)
So my question would be: Do I need to add this Raven_ErrorHandler and call those two methods. Or is this done automaticaly ?

I was cruising around the EventListener in this repo but did not find anything alike.

**Comment by Vandersteen** [comment]
A crontab is not really an option for now, the long running command is more like a queue manager. And fires of the necessary Processes when requested. (maybe the regular interval made it sound like a cron)

It might be that the events are only triggered when the main command is closed, as a Symfony process is created in the same process group. Will try and experiment with it

**Comment by Jean85** [comment]
Then I will suggest to you to switch to a proper queue manager, like RabbitMQ.
I'm closing this since it's not a issue/bug with this bundle, but feel free to continue to respond here.

**Comment by Vandersteen** [comment]
I would just need to know if the following is true:

`It seems that the errors are sent by Sentry at the shutdown of the main process..`

If someone knows, would be great. I will experiment with it some time in the future, and report my findings here.

Thank you for your time
