### ISSUE TITLE
Sentry bundle breaks Symfony\Component\Lock\Store\PostgreSqlStore

### ISSUE THREAD

**Issue by FractalizeR** [getsentry/sentry-symfony#558]
### Environment

How do you use Sentry?
self-hosted.

Which SDK and version?
4.1

PostgreSqlStore has a hard-coded switch in it's code [here](https://github.com/symfony/lock/blob/5.3/Store/PostgreSqlStore.php#L260):
```switch (true) {
                case $driver instanceof \Doctrine\DBAL\Driver\PDOPgSql\Driver:
                case $driver instanceof \Doctrine\DBAL\Driver\PDO\PgSQL\Driver:
                    break;
                default:
                    throw new InvalidArgumentException(sprintf('The adapter "%s" does not support the "%s" driver.', __CLASS__, \get_class($driver)));
            }
```

So you just get an exception "The adapter "Symfony\Component\Lock\Store\PostgreSqlStore" does not support the "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriver" driver." when using Sentry with PostgreSqlStore.

**Comment by ste93cry** [comment]
I don't think there is any actionable to do here, we're use the decorator pattern so the best that it can be done is for Symfony to avoid the `instanceof` check and rather check the database platform. See also #530 for a similar issue which got fixed in the framework itself
