### ISSUE TITLE
Support Symfony 6

### ISSUE THREAD

**Issue by eerison** [getsentry/sentry-symfony#564]
<img width="1590" alt="Screenshot 2021-10-05 at 16 06 52" src="https://user-images.githubusercontent.com/6358755/136039800-e65a87b0-8285-438b-b99d-a33501c7f7b0.png">

I can see other deprecations messages related with SentryBundle, in different files.
do you prefer to open one PR resolving all deprecations or one pr by file?

**Comment by ste93cry** [comment]
Recently, we released some small enhancements as part of the next patch version, however I'm not sure it's correct nor that we should do this in this case as the scope looks a lot bigger and we didn't even started looking at supporting PHP `8.1`. Opinions?
