### ISSUE TITLE
Deprecation warning with Symfony 6

### ISSUE THREAD

**Issue by frame** [getsentry/sentry-symfony#580]
### Environment

sentry/sentry-symfony 4.2.5
doctrine/dbal 3.2.0
Symfony - 6.0.1

### Steps to Reproduce

Run any code, look for deprecations warnings

### Expected Result

No deprecation warning

### Actual Result

`Deprecated: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" class implements "Doctrine\DBAL\Driver\ServerInfoAwareConnection" that is deprecated The methods defined in this interface will be made part of the {@link Driver} interface in the next major release.`

Note: This is not quite the same as [issue 579](https://github.com/getsentry/sentry-symfony/issues/579) but might be related.

**Comment by ste93cry** [comment]
Apart from the fact that the intent of the deprecation makes it possible to remove a bunch of code that was added to wrap conditionally the `TracingDriverConnection` connection when the original one implemented the `ServerInfoAwareConnection` interface, I don't think there is a way to solve the issue related to the deprecation being raised: in fact, a runtime deprecation is now raised if you don't implement the interface [here](https://github.com/doctrine/dbal/blob/decf34ad95334180dec6497f47b1557de02ea9b0/src/Connection.php#L443), but the interface itself in turn is marked as deprecated and Symfony blindly parses the annotation and throws the notice. The only thing that you can do is to [suppress the error](https://symfony.com/doc/5.4/components/phpunit_bridge.html#baseline-deprecations)

**Comment by frame** [comment]
Thanks for your detailed reply, @ste93cry. I wasn't able to hide the error log entry via the SYMFONY_DEPRECATIONS_HELPER env variable, so I've decided to patch the `@depricated` annotation from the vendor package (`./vendor/doctrine/dbal/src/Driver/ServerInfoAwareConnection.php`). I left this comment so others might use the same approach before creating a similar ticket.
