### ISSUE TITLE
Incompatibility of TracingStatementForV2 with latest Doctrine DBAL

### ISSUE THREAD

**Issue by romainneutron** [getsentry/sentry-symfony#583]
### Environment

I use Sentry 3.3.4 and doctrine/dbal 3.2.0

### Actual Result

Sentry reports `Compile Error: Declaration of Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingStatementForV2::execute($params = null): bool must be compatible with Doctrine\DBAL\Driver\Statement::execute($params = null): Doctrine\DBAL\Driver\Result`

**Comment by Jean85** [comment]
Which version of the bundle are you using?

**Comment by romainneutron** [comment]
I'm using sentry/sentry-symfony 4.2.5

**Comment by romainneutron** [comment]
I'm sorry, I'm realizing I might have post this issue on the wrong repo :/

**Comment by Jean85** [comment]
`TracingStatementForV2` shouldn't be loaded/used with DBAL 3. Can you still reproduce the issue? Can you give use a small reproducer or a stack trace? We don't get this in our CI.
