### ISSUE TITLE
Allow symfony/cache-contracts 3

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-symfony#584]
Currently, only versions 1 and 2 are allowed.

**Comment by ste93cry** [comment]
The newer version added mixed as return type to different methods and I'm not sure how much easy would be for us to support both it and the older versions. A PR is more than welcome though

**Comment by Jean85** [comment]
We may get away with it only with a conditional declaration of the class. It's impossible to support 1 and 3 with the same piece of code...

Also, `: mixed` is supported since PHP 8, another reason to declare that conditionally.

**Comment by ste93cry** [comment]
Fixed in #588. @garak would you mind testing it out and see if everything works as expected?

**Comment by garak** [comment]
Works for me, thank you!

**Comment by Jean85** [comment]
Closing as fixed in 4.2.6
