### ISSUE TITLE
Log level dosen`t work for 4 version

### ISSUE THREAD

**Issue by YuriyChmil** [getsentry/sentry-symfony#589]
### Environment
Sentry SaaS (sentry.io)
Which SDK and version?
sentry-symfony 4.2.6
symfony 5.3.13
symfony/monolog-bundle 3.7.1
monolog/monolog 1.26.1

### Steps to Reproduce
I am trying to upgrade the sentry from 3 to 4 versions. To do this I used this [guide](https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-4.0.md)

Here is my **sentry.yml**

---
        sentry:
          register_error_listener: false # Disables the ErrorListener to avoid duplicated log in sentry
          dsn: '%env(SENTRY_DSN)%'
          options:
            environment: '%kernel.environment%'
            integrations:
              - Sentry\Integration\IgnoreErrorsIntegration #exclude validation errors

**monolog.yaml**

---
        monolog:
            channels: ['standard', 'mealPlan', 'quiz', 'email', 'stdout','admin']
            handlers:
                sentry:
                    type: sentry
                    hub_id: Sentry\State\HubInterface
                    level: !php/const Monolog\Logger::CRITICAL
                    bubble: false

### Expected Result

Sentry catch only messages with critical level or higher

### Actual Result
Sentry catch all kinds of errors(warning, notice etc...
![screenshot-sentry io-2022 01 12-11_56_28](https://user-images.githubusercontent.com/32869128/149118387-defa4588-b8ac-4f88-aaac-664f3f9b7959.png)

Also, I have tried to remove it from the monolog.yaml sentry configuration and set up it in services.yaml:

---
     Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $level: !php/const Monolog\Logger::CRITICAL
                $bubble: false

It doesn't help

**Comment by Jean85** [comment]
@ste93cry you wrote the guide, and IIRC you use it like this in prod... Do you see anything off here?

**Comment by YuriyChmil** [comment]
How we can fix it ?

**Comment by ste93cry** [comment]
>Do you see anything off here?

As far as I can tell, no

>How we can fix it ?

Are you able to reproduce it in a clean project?

**Comment by Jean85** [comment]
@YuriyChmil you can try to help by creating a PR with a reproducer of your bug. We already have a couple of tests that you can use as a starting point.

**Comment by YuriyChmil** [comment]
This options solve my problem.

`options:
        error_types: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING`

**Comment by Jean85** [comment]
`error_types` defaults to what is set on PHP's `error_reporting()`, so you probably had `E_ALL` there.
