### ISSUE TITLE
Upgrade sentry/sdk in composer

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#600]
Earlier I've opened a discussion https://github.com/getsentry/sentry-symfony/discussions/599

After making some research I've found this issue in sentry/sdk https://github.com/getsentry/sentry-php/issues/1220

So there is a bug with local variables in SDK. it was fixed in 3.3.1 and sentry-symfony uses 3.1

**Comment by ste93cry** [comment]
Actually there is nothing preventing this package to use the newer version. The composer constraint we're using is `sentry/sdk:^3.1`, which in turn requires `sentry/sentry:^3.1`. You can just update the latter manually using `composer update sentry/sentry` and it should download the latest version

**Comment by jokaorgua** [comment]
@ste93cry thanks. you are right. but after updating to sentry/sentry to 3.3.7 I still do not see local variables :(

**Comment by ste93cry** [comment]
PHP 7.4 introduced a new INI option called `zend.exception_ignore_args`. Please check that it is disabled

**Comment by jokaorgua** [comment]
@ste93cry thanks! that was the issue
