### ISSUE TITLE
Duplicated logs

### ISSUE THREAD

**Issue by miedzikd** [getsentry/sentry-symfony#618]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
e.g: Symfony, 4.2.8

### Steps to Reproduce

1. Install fresh symfony project
2. follow guide from [docs](https://docs.sentry.io/platforms/php/guides/symfony/)
3. open test page

To make this easier to test for you I created a repo ([here](https://github.com/miedzikd/symfony-sentry-guide))

### Expected Result

I should see only one error with additional information from the logger

### Actual Result

I see two errors. 
![ScreenShot 2022-04-15 15-24-27](https://user-images.githubusercontent.com/21012696/163577618-688e36f6-5761-4a58-a8a4-882f4c83e13d.png)

if I understood the documentation correctly, using the option `register_error_listener` = `false` should stop duplicate logs in Sentry. Unfortunately, this is not true.

**Comment by Jean85** [comment]
Looking [at your code](https://github.com/miedzikd/symfony-sentry-guide/blob/ab2442a1a990a2d2d8efdb9d73668ff1e47567ac/src/Controller/TestController.php#L26-L30), this is absolutely normal: you logged a message with an `error` level (an you get the first event) and then you throw an uncaught exception (generating the second event).

**Comment by miedzikd** [comment]
Thanks @Jean85 Heh :) So I misunderstand docs... 
But when I logged a message with an `info` level - can be this included in the event?

**Comment by Jean85** [comment]
To add that to an event, you need Breadcrumbs. To transfer Monolog entries into breadcrumbs, you would need https://github.com/getsentry/sentry-php/pull/1199, which is not released yet.

**Comment by miedzikd** [comment]
@Jean85 do you know if this PR will be released?
