### ISSUE TITLE
Attempted to call an undefined method named "pgsqlGetNotify" of class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection"

### ISSUE THREAD

**Issue by Hadrien45** [getsentry/sentry-symfony#626]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
doctrine/dbal 2.13.8
sentry/sentry-symfony 4.2.9
symfony/messenger 5.4.8
symfony/doctrine-messenger 5.4.8

### Steps to Reproduce

Run Symfony Messenger with the `bin/console messenger:consume` command to consume messages from PostgreSQL.

### Expected Result

It works, consuming messages...

### Actual Result

```log
In PostgreSqlConnection.php line 82:
                                                                                                                                                             
 Attempted to call an undefined method named "pgsqlGetNotify" of class "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection".  
```

### Solution

Downgrade symfony/doctrine-messenger to version `5.4.7`.  
The error seems to be related to https://github.com/symfony/doctrine-messenger/commit/7e03e21dfe36fa58d646f181d34dd889c8e5f38f

**Comment by Hadrien45** [comment]
Hi @Jean85 thank you for your reply.

**Comment by ste93cry** [comment]
Weird. It looks like the caller is calling the `pgsqlGetNotify()` method on our connection object rather than on the one returned by `getNativeConnection()`

**Comment by Hadrien45** [comment]
I used the fix proposed in this issue https://github.com/symfony/symfony/issues/46436#issuecomment-1135172337 and it works for me with 4.3.0

**Comment by OskarStark** [comment]
Will check, thank you
