### ISSUE TITLE
Deprecation warnings in 4.2.9

### ISSUE THREAD

**Issue by Khez** [getsentry/sentry-symfony#629]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-symfony 4.2.9
symfony 5.3.9
doctrine/dbal 2.13.4

### Steps to Reproduce
Run `phpunit` with [symfony phpunit-bridge](https://symfony.com/doc/current/components/phpunit_bridge.html)

### Expected Result
no warnings

### Actual Result
```
The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverForV2" class implements "Doctrine\DBAL\Driver\ExceptionConverterDriver" that is deprecated.
```

**Comment by Jean85** [comment]
Is this a duplicate of #483?

**Comment by ste93cry** [comment]
It is
