### ISSUE TITLE
The annotation "@doc" in method Raven_Client::parseDSN() was never imported

### ISSUE THREAD

**Issue by tristanbes** [getsentry/sentry-symfony#64]
Using 

PHP 7.1
Symfony 2.8.24
sentry/sentry-symfony 0.8.0
doctrine bundle 1.6.8
doctrine orm v2.5.6

when clearing the cache of the application, or trying to simply `app/console`, we get:

```
Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@doc" in method Raven_Client::parseDSN() was never imported. Did you maybe forget to add a "use" statement for this annotation? in /srv/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
Stack trace:
#0 /srv/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(727): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
#1 /srv/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
#2 /srv/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
#3 /srv/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(282): Doctrine\Common\Annotations\DocParser->parse('/**\n     * Pars...', 'method Raven_Cl...')
#4 /srv/app/vendor/doctrine/annota in /srv/app/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54
```
Clearing the cache manually, restarting php-fpm, re-installing vendors from scratch does not solve the problem.
Do you have an idea on what's causing Doctrine to try to parse the `@doc` ?

**Comment by Jean85** [comment]
This does not seem to be an issue with the Raven client, but with the doctrine configuration. What did you change that triggered this error? Maybe you're letting Doctrine parse all your folders (vendors included) for annotations, when you should otherwise specify the folder of your entities...

You should review your Doctrine's mapping config, like this part: https://symfony.com/doc/current/reference/configuration/doctrine.html#dir

I'm closing this since it's not Sentry-related, but feel free to continue posting here if you need further help.

**Comment by tristanbes** [comment]
Apart from minor composer update (only minor versions), no configuration was changed. :(

**Comment by Jean85** [comment]
You can revert one update at a time to see which update, apart from Sentry, broke your setup.

**Comment by CrazyMuffin** [comment]
@tristanbes I've recently run into the same problem - have you found the breaking package?

**Comment by tristanbes** [comment]
Yes, it was `schmittjoh/JMSSecurityExtraBundle` package, the settings "secure all service" was on. I turned it off and it fix the problem as far as I can remember.
