### ISSUE TITLE
ServerInfoAwareConnection deprecated

### ISSUE THREAD

**Issue by casahugo** [getsentry/sentry-symfony#644]
### Environment

version 4.3.0 and doctrine/dbal v3.3.7

### Steps to Reproduce
Upgrade doctrine dbal to v3.0 

### Expected Result
No logs

### Actual Result
Logs: User Deprecated: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingServerInfoAwareDriverConnection" class implements "Doctrine\DBAL\Driver\ServerInfoAwareConnection" that is deprecated The methods defined in this interface will be made part of the {@see Driver} interface in the next major release.

**Comment by Jean85** [comment]
Closing as duplicate of #483 & #579
