### ISSUE TITLE
Add support of serializeAllObjects in Serializer

### ISSUE THREAD

**Issue by jokaorgua** [getsentry/sentry-symfony#648]
It would be good to have support for enabling the flag serializeAllObjects in the standard serializer

This will add the ability to serialize internal object's properties, as said in phpdoc in code's class

There is also a reference with picture which illustrates the problem https://github.com/getsentry/sentry-php/issues/1054

**Comment by Jean85** [comment]
https://github.com/getsentry/sentry-php/issues/1054#issuecomment-670215808 reports the suggested modification. Adding an explicit option for this could break everything if a non-standard serializer is used. Not sure it's worth it. Maybe we can document how to do it easily?

**Comment by jokaorgua** [comment]
@Jean85 I've tried the suggested option to instantiate a serializer by myself. 

But this brings us to 'create a new client with the same options in config' which is not simple. Maybe I did something wrong.
Maybe you have a hint on how to 'clone' the current client, re-set a serializer and bind it back?

such a solution will solve this ticket.

**Comment by Jean85** [comment]
The serializer is defined as a service called `\Sentry\Serializer\Serializer`, maybe you can add a method call to `setSerializeAllObjects` with a compiler pass?

**Comment by jokaorgua** [comment]
@Jean85 could you please give a hint where the serializer is defined as a service ? I can’t find :(

**Comment by Jean85** [comment]
It's defined in PHP here: https://github.com/getsentry/sentry-symfony/blob/12d0f9674b8a829fdf1a2cfbb3fd6b94ec4de893/src/DependencyInjection/SentryExtension.php#L123-L125

In a compiler pass of your own, you can simply get the definition of the service, add a method call and call it a day!
