### ISSUE TITLE
support operation duration

### ISSUE THREAD

**Issue by gclove** [getsentry/sentry-symfony#651]
Can we support `operation duration`? I think there is such a display in the vue package.

> ![image](https://user-images.githubusercontent.com/3645410/133869436-b38b55e2-b497-4b1a-b8d0-c847ee4e4bf1.png)

> ![image](https://user-images.githubusercontent.com/3645410/133869505-45306cb3-3e3f-4fa4-9bd9-b1e13b872e74.png)

**Comment by cleptric** [comment]
![Screenshot 2022-11-21 at 17 02 55](https://user-images.githubusercontent.com/6617432/203101851-a70acde8-1910-42e6-87da-7dc42f8263d0.png)
Using v4.4 of the bundle, this works for me. let us know if you have any other problems with this.
