### ISSUE TITLE
Symfony 6 support?

### ISSUE THREAD

**Issue by sterichards** [getsentry/sentry-symfony#654]
I am unable to upgrade a Symfony 5.4 project to Symfony 6.0 due to it using sentry/sentry-symfony

Checking for deprecation notices gives the following notice:

> 2x: The "Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverForV3" class implements "Doctrine\DBAL\VersionAwarePlatformDriver" that is deprecated All drivers will have to be aware of the server version in the next major release.
    2x in DeprecationErrorHandler::shutdown from Symfony\Bridge\PhpUnit

**Comment by Jean85** [comment]
You can disregard those deprecations, they are not related to Symfony but to DBAL. In any case, we are unable to solve them, since we need to be compatible with both DBAL v2 and v3. See also #483
