### ISSUE TITLE
install and get infinite loop by composer

### ISSUE THREAD

**Issue by erdalceylan** [getsentry/sentry-symfony#694]
I'm also trying many computers with symfony 4.4 and 5.4 and sentry-symfony:3.5 and sentry-symfony:4.5 it goes into infinite loop

Example
`composer create-project symfony/website-skeleton:"^5.4" test_project`
`cd test_project`
`rm composer.lock`
`composer require sentry/sentry-symfony:^3.5`

and I get this infinite loop

OUTPUT : 
_Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Generating optimized autoload files
120 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Restricting packages listed in "symfony/symfony" to "5.4.*"
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove_

![image](https://user-images.githubusercontent.com/4347677/217922455-84a1cd7b-b4b3-44ec-9d42-eb2f2d7fe005.png)

**Comment by Jean85** [comment]
The issue depends on php-http/discovery 1.15 and the fact that it now brings a Composer plugin, see:
* https://github.com/php-http/discovery/issues/213
* https://github.com/getsentry/sentry-php/pull/1464

You can work around this by pinning discovery below 1.15, or by allowin/disallowing it explicitly as a plugin in Composer, using ` composer config --no-plugins allow-plugins.php-http/discovery [true|false]` as suggested in https://github.com/php-http/discovery/issues/213#issuecomment-1424302584.

**Comment by erdalceylan** [comment]
I updated my composer.json file and the problem was fixed thank you @Jean85        
`"php-http/discovery" : "1.14.3",` <- add this line
`"sentry/sentry-symfony": "^3.5",`

**Comment by cleptric** [comment]
For now, we can't really do much on our end besides locking the version to before `1.15`, which also has its downsides.
