### ISSUE TITLE
Set Current User

### ISSUE THREAD

**Issue by bassrock** [getsentry/sentry-symfony#7]
In the old monolog raven way, there was a way to create a custom processor that allows you to set the current logged in user and any associated data keys.

How could this be accomplished now?

**Comment by Jean85** [comment]
This should be a very nice feature!
Right now the user is identified by its session, but it may vary if you wipe the sessions or if they expire.

I would suggest to do so automatically in this bundle with:
 ```
$this->get('security.token_storage')->getToken()->getUser();
```
It should just be an overridabile behaviour.

**Comment by dcramer** [comment]
I'd love if we could find a way to expose the Sentry client.

e.g. does ``$this->get('sentry.client')`` work?

That'd make it easy to do everything the client allows, but I'm not familiar enough with Symfony to know if there's a good pattern for this.

**Comment by Jean85** [comment]
I'm trying to work on it. Right now I'm just adding a functionality that sets the username as the user ID in the raven client, but I'm not familiar enough with Raven... is a string ok as an ID?

Anyhow, `$this->get('sentry.client')` works, so yes, it's exposed right now. I'll open a PR to discuss this ASAP.

**Comment by Jean85** [comment]
Ok, my PR is merged. It uses the username as a user ID inside Sentry, but I think that more could be achieved.

The interesting approach should be an extensible one, where the dev can write a class that somehow provides additional information (user email at the very least!). I currently don't know how to achieve this.. Any suggestions?

**Comment by dcramer** [comment]
@Jean85 I think we should empower people to just pull in the client and write their own middleware if defaults dont work for them. The solution might simply be to document how to do this.

**Comment by Jean85** [comment]
Yeah that could be a way. Anyhow, we should suggest a way that doesn't collide with the standard approach. Now we are using a listener, and a user should use an other listener for his custom implementation; maybe we can force the listener priority?

**Comment by swquinn** [comment]
@dcramer and @Jean85 see my above proposed PR (#47) I think through using the event dispatcher and trigger certain events, e.g. `SET_USER_CONTEXT` and `PRE_CAPTURE` you can allow projects to simply tap into and set their own values using a subscriber/listener pattern to override the defaults set.

Of course, these projects already have the option to completely customize the client and exception listener classes if they want to, but that is a little more extreme.

My PR also includes an update to the `README.md` to illustrate how the above can work.

**Comment by Jean85** [comment]
#47 is now merged, and it can be widely used to do all kinds of customization on the event information, including the user!

**Comment by florentdestremau** [comment]
This is not working anymore with the new versions (`"sentry/sentry-symfony": "^3.4"`), I don't have any users linked to my errors. Is there a missing configuration on my side ?

**Comment by florentdestremau** [comment]
This is not working anymore with the new versions (`"sentry/sentry-symfony": "^3.4"`), I don't have any users linked to my errors. Is there a missing configuration on my side ?

**Comment by Jean85** [comment]
What version where you using before? If you were on 2.x, you need to enable the processing of PII, as per the upgrade guide.

**Comment by florentdestremau** [comment]
Ooooh thanks @Jean85 ! Totally missed out this point.

**Comment by blackarcanis** [comment]
Don't know if it's the right place or not for that, but I'm looking to a solution to set as "user:id" on Symfony the user "ID" instead of "username"...

Is there a quick win setup for that in the .yml for example of Sentry ? Setting the property we want to use as "user:id" ?

**Comment by Jean85** [comment]
There's no easy "config" for that, but the docs says that you just need to add another listener and alter the scope to do that, same as the bundle does here: 

https://github.com/getsentry/sentry-symfony/blob/6a4664c83f6a71717d45fcf8f30e067fa8da5cc0/src/EventListener/RequestListener.php#L83-L86
