### ISSUE TITLE
Add message id or content for exception thown in SF Messenger handlers

### ISSUE THREAD

**Issue by RicoLannez** [getsentry/sentry-symfony#703]
Hello,

I'm actually working at AssoConnect/Springly on a project on Symfony with Symfony messenger. Your SF messenger integration works fine but we were wondering if it should be possible to add some data such as the message id or content which would be a great addition for us in our debugging process. 

Is there some active development planned for that? If not maybe we can submit a pull request if you give us some hints on the best way to do the job. 🙂

Best regards

**Comment by cleptric** [comment]
https://github.com/getsentry/sentry-symfony/blob/master/src/EventListener/MessengerListener.php#L47
If you think we could add more information here, I'm happy to review a PR.

Besides that, you can always enhance your error events by calling `setTag`, `setData`, inside your message classes.
