### ISSUE TITLE
Re-map `ignore_exceptions`, add `ignore_transactions`

### ISSUE THREAD

**Issue by Jean85** [getsentry/sentry-symfony#710]
In https://github.com/getsentry/sentry-php/pull/1503 we re-added `ignore_exceptions`, and also added `ignore_transactions`.

We need to map those in the bundle config, and also we need to change the UPGRADE-4.0 docs, since we can dismiss the change requested in there.

**Comment by ruudvanderweijde** [comment]
I just ran into this issue as well. I was expecting to be able to use the options, as the other one is deprecated.
