### ISSUE TITLE
Add profiling service

### ISSUE THREAD

**Issue by Ciloe** [getsentry/sentry-symfony#713]
Hi there,

Regarding to the [documentation](https://docs.sentry.io/platforms/php/profiling/), we need to implement in the sentry init a `profiles_sample_rate`. Unfortunatly, using the symfony SDK project, we haven't access to the init.

The purpose is to add the `profiles_sample_rate` service like it's already available on `traces_sample_rate`. Like this documentation too : https://docs.sentry.io/platforms/php/guides/symfony/configuration/sampling/

**Comment by Ciloe** [comment]
Nice thanks ! I didn't see this option in the documentation : https://docs.sentry.io/platforms/php/guides/symfony/configuration/symfony-options/

**Comment by cleptric** [comment]
Yep, I'm aware that the docs only represent the PHP SDK. We'll follow up with specific docs for Symfony and Laravel soon.

**Comment by Ciloe** [comment]
Cool, and what more things, You added the `profiles_sample_rate`, why don't add `profiles_sampler` like `traces_sampler` ?

**Comment by cleptric** [comment]
The `profiles_sample_rate` is considered relative to `traces_sample_rate` or whatever the `traces_sampler` returns.
This means the profile is taken only if the transaction is sampled.
Hence, we didn't see a big use case for `profiles_sampler`.
