### ISSUE TITLE
Add maglnet/composer-require-checker 

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-symfony#716]
@cleptric we should avoid similar issues in the future by adding https://packagist.org/packages/maglnet/composer-require-checker in CI

_Originally posted by @Jean85 in https://github.com/getsentry/sentry-symfony/issues/714#issuecomment-1523646872_

**Comment by Jean85** [comment]
We can also use https://packagist.org/packages/irstea/composer-require-checker-shim if we don't want to pollute our dependencies.
