### ISSUE TITLE
4.9.0 version doesn't load the correct DBAL Platform

### ISSUE THREAD

**Issue by jdecool** [getsentry/sentry-symfony#730]
### Environment

- PHP 8.1.20
- Symfony 5.4
- DBAL 3.6.3 / ORM 2.14.3
- Sentry Symfony 4.9.0

### Steps to Reproduce

On a project I work, I've updated `sentry/sentry-symfony` from `4.8.0` to `4.9.0`.

After the update I've this exception when trying to interact with the database:

```text
In AbstractPlatform.php line 441:
                                                                               
  Unknown database type json requested, Doctrine\DBAL\Platforms\MySQLPlatform  
   may not support it.  
```

It seems that https://github.com/getsentry/sentry-symfony/pull/723 change the `AbstractPlaform` loaded instance.
In my configuration I specify the `serverVersion` in the Doctrine DSN.

With the `4.8.0` I've the `Doctrine\DBAL\Platforms\MySQL80Platform` which is loaded whereas when I update dependency to `4.9.0` load `Doctrine\DBAL\Platforms\MySQLPlatform` which not implement the `json` type mapping.

**Comment by ste93cry** [comment]
I bet the problem is that we're not implementing the `createDatabasePlatformForVersion()` method in the driver's `class`. As the fix seems rather easy, would you mind opening a PR?

**Comment by jdecool** [comment]
Sure.

I've test and it fix the bug.

I'm going to create the PR.

**Comment by jdecool** [comment]
I've just created https://github.com/getsentry/sentry-symfony/pull/731

**Comment by kov-lucas** [comment]
I think this is also breaking the `bin/console doctrine:migrations:diff` command, this is the only dependency that i've recently updated and now it is completely broken, i had to roll it back to 4.8.0

**Comment by cleptric** [comment]
Version [4.9.1](https://github.com/getsentry/sentry-symfony/releases/tag/4.9.1) was released which contains a fix for this issue.
