### ISSUE TITLE
After update to sentry-symfony:4.9 doctrine get please run the sync-metadata-storage command to fix this issue

### ISSUE THREAD

**Issue by mortezakarimi** [getsentry/sentry-symfony#732]
### Environment

| Package | Version |
|--------|--------|
| Symfony | 6.3 |
| Sentry-Symfony | 4.9 |
| MariaDB | 10.0 |
| PHP | 8.2 |

### Steps to Reproduce

1. Create application with symfony messenger active on it
2. Create migration for entities
3. Symfony messenger migration not created
4. Open application web UI get "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."
5. Try to sync-metadata-storage
6. Try to generate 

### Expected Result

When run all migrations or try to run make:migration if any change exist generate them, else show no change on database

### Actual Result

"The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue."
![screenshot-bugloos skiplanner localhost-2023 06 18-12_46_41](https://github.com/getsentry/sentry-symfony/assets/4004087/741ddf2a-c054-4899-bfd0-16dba76365c4)

**Comment by ste93cry** [comment]
This may be related to #730, as it's the only thing that I can think of that changed in `4.9.0` impacting this. A release with the fix is coming shortly, you can try `dev-master` in the meanwhile to see if it solves your problem.

**Comment by mortezakarimi** [comment]
Fixed in #731

**Comment by cleptric** [comment]
Version [4.9.1](https://github.com/getsentry/sentry-symfony/releases/tag/4.9.1) was released which contains a fix for this issue.
