### ISSUE TITLE
Tags options deprecated

### ISSUE THREAD

**Issue by andrii29** [getsentry/sentry-symfony#737]
Hello,
I tried to add global tags via `symfony.options.tags` in `config/packages/sentry.yaml` as it mentioned [docs](https://docs.sentry.io/platforms/php/guides/symfony/configuration/symfony-options). But, I'm getting errors about deprecation

```
php.INFO: User Deprecated: The option "tags" is deprecated since version 3.2 and will be removed in 4.0. Either set the tags on the scope or on the event. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The option \"tags\" is deprecated since version 3.2 and will be removed in 4.0. Either set the tags on the scope or on the event. at /path/to/app/vendor/sentry/sentry/src/Options.php:772)"} []
```

How to fix this deprecation warning and add tags globally?

Regards

**Comment by cleptric** [comment]
You can use `\Sentry\configureScope()`.

https://docs.sentry.io/platforms/php/guides/symfony/enriching-events/tags/

**Comment by andrii29** [comment]
@cleptric hi,
thank you for the answer. Can you provide an example how to add global tag?

Regards

**Comment by cleptric** [comment]
Somwhere in your code

```php
\Sentry\configureScope(function (\Sentry\State\Scope $scope): void {
    $scope->setTag('foo 'bar');
});
```

All events that happen afterwards will have the `foo` tag applied.

**Comment by andrii29** [comment]
can you provide example of symfony php file where should I add this for all errors to have this tag?

**Comment by cleptric** [comment]
Maybe in your `Kernel.php`. Will likely un-deprecate the option, so feel free to use it 😃

**Comment by cleptric** [comment]
We undeprecated the option and will include this in the next release.
https://github.com/getsentry/sentry-php/pull/1561
