### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by asvechkar** [getsentry/sentry-symfony#749]
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.9.2

### Steps to reproduce

composer update -W

### Expected result

Problem 1
    - Root composer.json requires sentry/sentry-symfony ^4.9.2 -> satisfiable by sentry/sentry-symfony[4.9.2].
    - sentry/sentry-symfony 4.9.2 requires symfony/psr-http-message-bridge ^1.2||^2.0 -> found symfony/psr-http-message-bridge[v1.2.0, v1.3.0, v2.0.0, ..., v2.3.1] but these were not loaded, likely because it conflicts with another require.

### Actual result

Now I have installed symfony/psr-http-message-bridge v2.2.0.

**Comment by cleptric** [comment]
My hunch is that the recent change in Symfony caused this. I opened https://github.com/symfony/symfony/issues/51192 for further clarification.

I assume this will be resolved once 6.4 is tagged, but this has yet to happen.
https://github.com/getsentry/sentry-symfony/pull/750

**Comment by derrabus** [comment]
This issue seems to be caused by Symfony Flex. As a workaround, you can add `"symfony/psr-http-message-bridge": "^2.3"`  to the `require` section of your project. This should make the error disappear while we're working on a more permanent solution.

**Comment by tacman** [comment]
Thanks, @derrabus add "symfony/psr-http-message-bridge": "^2.3" to require worked perfectly.

I wish json allowed for comments, so I could reference this issue as to why I installed that!

**Comment by nostadt** [comment]
> Thanks, @derrabus add "symfony/psr-http-message-bridge": "^2.3" to require worked perfectly.
> 
> I wish json allowed for comments, so I could reference this issue as to why I installed that!

I usually use the git commit for that. True, it's a little less convenient but works for me.

**Comment by cleptric** [comment]
Released in [4.12.0](https://github.com/getsentry/sentry-symfony/releases/tag/4.12.0)
