### ISSUE TITLE
Stack trace is missing due to bootstrap.php.cache

### ISSUE THREAD

**Issue by pguso** [getsentry/sentry-symfony#75]
In sentry i dont see a full stack trace cause of bootstrap.php.cache, is there a configuration i am missing?

**Comment by Jean85** [comment]
Can you post an example of what you are missing?
Why do you think that the boostrap has merit here?

Also, part of the stack trace is suppressed if it's outside of your app.

**Comment by Jean85** [comment]
Closing this since no further info were provided. Feel free to reply if you have them.
