### ISSUE TITLE
Sentry doesn't capture events on PROD environment, but does capture on DEV environment (Check your DSN or your before_send callback if used)

### ISSUE THREAD

**Issue by Softens** [getsentry/sentry-symfony#766]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### Versions

- sentry/sentry-symfony 4.11.0
- sentry/sdk 3.5.0
- sentry/sentry 3.21.0

### Steps to reproduce

1. Run php bin/console sentry:test on the server environment
2. Observe the following error output: Check your DSN or your before_send callback if used

### Expected result

An exception should be sent to Sentry and viewable

### Actual result
Local on dev environment:
```
DSN correctly configured in the current client
Sending test message...
Message sent successfully with ID b4445ea897cf43eb954723b953aba1ad
```

On server, running on PHP 8.2.11:
```
DSN correctly configured in the current client
Sending test message...
Message not sent!
<warning>Check your DSN or your before_send callback if used</warning>
```

In #533, this issue should be fixed in amphp/http-client version 4.6.1. I am using amphp/http-client version 4.6.3. I am not using a before_send callback and the DSN is set correctly. Any thoughts?

**Comment by Softens** [comment]
Awesome, that did a trick.
![image](https://github.com/getsentry/sentry-symfony/assets/22530994/e2affb6c-f09b-4915-93ce-f6a501bee92b)

**Comment by cleptric** [comment]
I am glad you were able to get to the bottom of your issue 🙂 
I'll close this one, then. Let us know if anything else is coming up.
