### ISSUE TITLE
sentry/sentry-symfony 4.12.0 requires sentry/sentry ^3.20.1 -> found sentry/sentry[3.20.1, 3.21.0, 3.22.0] but it conflicts with your root composer.json require (^4.0).

### ISSUE THREAD

**Issue by shakaran** [getsentry/sentry-symfony#778]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

3.5.0

### Steps to reproduce

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires sentry/sentry ^4.0, found sentry/sentry[4.0.0] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - sentry/sdk is locked to version 3.5.0 and an update of this package was not requested.
    - sentry/sdk 3.5.0 requires sentry/sentry ^3.19 -> found sentry/sentry[3.19.0, ..., 3.22.0] but it conflicts with your root composer.json require (^4.0).
  Problem 3
    - sentry/sentry-symfony is locked to version 4.12.0 and an update of this package was not requested.
    - sentry/sentry-symfony 4.12.0 requires sentry/sentry ^3.20.1 -> found sentry/sentry[3.20.1, 3.21.0, 3.22.0] but it conflicts with your root composer.json require (^4.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

### Expected result

sentry/sentry should update to 4.0 when using sentry/sentry-symfony 4.12

### Actual result

Cannot upgrade without downgrade sdk version

**Comment by cleptric** [comment]
Bumping the underlying PHP SDK to the new major version is a breaking change and will require a new major version of the Symfony SDK. We currently have no immediate plans for version 5, but we'll look at this beginning of 2024.

**Comment by bobvandevijver** [comment]
@cleptric Not necessarily. If you can make it such that the API for this bundle doesn't change, but support both SDK versions, it can be just a minor release. Looking at the changeset, I believe it should be possible as there do not seem to be breaking changes on code (judged from a quick look, so I might be wrong).

**Comment by cleptric** [comment]
We updated numerous interfaces as well as changed method signatures and option defaults.
So this is not possible, as all of these are breaking changes.
