### ISSUE TITLE
Update version of Sentry

### ISSUE THREAD

**Issue by sd-matt-b** [getsentry/sentry-symfony#779]
### Problem Statement

All versions of the Sentry package compatible with this package contain a dependency to an abandoned package. That's fixed in the next major version of Sentry `sentry/sentry 4.0.0`, to close that security vulnerability Sentry should be updated here.

### Solution Brainstorm

1. update Sentry to 4.0.*
2. see if it breaks anything
3a. if nothing broke, release new bugfix version for this package
3b. if something broke, see if it can be reasonably fixed

**Comment by cleptric** [comment]
We will work on a new major for Symfony starting Q1 2024. There are no security issues, the package in question exposes a few interfaces without a single line of actual implementation.
