### ISSUE TITLE
Support for sentry php 4.x

### ISSUE THREAD

**Issue by screenflavor** [getsentry/sentry-symfony#780]
### Problem Statement

Sentry php sdk 4.0.0 has been release on 2023-11-06. I cannot upgrade to it or the latest version 4.0.1 while using sentry-symfony because it supports only version 3.x (currently 3.22.1).

### Solution Brainstorm

I am asking for a new version of sentry-symfony which supports the latest version of sentry php 4.X.

**Comment by cleptric** [comment]
Same answer as in https://github.com/getsentry/sentry-symfony/issues/779

As the PHP SDK release contains breaking changes, we have to release a new major version of the Symfony SDK, something we’ll look into beginning Q1 2024.

**Comment by screenflavor** [comment]
I would like to know Is there any news around the support for sentry php 4? On github it looks like the 5.x (dev) version of sentry-symfony still references sentry version 3 (v3.20.1 in the composer.json). Can you give a rough outlook when a new major version will be out?
And second question for the time being is version 3 of sentry still maintained with security fixes? Can I see anywhere which versions are stable, supported and for how long?

**Comment by cleptric** [comment]
I haven't made any progress on the next major so far.
Version 4 of the Symfony SDK is still fully maintained, and so is Version 3 of the PHP SDK.
We never published any support time frames, if there is any kind of security issue, we'll release a fix for it.
