### ISSUE TITLE
Add support for sentry/sentry v4

### ISSUE THREAD

**Issue by lyrixx** [getsentry/sentry-symfony#781]
### Problem Statement

[Version 4](https://github.com/getsentry/sentry-php/releases/tag/4.0.0) has been released 2 weeks ago, and it would be nice to support this version.

This is not the case ATM:
https://github.com/getsentry/sentry-symfony/blob/2ab21d9e89321eb0ff8294f1536ab9a332afd0a5/composer.json#L31

### Solution Brainstorm

It looks like the V4 is compatible, so you can allow v3 or v4.

**Comment by cleptric** [comment]
Same answer as in https://github.com/getsentry/sentry-symfony/issues/780 & https://github.com/getsentry/sentry-symfony/issues/779

As the PHP SDK release contains breaking changes, we have to release a new major version of the Symfony SDK, something we’ll look into beginning Q1 2024.

**Comment by lyrixx** [comment]
Oups, sorry for the noise. I did not check for other issue 😢 
Good luck with the BC layer 🤗
