### ISSUE TITLE
Bump (or allow) sentry libraries to version 4

### ISSUE THREAD

**Issue by tacman** [getsentry/sentry-symfony#782]
### Problem Statement

This bundle doesn't use (or allow) the latest sentry libraries.

### Solution Brainstorm

https://github.com/getsentry/sentry-symfony/blob/master/composer.json#L30C30-L31C1

This might be as simple as change composer.json to

```json
 "sentry/sdk": "^3.4 || ^4.0",
 "sentry/sentry": "^3.20.1 || ^4.0",
```

**Comment by glennmcewan** [comment]
I've found an issue this morning which is related to sentry/sentry-php:
https://github.com/getsentry/sentry-php/pull/1503

The `IgnoreErrorsIntegration` has been removed in v4, and this bundle did the opposite of that for its v4 release:
https://github.com/getsentry/sentry-symfony/pull/385

It wouldn't be a simple change to the composer.json.

**Comment by tacman** [comment]
Would bumping the minimum PHP to 7.4 (which is already at EOL) or 8.0 help?  The issue you referenced mentioned something about a change between 7.2 and 7.3.  PHP 7.2 has been EOL for 3 years.

**Comment by cleptric** [comment]
No, it would not.

**Comment by cleptric** [comment]
> Would bumping the minimum PHP to 7.4 (which is already at EOL) or 8.0 help? The issue you referenced mentioned something about a change between 7.2 and 7.3. PHP 7.2 has been EOL for 3 years.

No, it would not, and we won't do this.

https://github.com/getsentry/sentry-php/releases/tag/4.0.0
Here is the link to the changelog. Bumping the SDK will introduce many breaking changes to userland code, outside of the Symfony SDK, hence we have to release version 5.0.0 of this SDK as well.

**Comment by glennmcewan** [comment]
Without derailing this too much, no. It's an old issue sure but that class has been removed in the core SDK, so this repo would need to make some changes to handle the deprecations.

**Comment by cleptric** [comment]
We'll tackle the SDK update in #783, closing this one.
