### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [getsentry/sentry-symfony#784]
### Problem Statement

This won't install with Symfony 7

    - Root composer.json requires sentry/sentry-symfony ^4.12 -> satisfiable by sentry/sentry-symfony[4.12.0].
    - sentry/sentry-symfony 4.12.0 requires symfony/config ^4.4.20||^5.0.11||^6.0 -> found symfony/config[v4.4.20, ..., 4.4.x-dev, v5.0.11, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.4.x-dev] but these were not loaded, likely because it conflicts with another require.
  Problem 4

### Solution Brainstorm

Add || ^7.0 to the Symfony components in composer.json

**Comment by cleptric** [comment]
https://github.com/getsentry/sentry-symfony/pull/761

**Comment by tacman** [comment]
Thanks -- I keep forgetting to check Pull Requests as well as Issues.
