### ISSUE TITLE
Update documentation for current versions of Symfony

### ISSUE THREAD

**Issue by tacman** [getsentry/sentry-symfony#788]
### Problem Statement

The documentation feels very dated.  It refers to Symfony 3.4 (released 6 years ago, EOL over 2 years ago), the instructions about flex are wrong (it's config/bundles.php, not Kernel.php), and has long explanations about very old versions.

sensio/framework-bundle is dead.  Yet it's almost the first thing you mention in the README.

### Solution Brainstorm

I know the philosophy is "compatibility first", but the README seems unnecessarily complicated.  I just want to do a "composer req..." set the DSN, and see my errors.  For example, instead of focusing on old versions, I wish you had documentation on how to use the Symfony vault.  

Ideally, the documentation would assume that the developer is using a current, supported version of Symfony.  Honestly, if they're not using a supported version of Symfony, the instructions for installation shouldn't be front and center.  It's like you're catering to the folks that refuse to modernize.  Like putting your fax number before your email. (You don't, but when I see "If you're using Symfony 3.4...", that's my reaction.)

I can make a few tweaks to the documentation if you're accepting PRs.

I know you're working on Symfony 7 and updates to the libraries, so it's a good opportunity to revisit the README.

**Comment by shakaran** [comment]
I am using your product commercially in a lot projects with Symfony 7, but from a year ago, it feels that Sentry it is not spending enough resources for keep this updated in last versions or at least it is not quick releasing. 

If the support is not good for all the paid projects that I have, I will have look for an alternative in other providers. Please dedicate more resources to this or just drop the support, so we decide more fast or change to another provider.

**Comment by cleptric** [comment]
To speak about docs, they'll get revamped with v5.0.0 which I'm currently working on.
We'll also add support for `doctrine/dbal 4.x`. What else do you see missing?

**Comment by cleptric** [comment]
Hey,

support for `doctrine/dbal 4.x` was shipped Feb 26. The work on the new major version is still ongoing, but given the small size of our team and other obligations taking my time, it might be a bit longer. The PR is already up and I expect to wrap this up soon. The README is greatly condensed and will be reflected in our docs with the release. https://github.com/getsentry/sentry-symfony/blob/c0ad7c1e06bf96735cbaffd25a2870c70db56d06/README.md

Sorry for not getting back to you, this sadly has slipped my mind.

**Comment by cleptric** [comment]
The README was just was updated, docs are in a different repository and will be updated separately.
