### ISSUE TITLE
Add conflicting package symfony/http-client v6

### ISSUE THREAD

**Issue by yard-mschwartz** [getsentry/sentry-symfony#794]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.13.1

### Steps to reproduce

Run an application with `sentry/sentry-symfony` in combination with `symfony/http-client-contracts` on version 3.x, which can be achieved by using `symfony/http-client` on version 6 or higher.

### Expected result

No errors

### Actual result

I was working on updating one of our applications to PHP 8.2, including a number of packages. The following error appeared running the automated tests:

```
PHP Fatal error:  Declaration of Sentry\SentryBundle\Tracing\HttpClient\TraceableHttpClientForV5::withOptions(array $options): Sentry\SentryBundle\Tracing\HttpClient\TraceableHttpClientForV5 must be compatible with Symfony\Contracts\HttpClient\HttpClientInterface::withOptions(array $options): static in /home/mschwartz/Documents/projects/testjeleefstijl/server/vendor/sentry/sentry-symfony/src/Tracing/HttpClient/TraceableHttpClientForV5.php on line 15
```

Turns out `TraceableHttpClientForV5::withOptions()` is defined as `public function withOptions(array $options): self`, whereas [the parent](https://github.com/symfony/http-client-contracts/blob/main/HttpClientInterface.php#L98) defines this as `public function withOptions(array $options): static`

I solved this adding `"symfony/http-client": "^5.4",` to our `composer.json`, because it was implicitly using version 6, which requires `symfony/http-client-contracts` version 3.

My suggestion is to add `"symfony/http-client": "^6|^7",` as conflicting packages.

**Comment by Jean85** [comment]
This seems an error on your side: we already use a separate class to handle v6 and further: https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/HttpClient/TraceableResponseForV6.php

Do you have custom code handling that part? Because that situation is checked on our CI, and it doesn't have issues.

**Comment by yard-mschwartz** [comment]
I'm not sure if I understand your question. Our project is not using `TraceableHttpClientForV5` anywhere as far as I can see. Symfony was merely complaining that `TraceableHttpClientForV5` was extending from an incompatible `HttpClientInterface`, because composer accidentally installed v6 of `http-client` for us. I solved this on our end by forcing `http-client` v5. Other Symfony packages were also still on `v5` so that checks out.

**Comment by Jean85** [comment]
I just noticed that our code uses the PHP version to decide which version of the interface should be loaded, and this doesn't seems right to me: https://github.com/getsentry/sentry-symfony/blob/692632a372219ef4a0ace8c8d7f385777de0552a/src/aliases.php#L67-L73

**Comment by ste93cry** [comment]
I checked what changed between `symfony/http-client:6.0` and previous versions and I didn't find anything suitable that we can use to do feature-detection. Any idea on how we could discern which version to load?

**Comment by Jean85** [comment]
The major change that is affecting us is the jump between contracts ^2.4 to ^3.0. We could detect the change there! This is the changes between the last 2 patch and 3.0.0: https://github.com/symfony/http-client-contracts/compare/v2.5.2...v3.0.0

The existence of `HttpClientInterface::stream` and `HttpClientInterface::withOptions` seems to be the path to follow!

**Comment by yard-mschwartz** [comment]
Great work guys! :clap:

**Comment by cleptric** [comment]
The fix was released in [4.13.2](https://github.com/getsentry/sentry-symfony/releases/tag/4.13.2)

**Comment by ce5530** [comment]
I'm working on upgrading symfony from 5.4 to 6.4 and facing the same issue.
"symfony/http-client": "^6.0",
"sentry/sentry-symfony": "^5.0",
I can't downgrade any package bc it conflicts with "symfony/framework-bundle": "^6.4".
The error that I get is the same:
PHP Fatal error:  Declaration of Sentry\SentryBundle\Tracing\HttpClient\TraceableHttpClientForV5::withOptions(array $options): Sentry\SentryBundle\Tracing\HttpClient\TraceableHttpClientForV5 must be compatible with Symfony\Contracts\HttpClient\HttpClientInterface::withOptions(array $options): static in /var/www/html/vendor/sentry/sentry-symfony/src/Tracing/HttpClient/TraceableHttpClientForV5.php on line 15

**Comment by yard-mschwartz** [comment]
Maybe the fix was only applied to the 4.x branch of `sentry-symfony`? Or the fix for 5.x isn't working.

**Comment by ce5530** [comment]
Just tried `setnry-symfony` with 4.13 and 4.14 versions, no luck

**Comment by Dherlou** [comment]
> I'm working on upgrading symfony from 5.4 to 6.4 and facing the same issue. ...

I just migrated one of our prod servers from symfony 5.4 to 6.4 as well and faced the same issue, whereas the same update worked fine on our dev and test server.
I cannot exactly say where the problem was, but removing the complete project directory, rebooting and redeploying the project fixed it, although I had already previously removed the vendor directory and restarted PHP (to clear OpCache).
