### ISSUE TITLE
Documentation error about "ignore_exceptions"

### ISSUE THREAD

**Issue by fernandosngular** [getsentry/sentry-symfony#798]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

4.11.0

### Steps to reproduce

1. I have sentry-symfony in 4.11 version in composer.json
2. I use documentation (in UPDATE.md) about ignore_exceptions for configure it, and it not is working

### Expected result

It not working

### Actual result

It not working with:
<img width="683" alt="Captura de pantalla 2024-01-08 a las 14 22 09" src="https://github.com/getsentry/sentry-symfony/assets/68990135/22528b54-695c-4c73-9ac3-7ee75c4cdc00">

If i use last setting it work:
<code>
when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            ignore_exceptions:
                - Symfony\Component\Security\Core\Exception\AccessDeniedException
                - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
</code>

**Comment by Lehren** [comment]
In my case it's not working because using it with Monolog turns the Exception into a string message. Don't know a way around that right now

**Comment by cleptric** [comment]
Version [5.0.0](https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-5.0.md) removed the `IgnoreErrorsIntegration`. The canonical way of ignoring exceptions is now the `ignore_exceptions` option.

```yaml
sentry:
    options:
        ignore_exceptions:
            - "RuntimeException"
```
