### ISSUE TITLE
Attempted to call an undefined method named "setTransportFactory" of class  "Sentry\ClientBuilder".  

### ISSUE THREAD

**Issue by N-M** [getsentry/sentry-symfony#851]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

5.0.0

### Steps to reproduce

1. Upgraded version from 4.0 to 5.0
2. Adjusted config to new version

Config:

![Screenshot from 2024-06-17 14-08-17](https://github.com/getsentry/sentry-symfony/assets/781417/94801932-0875-4368-9cb6-cbfe49e8eea0)

### Expected result

" Attempted to call an undefined method named "setTransportFactory" of class   
  "Sentry\ClientBuilder".  " should not be presented.

### Actual result

![Screenshot from 2024-06-17 14-06-13](https://github.com/getsentry/sentry-symfony/assets/781417/d98a91a2-e58b-47da-80c6-5afd901aabe4)

**Comment by Jean85** [comment]
Did you clear the cache? Have you tried a manual `rm -rf var/cache`? Sometime cache generated from the older version of the packages is still present and may generate this kind of issues when launching a Symfony command (and the `cache:clear` command suffers from this kind of issues).

**Comment by N-M** [comment]
> Did you clear the cache? Have you tried a manual `rm -rf var/cache`? Sometime cache generated from the older version of the packages is still present and may generate this kind of issues when launching a Symfony command (and the `cache:clear` command suffers from this kind of issues).

That was the cause of the issue. Thank you.
