### ISSUE TITLE
Missing documentation for Monolog Integration

### ISSUE THREAD

**Issue by DrauzJu** [getsentry/sentry-symfony#866]
### How do you use Sentry?

Sentry SaaS (sentry.io)

### SDK version

5.0.0

### Steps to reproduce

Hi!

We would love to use the Sentry Symfony Integration, especially the Monolog Integration would be very useful.

Unfortunately, we are stuck about how to achieve this. The current documentation (https://docs.sentry.io/platforms/php/guides/symfony/) seems to be outdated. The proposed way to register a monolog handler does not work anymore.

```bash
composer require sentry/sentry-symfony

# Add monolog integration config as described in https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration

bin/console cache:warmup
```

Error:

```
Symfony\Component\Config\Exception\LoaderLoadException

There is no extension able to load the configuration for "sentry" (in "/app/config/sentry.yaml"). Looked for namespace "sentry", found "framework", "twig", "monolog", "debug", "web_profiler" in /app/config/sentry.yaml
```

Additionally, the [current README](https://github.com/getsentry/sentry-symfony/blob/5.0.0/README.md) does not help, because it does not mention the Monolog integration. Can somebody give us a starting point / working example?

Thanks a lot for your work and your help!

### Expected result

We can use the Sentry Symfony package to report application errors to Sentry using a Monolog Handler.

### Actual result

Error:

```
Symfony\Component\Config\Exception\LoaderLoadException

There is no extension able to load the configuration for "sentry" (in "/app/config/sentry.yaml"). Looked for namespace "sentry", found "framework", "twig", "monolog", "debug", "web_profiler" in /app/config/sentry.yaml
```

**Comment by Steveb-p** [comment]
The error you're reporting is coming from Symfony itself. You don't have Sentry bundle enabled, so it cannot process the configuration you're giving.
