### ISSUE TITLE
Breadcrumbs handler is not installed by default

### ISSUE THREAD

**Issue by akovalyov** [getsentry/sentry-symfony#91]
There is an option for that -- https://github.com/getsentry/sentry-symfony/blob/8123affbeb636151b0d0cbe886d4d69100b3a5ce/src/DependencyInjection/Configuration.php#L101.
However, it is not used anywhere (except tests) -- https://github.com/getsentry/sentry-symfony/search?utf8=%E2%9C%93&q=install_default_breadcrumb_handlers&type=. 
Is it possible to fix this before releasing 2.0? :) Is there anything I can help with?

**Comment by Jean85** [comment]
Nope, that is currently used.
Everything there is under the `options` key, which is passed to the Sentry client constructor: 

https://github.com/getsentry/sentry-symfony/blob/e4aa2643e69ca99ea69c99ffc8a6535fe5153ae5/src/Resources/config/services.yml#L2-L6

Also, the default behavior of the Sentry client is to enable them by default, so only disabling it would be possible with your bug as you are reporting it.

**Comment by akovalyov** [comment]
@Jean85 thank you for the explanation, it makes sense now. How would one extend the default `Raven_Breadcrumbs_ErrorHandler` or change the class? Since it is not available in DI container, the only possibility now is to override the client and set the custom error handler manually. Is it the recommended way to go at the moment?

**Comment by Jean85** [comment]
As you can see from the Client source code: https://github.com/getsentry/sentry-php/blob/c196051d5c75c45773bb075b1f3bc761f028e2d1/lib/Raven/Client.php#L686-L690

The breadcrumb handler is not inside the client, but the other way around. What you need to do is (optionally) disable the default one, extend it and define it in your container, injecting the client as a dependency.

I'm closing the issue, but feel free to continue replying here.
